mattermost/mattermost-plugin-playbooks

- webapp/src/components/backstage/stage_edit.tsx
- webapp/src/components/backstage/stages_and_steps_edit.tsx
Adds a confirmation modal for stage removal.
Does not implement the custom modal for moving all the steps to another stage as this would involve even more custom UI for little benefit. Also unlike the design, it will actually allow you to delete a stage like you intended to do when you clicked delete on it. 
https://mattermost.atlassian.net/browse/MM-27032
> MM-27032 Confirm stage removal.

- .golangci.yml
- server/api/incidents.go
- server/api/playbooks.go
- server/api/playbooks_test.go
- server/command/command.go
- server/playbook/filter_options.go
- server/playbook/playbook.go
- server/playbook/service.go
- server/pluginkvstore/playbook_store.go
- server/sqlstore/incident.go
- server/sqlstore/playbook.go
- server/sqlstore/pluginapi_client.go
- server/sqlstore/store.go
- Based on #252 , so will need to rebase off that once it's merged (sorry @agarciamontoro)
- note for #252 : I think I was using transactions wrong, and needed to add the execer and queryer back to the sqlstore/store.go
- In order to move the sorting logic in `GetPlaybooksForTeam` completely into a SQL query, I'm adding two columns to the schema `Stages` and `Steps`. They won't be pulled out into the model, they're just there for sorting in SQL queries. I think this is pretty cool. This is why /not/ using an ORM was the best decision!
- Like #252, I'm eyeballing the SQL, so I'm sure I've made a few mistakes, sorry Alejandro
- Alejandro will take this over for the reviews and revisions, thanks!
- https://mattermost.atlassian.net/browse/MM-27002
> MM-27002: Playbook sql store

- webapp/src/components/assets/icons/dot_menu_icon.tsx
- webapp/src/components/assets/icons/file_icon.tsx
This adopts the dot menu and file compass icons from the mattermost webapp. Pending discussion at https://community-daily.mattermost.com/core/pl/z4skuuxooj8gpy7rcr85ze3wmh.
Before:
After:
https://mattermost.atlassian.net/browse/MM-26611
> MM-26611: use compass icons

- server/api/incidents.go
- server/api/incidents_test.go
- server/incident/incident.go
- server/incident/service.go
- tests-e2e/cypress/integration/frontstage/incident_creation_spec.js
- tests-e2e/cypress/integration/frontstage/incident_dialog_spec.js
- tests-e2e/cypress/support/plugin_api_commands.js
- tests-e2e/cypress/support/plugin_ui_commands.js
When starting an incident, prompt for an incident name (vs. the `channel name` currently provided), and then add a prompt for an optional description. The description ends up as the channel header.
When starting an incident from a post, this description will be pre-filled with the markdown we currently use to record a link to the post, but can be modified freely. We only show `The channel was created by the Incident Response plugin.` in the channel header if no description is provided.
Fixes: https://mattermost.atlassian.net/browse/MM-28311
> prompt for incident name and description

- webapp/src/components/backstage/editable_text.tsx
- webapp/src/components/backstage/playbook_edit.tsx
- webapp/src/components/backstage/profile_autocomplete.tsx
- webapp/src/components/backstage/share_playbook.tsx
- webapp/src/components/backstage/stage_edit.tsx
- webapp/src/components/backstage/stages_and_steps_edit.tsx
- webapp/src/components/backstage/step_edit.tsx
A grabbag of changes from a recent design review and some opinionated changes along the way.
* When sharing a playbook, show profiles on first click even before searching.
* Show "Add Slash Command" button until a slash command is added, and then automatically show slash command auto-complete on focus. (Requires parallel webapp changes.)
* Tweak step description adding and removing.
* Style placeholder text with italics:
Finally, allow `Save` at all times, and not just when there are changes. This eliminates a number of weird edge cases where the `Save` button sometimes shows up enabled and sometimes not, and always provides a safe "exit path" vs. having to figure out how to get out of editing without losing potential changes. As part of this, allow empty stage and step names, and just …
> Playbook edit polish

- README.md
We are hyperlinking "Mattermost Source Available License" twice, but each links to a different page.
Propose updating the second reference to "frequently asked questions", which links to the FAQ section in our docs.
@lieut-data @justinegeffen for reviewers (no permissions to add you as reviewers).
> Clarification to license section in README file

- webapp/src/components/checklist_item.tsx
React throws a warning when using `checked` without `onChange`. Since we use `onClick` with this component, use `defaultChecked` instead.
https://mattermost.atlassian.net/browse/MM-27983
> MM-27983: use defaultChecked when no onChange

- webapp/src/hooks.ts
`currentChannel` from the Redux store is changing unexpectedly, even if the channel itself is not changing -- depend on `currentChannel.Id` only instead to avoid flashing the RHS until the webapp is fixed.
Relates-to: https://mattermost.atlassian.net/browse/MM-28825
> currentChannelId vs currentChannel.Id

- server/sqlstore/incident.go
- server/sqlstore/migrate.go
- server/sqlstore/migrations.go
- server/sqlstore/store.go
- server/sqlstore/store_test.go
- server/sqlstore/support_for_test.go
- server/sqlstore/system.go
A rebased copy of #280. The original summary:
- I've changed the migration so we don't finish it when we are unable to create the extension, but only log the error. Also, in case the extension fails to be created, I've added a fallback so we don't use it (I considered implementing a noop SQL function so we don't need to check whether the real function exists, but we would have the same problem: does the user has permissions to add a function?)
- I've smoke-tested that the general Mattermost search is not affected by this change. Also, I'm 99% sure it won't affect anything because all the extension does is adding a dictionary and a function, which you need to explicitly call to get the behavior.
- Also, I was testing this mostly with the ñ letter, and after all was implemented, I tried to …
> MM-28332: Add a fallback for when unaccent is not available (now ready to merge)

- tests-e2e/cypress/integration/backstage/incident_list_spec.js
- webapp/src/components/backstage/incidents/incident_list/incident_list.tsx
When changing the filter settings on the incident list, reset pagination to avoid being stuck on a second page without any results.
Fixes: https://mattermost.atlassian.net/browse/MM-28038
> MM-28038: reset pagination on filtering

- server/incident/service.go
- server/incident/service_test.go
For consistency with other fields on the RHS, allow changing state even after ending the incident.
https://mattermost.atlassian.net/browse/MM-28030
> allow changing stages after incident is ended

- server/api/incidents.go
- server/api/incidents_test.go
- server/api/playbooks.go
- server/api/playbooks_test.go
- server/command/command.go
- server/incident/incident.go
- server/permissions/permissions.go
- server/playbook/playbook.go
- server/sqlstore/incident.go
- server/sqlstore/incident_test.go
- server/sqlstore/playbook.go
- server/sqlstore/playbook_test.go
- Simplifying permissions checking. If the user is not a member of the team, they cannot list incidents or commanders.
- No need to check that permission in the SQl queries--if the query is running, assume the requester has access to that team.
- I thought about making a `handler.checkTeamPermissions` and put that in front of everything, but we're not always sending in the team_id in the params (and trying to get it through the incident id or the channel id would just complicate it -- let's keep doing that in the individual handler functions).
- https://mattermost.atlassian.net/browse/MM-28797
> MM-28797 - Fix permissions in incidents and playbook

- server/command/command.go
- server/incident/service.go
- server/playbook/playbook.go
- server/sqlstore/playbook.go
- server/sqlstore/playbook_test.go
- Simplify the GetPlaybooksForTeams. We could have put the MemberOnly flag in the options, but I figured that should probably be kept for paging and searching options, the kind that are sent from the client, whereas RequesterInfo is more of the internal information. But I'm open to other suggestions. 
- Had a lot of trouble with the tests, that's what took half the day. Turns out I was modifying the original slice of playbooks, and then inserting them again into the next db, and that's why things were failing. It was a mess.
- Alternatively, we could get all memberIDs like in `GetPlaybooks` and keep the check in the Go code, but keeping it all in the store seems cleaner to me.
- https://mattermost.atlassian.net/browse/MM-28994
> MM-28949 - Fix the GetPlaybooksForTeam when used for starting an incident

- server/sqlstore/data_migration.go
- server/sqlstore/data_migration_test.go
Before #274, the `ChecklistItem` structs had two `time.Time` fields: `StateModified` and `AssigneeModified`. Now, those timestamps are stored as `int64` fields that contain the number of milliseconds since the unix epoch.
When doing the data migration, we used [`model.GetMillisForTime`](https://github.com/mattermost/mattermost-server/blob/30bd506e7676033bdfb632f566e538d6cd3d8be0/model/utils.go#L179-L182) directly on the timestamps, but we never checked whether they had a zero value. It turns out that converting the zero value of a `time.Time` using that function returns a negative number. Specifically, the value `-6795364578871`. This value is then stored in all items that were never checked (in which case, `StateModified` has this value) or that never got an assignee (in which case, …
> MM-29021: Fix timestamp bug in data migration

- .golangci.yml
More closely matches server golang-ci config
Removes some flaky inters affecting PRs: https://github.com/mattermost/mattermost-plugin-incident-response/pull/290
>  More closely match server golangci configuration, removing some flaky linters.

- server/command/command.go
- webapp/src/slash_command.ts
Unsurprisingly, this adds an `/incident info` slash command. I do have an E2E test, but it is based on the changes introduced on #293; as I want these changes to be merged before deploying to community tomorrow, I'm opening this PR without the test. I'll open a new one with the test tomorrow, when the commander slash command is merged.
- If not on an incident channel, it shows an ephemeral message `You can only show the details of an incident from within the incident's channel.`
- If on an incident channel:
- If command executed from webapp, it just opens the RHS. If it was already open, it shows an ephemeral message `Your incident details are already open in the right hand side of the channel.`
- If command executed from mobile, it shows the following, non-interactive, info:
> Add /incident info

- .circleci/config.yml
- Makefile
- plugin.json
- server/manifest.go
- webapp/src/manifest.js
Bump version to v1.0.0-alpha.1, and temporarily disable `golangci-lint` until we figure out why it's failing spuriously.
> Bump version and disable linting

- tests-e2e/cypress/integration/frontstage/slash_command_spec.js
This PR adds the E2E test for `/incident info` promised in #306.
https://mattermost.atlassian.net/browse/MM-28286
> Add E2E test for /incident info

- tests-e2e/cypress/integration/backstage/playbook_details_spec.js
- webapp/src/components/backstage/step_edit.tsx
When the slash command prompt in the playbook details backstage is blurred with an empty or only `/` value, just revert back to `Add a Slash Command` as though nothing was entered. This  makes it easy to click back in and trigger the autocomplete prompt right away.
Fixes: https://mattermost.atlassian.net/browse/MM-28037
> MM-28296: improved slash command autocomplete

- webapp/src/components/backstage/incidents/incident_list/incident_list.tsx
- webapp/src/components/checklist_item.tsx
- webapp/src/components/profile/profile_selector.tsx
Fix an issue with the `ProfileSelector` being given a `CustomComponent` that is redefined on every render. This breaks the internal logic of react-select, forcing it to render new DOM elements instead of reusing them, and ultimately losing focus. On an active site like community-daily, the re-renders almost most the component unusable.
The fix here was applied both to the backstage and the incident RHS for assignees, making it technically the requisite follow-up to https://github.com/mattermost/mattermost-plugin-incident-response/pull/260. I'm still not sure why the webapp insists on re-rendering practically everything so often.
While in here, I removed one thing tsc no longer complained about, and fixed another.
https://mattermost.atlassian.net/browse/MM-29158
> MM-29158: fix custom components in react select

- server/api/api.yaml
- server/api/incidents.go
- server/api/incidents_test.go
- server/incident/service.go
Fallback to just supporting POST against `/incidents/<id>/end`. The original ticket here called for creating `/incidents/<id>/end`, but that was effort done earlier for other reasons.
Fixes: https://mattermost.atlassian.net/browse/MM-26181
> MM-26181: deprecate /end-dialog endpoint

- webapp/src/components/rhs/incident_details.tsx
One stage:
Two stages:
Three stages, 2nd stage active:
Ten stages, incident ended, themed:
Many stages, third stage active:
https://mattermost.atlassian.net/browse/MM-28941
> MM-28941: stage progress bar

- server/incident/filter_options.go
- webapp/src/components/backstage/incidents/incident_list/incident_list.tsx
Another quick fix, this one to fix sorting by status by sending up `is_active` as the key instead of the unsupported `status`.
https://mattermost.atlassian.net/browse/MM-29371
> fix sort by status

- client/client.go
- server/api/api.go
- server/api/api.yaml
- server/api/api_test.go
- server/api/incidents_test.go
- server/api/playbooks_test.go
- server/api/subscriptions_test.go
- server/command/command.go
- server/incident/service.go
- tests-e2e/cypress/support/endpoints.json
- tests-e2e/cypress/support/plugin_api_commands.js
- webapp/src/client.ts
Just that, replacing all occurrences of `v1` with `v0`.
I considered coding a simple function that builds the API url prefix and call that from all the places that are using a path, but it's too late to fight paths and double slashes and stuff that will break before code freeze. So good old replace. We can do the right thing when we move to v1.
https://mattermost.atlassian.net/browse/MM-29286
> MM-29286: Change API version to v0

- tests-e2e/cypress/integration/frontstage/incident_creation_spec.js
- tests-e2e/cypress/integration/frontstage/incident_rhs_list_spec.js
- tests-e2e/cypress/support/plugin_api_commands.js
- webapp/src/actions.ts
- webapp/src/components/rhs/rhs_main.tsx
- webapp/src/reducer.ts
- webapp/src/rhs_opener.ts
- webapp/src/selectors.ts
- webapp/src/slash_command.ts
- webapp/src/types/actions.ts
- webapp/src/websocket_events.ts
- This changes how the redux works -- it's now a map to a map: `{teamId: {channelId: Incident}}`. True, we could keep it all in a `{channelId: Incident}` flatter map, but I think that makes unnecessary waste in the selectors. The downside is the complicated reducer state spreading to avoid mutating the store. Would appreciate a double check if you're able.
- I fixed how we were using reselectors--it's making more sense to me now.
- Oh! I'm a huge fan of TDD with cypress--it helped catch a huge bug in an earlier version of this (I was sending a message to clear the store when we changed channels, but that solution is racy -- this current implementation isn't).
- https://mattermost.atlassian.net/browse/MM-29608
> MM-29608 - Fix for RHS List across teams

- server/command/command.go
- server/incident/incident.go
- server/incident/mocks/mock_service.go
- server/incident/service.go
- server/incident/service_test.go
It's not possible to create a playbook on mobile, so tweak the `/incident start` interactive dialog to avoid mentioning this at all when invoked from mobile.
https://mattermost.atlassian.net/browse/MM-29380
> MM-29380: remove create playbook prompt on mobile

- server/command/command.go
- tests-e2e/cypress/integration/frontstage/slash_command/stage_spec.js
There was a missing return after the check for no arguments, so although the help text informing the user was posted, the function kept running. As the code following that check assumed that there was at least one argument, it panicked when trying to retrieve it.
I've also added an E2E test covering this case. I check that no error is posted in the footer but, if the plugin crashes, all remaining tests will fail. That is, we will know that something is wrong one way or another.
https://mattermost.atlassian.net/browse/MM-29699
> MM-29699: Fix crash after /incident stage with no arguments

- .circleci/config.yml
Re-enable golangci-lint now that the upstream orb has been updated.
> restore plugin-ci/lint

- client/doc.go
- client/incidents.go
- server/api/api.yaml
- server/api/incidents.go
- server/api/playbooks.go
- server/command/command.go
- server/incident/filter_options.go
- server/playbook/filter_options.go
- server/sqlstore/incident.go
- server/sqlstore/incident_test.go
- server/sqlstore/playbook.go
- server/sqlstore/playbook_test.go
- webapp/src/components/backstage/incidents/incident_list/incident_list.tsx
- webapp/src/components/backstage/playbook_list.tsx
- webapp/src/components/sortable_col_header.tsx
- webapp/src/types/incident.ts
All collection endpoints that support `sort`, `direction` and `search_term` (namely, `GET /incidents` and `GET /incidents/channels`) are now consistent. However, there are collections endpoints that only support a subset of those parameters. I did not add any code to support the missing parameters because we don't need it right now (and because adding new code at this stage does not seem like a good idea). The endpoints that don't support everything are:
- `GET /playbooks` does support `sort` and `direction`, but does not support `search_term`.
- `GET /incidents/commanders` does not support `sort`, `order` nor `search_term`.
I also removed the `status` value for the `sort` parameter because it feels redundant:
- status filtering is usually done through the `status` parameter
- we also …
> MM-26182: Standardize filtering parameters

- .circleci/config.yml
Avoid spamming telemetry from e2e tests by only setting the required RUDDER environment variables during the build step.
Fixes: https://mattermost.atlassian.net/browse/MM-29753
> set RUDDER env for build artifacts only

- server/api/api.go
- server/api/incidents.go
- server/api/incidents_test.go
- server/api/playbooks.go
- server/api/playbooks_test.go
- server/incident/incident.go
- tests-e2e/cypress/support/plugin_api_commands.js
This PR standardizes the HTTP status codes returned by the API. The changes affect only the API layer (I tried at first to modify all the layers: API, service and store; but I'd like us to decide together how to approach this). There are a few things more that we can do to standardize, as checking empty IDs as the first step of the data validation in the API, but I also left those for the data validation approach we follow.
The main changes are:
- Returning 400 (Bad Request) instead of 500 (Internal Server Error) when it is clear in the API layer that the data is not valid. This happens when the query parameters or the body values are not valid.
- Returning 403 (Forbidden) instead of 500 (Internal Server Error) when there is a permissions error.
- Returning 201 (Created) instead of 200 …
> MM-26194: Standardize HTTP status codes

- server/api/incidents.go
- server/api/incidents_test.go
- Check that the dialog's userID is the same as the requester's
- Thanks Juho!
- https://mattermost.atlassian.net/browse/MM-29886
> MM-29886 - Fix for createIncidentFromDialog allows creating incidents in arbitrary teams

- server/command/command.go
- server/permissions/permissions.go
- Check permissions before posting in an arbitrary channel
- https://mattermost.atlassian.net/browse/MM-29897
> MM-29897 - Fix for: /incident announce allows announcing to arbitrary channels

- server/api/incidents.go
- server/api/incidents_test.go
- Check that the user requesting to start an incident is a member of the playbook they are using to start the incident.
- Added a test for it.
- https://mattermost.atlassian.net/browse/MM-30189
> MM-30189 - Fix: Incident creation lacks checks for playbook permissions

- plugin.json
- server/manifest.go
- server/telemetry/rudder.go
- server/telemetry/rudder_test.go
- webapp/src/manifest.js
- Include playbook ID, bump version
- https://mattermost.atlassian.net/browse/MM-30207
- https://mattermost.atlassian.net/browse/MM-30208
> MM-30207 - include playbook id in telemetry; bump to v1.1.1

- tests-e2e/cypress/support/plugin_ui_commands.js
- webapp/src/components/backstage/profile_autocomplete.tsx
This adds more info to the auto-complete dropdown. I found that the profile component has exactly what we need.
**Where to find the change:**
1. Click Create a Playbook
2. On the RHS type in a name
**Expected Result:** We see the profile picture and name (display configuration dependent) in the dropdown suggestions
https://github.com/mattermost/mattermost-server/issues/15772
> [MM-15772] Showing more user details in the share playbook auto-complete

- client/client.go
- server/api/api.go
- server/api/incidents_test.go
- server/api/playbooks.go
- server/api/playbooks_test.go
Changed `HandleErrorWithCode` to only log the internal error, while it sends the public message to the client. I renamed the parameters in the function to make the distinction between both arguments clearer.
I also needed to change a couple of tests that were expecting the error where it no longer is. I reviewed all the places that were using this function and all of them look to be using it correctly.
https://mattermost.atlassian.net/browse/MM-30249
> MM-30249: Avoid sending internal errors to the client

- webapp/src/actions.ts
- webapp/src/reducer.test.ts
- webapp/src/reducer.ts
- webapp/src/types/actions.ts
- webapp/src/websocket_events.ts
When we leave a channel, the websocket event doesn't include the channel metadata: we only know the channel id. Avoid trying to reference a null `channel` object and instead rely solely on the `channelId` in the event.
Fixes: https://mattermost.atlassian.net/browse/MM-30191
> MM-30191: handle leaving channel without teamId

- server/incident/service.go
- tests-e2e/cypress/integration/frontstage/rhs/latest_update_spec.js
- tests-e2e/cypress/support/ui_commands.js
- Does what it says in the title.
- https://mattermost.atlassian.net/browse/MM-30206
> MM-30206: Update incident dialog should pre-populate status with previous update text

- docs/README.md
Replace existing link with this: https://mattermost.gitbook.io/mattermost-incident-management/end-users-guide/creating-and-managing-playbooks (or relative link equivalent).
> Playbook link is broken

- tests-e2e/cypress/integration/backstage/incident_list_spec.js
- webapp/src/client.ts
Calling `clientExecuteCommand` relies on the Redux store containing a current channel. If the first URL to be loaded is the one in the backstage, such channel does not exist. The proposed fix is simple: just defaulting to town-square when no current channel exists. I think this is a good solution, but I'm open to any other ideas you have (the best solution would be not to have a mandatory channel in the API endpoint, of course, but that would be a weeks long solution, probably).
https://mattermost.atlassian.net/browse/MM-30259
> MM-30259: Fix backstage bug

- server/incident/service.go
- tests-e2e/.eslintrc
- tests-e2e/cypress/integration/frontstage/incident_rhs_list_spec.js
- tests-e2e/cypress/support/plugin_api_commands.js
- webapp/src/index.tsx
- webapp/src/selectors.ts
- webapp/src/websocket_events.ts
- Now we're updating the incident list for every status post, even if we're currently not in that incident channel
- That kicks the incident list, which updates `Last updated` field in the RHS list
- This is one more step towards keeping a synced model of the incidents on the client side
- https://mattermost.atlassian.net/browse/MM-30787
> MM-30787 - Deleting a status post should update Last Updated field

- plugin.json
- server/manifest.go
- webapp/src/manifest.js
Bumping `v1.2.0-alpha.2` pre-emptively for next push.
N/A
> bumping v1.2.0-alpha.2 pre-emptively for next push

- server/api/playbooks.go
- server/api/playbooks_test.go
- webapp/package-lock.json
- webapp/package.json
- webapp/src/components/backstage/channel_selector.tsx
- webapp/src/components/backstage/playbook_edit.tsx
- webapp/src/websocket_events.ts
Enables selection of private channels in the broadcast option. 
Also fixes bug where users could possibly select channels they are not a part of by guessing an ID. 
If another member of the playbook is not a member of the channel selected, they will see "Unknown Channel" in the dropdown. They will still be able to change the values of other fields, or select a channel they are a member of. 
https://mattermost.atlassian.net/browse/MM-31187
> MM-31187 Enable broadcast to private channels.

- go.mod
- go.sum
I simply ran
```
go get github.com/mattermost/mattermost-plugin-api@631fdc447dbef8b3c06ac262d34c9ef0b8aaea4b
```
to get the latest commit from https://github.com/mattermost/mattermost-plugin-api/pull/79.
https://mattermost.atlassian.net/browse/MM-31255
> MM-31255: Bump plugin-api version

- server/incident/service.go
- tests-e2e/cypress/integration/backstage/incident_list_spec.js
- tests-e2e/cypress/integration/frontstage/rhs/latest_update_spec.js
- tests-e2e/cypress/support/server_api_commands.js
- tests-e2e/cypress/support/ui_commands.js
Check that the broadcast channel is public, and add information about it to the interactive dialog only in that case. If it is a private channel, a DM or a GM, then a generic message "This message will be broadcasted to a private channel." is added instead.
https://mattermost.atlassian.net/browse/MM-31237
https://mattermost.atlassian.net/browse/MM-31241
> MM-31241, MM-31237: Fix update status dialog

- webapp/src/components/assets/left_fade.tsx
- webapp/src/components/assets/right_fade.tsx
Safari's treatment of `linear-gradient` has `transparent` meaning black transparent (namely `rgba(0,0,0,0)` -- [reference](https://stackoverflow.com/questions/30673204/css-linear-gradient-transparency-misbehaving-only-in-safari)).
This is apparently according to spec, but results in the undesirable behaviour below as we try to fade out the image assets in the backstage:
Fix this by making a transparent version of the background colour over which to apply the gradient ([reference](https://stackoverflow.com/questions/30673204/css-linear-gradient-transparency-misbehaving-only-in-safari)):
https://mattermost.atlassian.net/browse/MM-31242
> MM-31242: fix unusual backstage shadows

- webapp/src/components/backstage/backstage.tsx
- webapp/src/components/backstage/incidents/incident_details/incident_details.tsx
- webapp/src/components/backstage/playbook_edit.tsx
- webapp/src/components/backstage/styles.tsx
Set a minimum height on the headers of the playbook backstage edit screen to prevent their collapsing under flex rules.
Before:
After:
Fixes: https://mattermost.atlassian.net/browse/MM-31240
> MM-31240: Set min height on backstage header

- server/command/command.go
- tests-e2e/cypress/integration/frontstage/slash_command/commander_spec.js
Change the text of the ephemeral message from "You can only show..." to "You can only see..." in command.go
Fixes: https://github.com/mattermost/mattermost-server/issues/16423
> Change the text of the ephemeral message from "You can only show..." to "You can only see..."

- tests-e2e/cypress/integration/backstage/playbook_details_spec.js
- webapp/src/components/backstage/channel_selector.tsx
- webapp/src/components/backstage/playbook_edit.tsx
Keep showing `Unknown Channel` when a private channel is configured as the broadcast channel in the backstage, but restore showing `Select a channel` when none is selected at all.
As part of writing the unit tests here, I discovered it was impossible to type a channel name: search was broken. I restored this behaviour with a simple `includes` scan on id, name and display name.
Fixes: https://mattermost.atlassian.net/browse/MM-31243
> MM-31243: broadcast channel tweaks

- .circleci/config.yml
- tests-e2e/cypress/integration/frontstage/incident_rhs_list_spec.js
- tests-e2e/cypress/integration/frontstage/slash_command/test_spec.js
- tests-e2e/cypress/support/ui_commands.js
- upgraded postgres in the e2e tests
- added a bunch of little things to stop the e2e tests from failing. E.g., the "Search" bar and its drop down were activating after clicking on the incident-management channel header button, and hiding components below it. Why now? I don't know.
- https://mattermost.atlassian.net/browse/MM-31683
> [MM-31683] Fixing e2e and postgres

- webapp/src/websocket_events.ts
When a user is added to a channel, we query the server to determine if this is an incident. If not, the client dutifully throws an 404 error, but we failed to handle that from the caller and treat it as a non-error. Fix this.
Fixes: https://mattermost.atlassian.net/browse/MM-31007
> MM-31007: handle err fetching incident by channel

- webapp/src/components/backstage/step_edit.tsx
- webapp/src/utils.test.ts
- webapp/src/utils.ts
The `Textbox` component from webapp requires an `id`, throwing an exception in development environments when we validate props at runtime.
This doesn't appear in a cloud/production environment, where runtime prop checking is disabled, and thus must be verified locally.
Fixes: https://mattermost.atlassian.net/browse/MM-31919
> MM-31919: set id when rendering Textbox

- .circleci/config.yml
- (as described in channel) This 'fixes' the e2e test problems we've been having. A lot (all?) of the e2e trouble Christopher was having on #429 was because of recent changes to master. I'm not sure what made so many (~27) tests fail, but it has caused a lot of wasted engineering effort. I can't tell if this will be fixed by moving to the cloud prerelease docker image (I'm waiting on devops to help us get it working). But after adding e2e test suites for 5.31, everything passes (after disabling those admin "upgrade your server" notices).
So, my proposed solution is to:
- e2e test with master (for now, until we move to the cloud prerelease image), which will fail
- e2e test with 5.31, which will pass
-  Christopher is going to turn off the requirement that all tests pass before merging, at …
> testing e2e with master & 5.31 mattermost docker images

- .circleci/config.yml
- Need to check to see if this makes circle-ci ignore the `e2e-cypress-tests-master` job
- none
> Ignore e2e-cypress-tests-master on master branch

- server/telemetry/rudder.go
Add missing information in the telemetry data.
@Adovenmuehle, one of the fields I just added to the incident structure (`ReminderTimerSeconds`) is only present in a specific event, as it does not make much sense to send it with the others that relate to incidents. Is that ok for your data processing, or do you guys need us to always add the same fields for the events that refer to the same data type?
https://mattermost.atlassian.net/browse/MM-32051
> Add telemetry on reminder and broadcast features

- server/api/incidents.go
- server/api/incidents_test.go
- server/incident/incident.go
- server/plugin.go
- server/telemetry/noop.go
- server/telemetry/rudder.go
- webapp/src/client.ts
- webapp/src/components/rhs/rhs_tab_view.tsx
- For v1 of Timelines, Jason wanted to have the ability to check whether or not people were using it.
- Added a `frontend` event (open to suggestions on naming) for all telemetry coming from the frontend. Added `timeline_tab_clicked` to record this one (also open to suggestions).
- Why not handle this on the frontend? I did at first, but I found I was duplicating the boilerplate info we want to have everywhere, and I wanted to be absolutely sure we were using the identical identifier ids, field names, etc. as the backend was sending, so I think it's easier if we do it this way. Less error prone.
- https://mattermost.atlassian.net/browse/MM-32357
> MM-32357 Telemetry for timeline tab

- webapp/src/components/checklist_item.tsx
- webapp/src/components/profile/profile_selector.scss
- webapp/src/components/profile/profile_selector.tsx
To facilitate using the profile selector with the new "assignee" button, a `right: 0` property was unconditionally added. Unfortunately, this shifted all the profile selectors as such, causing problems for the commander dropdown when the RHS shrinks in size for smaller windows:
As a workaround, pass in a new `showOnRight` prop to conditionally set
this field:
Ideally, we'll revisit this component in the future.
Fixes: https://mattermost.atlassian.net/browse/MM-32516
> MM-32516: selectively align profile selector to right

- build/manifest/main.go
- plugin.json
The `ReleaseNotesURL` for the most recent `v1.3.1` still points at `v1.2.0`, since this field remains hard-coded. For future versions, update the manifest tooling to generate this too, using the latest tag.
I'm not going to fix v1.3.1, but will just amend the 1.2.0 release notes with a note pointing at v1.3.1 as well.
N/A
> generate release_notes_url

- server/incident/service.go
- server/incident/service_test.go
While the automatic promotion to channel admin doesn't work with managed team schemes, it does still work in the vanilla case. Keep the "base" functionality for customers not using advanced permissions by just logging a warning when this promotion fails.
Fixes: https://mattermost.atlassian.net/browse/MM-25755
> log a warning only when failing to promote commander to channel admin

- build/manifest/main.go
- There's no way to narrow down the `git tag` command to filter (with a glob or regex) so using the simple rule:
- If there are multiple tags, we care most about tags that start with `v`, and for simplicity just use the first one we find.
- none
> Use only one version when naming the build

- server/command/command.go
- tests-e2e/cypress/integration/frontstage/incident_rhs_list_spec.js
- tests-e2e/cypress/integration/frontstage/rhs/header_spec.js
- tests-e2e/cypress/integration/frontstage/rhs/open_spec.js
- tests-e2e/cypress/integration/frontstage/rhs/timeline-spec.js
- tests-e2e/cypress/support/index.js
- webapp/src/types/incident.ts
- List all non-archived incidents
- No tests because it's a quick fix on a function that isn't tested (not testable with the e2e tests, unless we set a "pretend not mobile" flag)
- https://mattermost.atlassian.net/browse/MM-32852
> MM-32852 - Fix for Mobile app: `/incident list`

- server/api/incidents.go
- server/api/incidents_test.go
- server/api/playbooks.go
- server/api/playbooks_test.go
- server/command/command.go
- server/incident/incident.go
- server/permissions/permissions.go
- server/sqlstore/incident.go
- server/sqlstore/incident_test.go
Guests will now have full access to the incidents they are a member of. They will now not have access to playbooks or the ability to create incidents. 
This is functionality side only. The UI still makes it seem like they can do some of this, but will error (with a message)
https://mattermost.atlassian.net/browse/MM-32452
> MM-32452 Allow guest users access to their own incidents.

- tests-e2e/cypress/integration/frontstage/rhs/timeline-spec.js
- webapp/src/components/checklist_item.tsx
- webapp/src/components/rhs/rhs_shared.tsx
- webapp/src/components/rhs/rhs_timeline.tsx
- Moving the hovermenu up a bit so it doesn't hide the `details` icon. This makes it a tad more difficult to click, but it's consistent with how hovermenus work in UIs in general. Please try it out (it's tough to describe the interaction in photos).
- The Incident Timeline notice shows when there are no events (either because the incident had activity before v1.4.0, or because the events were removed). 
- The timeline was using the `reported` event to figure out when the event time starts, but if that's manually removed it wouldn't exist. So using the incident `create_at` field instead (should have used that from the start anyway). I can't think of why that wouldn't be the `reported at` time, can anyone else think of why that would cause a problem?
- e2e tests are broken, probably because …
> MM-32853 & MM-32951 - Hovermenu tweaks and timeline notice

- webapp/src/components/checklist_item.tsx
This PR fixes the height of the checklist item containers. I simply removed the `ChecklistItemContainerLive` component, replacing its only usage with `ChecklistItemContainer` (which was not used anywhere else that was not dead code, actually).
| Before 	| After 	|
|-	|-	|
| ![image](https://user-images.githubusercontent.com/3924815/109290940-95ab7980-7828-11eb-89f5-92b5bc681a51.png) 	| ![image](https://user-images.githubusercontent.com/3924815/109290989-a65bef80-7828-11eb-9756-90587a838900.png) 	|
https://mattermost.atlassian.net/browse/MM-33301
> Fix height of checklist item containers

- webapp/src/components/backstage/profile_autocomplete.tsx
React-select has a prop `filterOption` for doing what we were incorrectly doing when grabbing the data from the server. This PR simply moves the filtering logic where it should be.
I found this while working on the new user selector in https://github.com/mattermost/mattermost-plugin-incident-management/pull/440, but I did not want to add more noise there. Hence, this independent PR.
https://mattermost.atlassian.net/browse/MM-32313
> Use filterOption in ProfileAutocomplete

- webapp/src/components/backstage/incidents/incident_details/export_link.tsx
- webapp/src/components/backstage/incidents/incident_details/incident_details.tsx
- webapp/src/components/backstage/playbook.scss
- webapp/src/components/backstage/playbook_list.tsx
- webapp/src/components/backstage/shared.tsx
The styling of the banner dates back to when we had a left hand side bar in the backstage (https://github.com/mattermost/mattermost-plugin-incident-collaboration/pull/70/)!
This PR moves the old CSS to a shared style component and updates its width to simply `100%`. I also had to add a `left: 0` so the banner for the exported channel in the incident details view is correctly placed. The `banner__text` class was not defined anywhere, so I ignored it.
https://mattermost.atlassian.net/browse/MM-32113
> MM-32113: Fix banner width

- webapp/src/components/backstage/automation/invite_users_selector.tsx
The component was filtering the invited members out of the list that is fetched when the component is mounted. This list is capped at 100 users (the default for getUsers), so if the invited member was not originally there, it was not shown in the component.
This PR fixes the bug by pre-fetching all the invited members. In particular:
1. Fetch all the invited members on component mount.
2. If the user has not typed anything in the search box, just pass the fetched members to react-select as the group of invited members. All the invited members will be there.
3. If the user has typed something in the search box, rely on the server-side filtering. This is the tricky part: if there are more than 100 hits for your search term, it is possible that the invited member is still lost, but this also …
> MM-33439: Fetch invited users independently

- server/api/incidents.go
- tests-e2e/cypress/integration/frontstage/incident_rhs_list_spec.js
- tests-e2e/cypress/integration/frontstage/rhs/header_spec.js
- tests-e2e/cypress/integration/frontstage/rhs/latest_update_spec.js
- tests-e2e/cypress/integration/frontstage/rhs/open_spec.js
- tests-e2e/cypress/support/index.js
- Trimming and testing the submitted message, rejecting the interactive dialog request if the message is empty
- e2e tests
- https://mattermost.atlassian.net/browse/MM-33310
> MM-33310 "Message" in status update modal accepts empty character string

- server/api/incidents.go
- webapp/src/client.ts
- Add `doFetchWithoutResponse`, use that when we're not expecting a body
- Fix frontend telemetry endpoint to use `StatusNoContent` and `doFetchWithoutResponse`
- https://mattermost.atlassian.net/browse/MM-33817
> MM-33817 Javascript error when deleting a timeline event

- webapp/src/components/rhs/rhs_timeline.tsx
- @prapti noticed an edge case when the filter filtered out all events, a piece of the timeline's line still showed. So don't return the Timeline element if there are no filtered events. https://github.com/mattermost/mattermost-plugin-incident-collaboration/pull/487#pullrequestreview-618079651
- https://mattermost.atlassian.net/browse/MM-34207
- https://github.com/mattermost/mattermost-plugin-incident-collaboration/pull/487#pullrequestreview-618079651
> MM-34207: css issue with RHS timeline

- .golangci.yml
Eliminate a number of unnecessary warnings for our product (at this time), e.g.:
```sh
> golangci-lint run ./...
server/config/configuration.go:14:20: fieldalignment: struct with 48 pointer bytes could be 40 (govet)
type Configuration struct {
^
server/config/service.go:15:18: fieldalignment: struct with 56 pointer bytes could be 32 (govet)
type ServiceImpl struct {
^
server/bot/bot.go:12:10: fieldalignment: struct with 48 pointer bytes could be 40 (govet)
type Bot struct {
^
```
> golangci: disable fieldalignment

- webapp/src/components/backstage/styles.tsx
Ensure the font color is inherited, fixing this:
to render like this:
Fixes: https://mattermost.atlassian.net/browse/MM-33942
> MM-33942: fix preferences styling

- client/client.go
- client/incident.go
- client/incidents.go
- client/playbook.go
- client/playbooks.go
- client/playbooks_test.go
- server/api/api_test.go
- server/api/incidents_test.go
- server/api/playbooks_test.go
Introduce the playbooks service to the Go client. Make `page` and `perPage` parameters required when listing, even for incidents, otherwise the results are generally unexpected or mistakenly wrong when the client author forgets to paginate.
Fixes: https://mattermost.atlassian.net/browse/MM-26944
> MM-26944: expose playbooks service in Go client

- webapp/src/components/backstage/playbook_edit.tsx
The default when searching users through `GET /users/search` is to return only the active ones, but we need to be specific when retrieving all users in a team via `GET /users`, as the default is to return active and inactive users.
It is actually a bit weird, as there are [two boolean query parameters, `active` and `inactive`](https://api.mattermost.com/#tag/users/paths/~1users/get), mutually exclusive, that both default to false. They actually mean "only active" and "only inactive", so both being false means "both active and inactive".
Anyway, the change just adds the `active: true` option to get only active users, and I had to fill the other precedent parameters with their default values.
https://mattermost.atlassian.net/browse/MM-33809
> Retrieve only active users

- webapp/src/components/checklist_item_input.tsx
Fixes the random scrolling issue on the playbook edit screen by preventing the command box from grabbing focus if it's opened already. 
https://mattermost.atlassian.net/browse/MM-34614
> MM-34614 Prevent command box from grabbing focus when already opened.

- client/incident.go
- plugin.json
- server/api/incidents.go
- server/api/incidents_test.go
- server/api/playbooks.go
- server/api/playbooks_test.go
- server/command/command.go
- server/config/configuration.go
- server/permissions/permissions.go
- server/plugin.go
- webapp/src/actions.ts
- webapp/src/components/assets/icons/channel_header_button.tsx
- webapp/src/index.tsx
- webapp/src/make_update_main_menu.ts
- webapp/src/reducer.test.ts
- webapp/src/reducer.ts
- webapp/src/rhs_opener.ts
- webapp/src/selectors.ts
- webapp/src/system_console_enabled_teams.tsx
- webapp/src/types/actions.ts
- webapp/src/types/incident.ts
Adds a system console setting to limit which teams the plugin is enabled on.
- When you are on a non-enabled team the main menu item and header icon disappear.
- The API only restricts creating incidents and playbooks. Reads and incident modifications are still possible. However listing incidents is not.
- All slash commands are disabled on teams for which the plugin is disabled. However the autocomplete will still suggest them.
https://mattermost.atlassian.net/browse/MM-34479
> MM-34479 System console setting for which teams plugin is enabled on.

- server/incident/service.go
- tests-e2e/cypress/integration/frontstage/incident_broadcast_spec.js
- tests-e2e/cypress/support/plugin_ui_commands.js
- tests-e2e/cypress/support/ui_commands.js
We were using the previous status when broadcasting a status update. Which was obviously wrong.
I also adapted the specific E2E test, which was not changing the status itself, so the important part was left unchecked.
https://mattermost.atlassian.net/browse/MM-34772
> MM-34772: Fix broadcast status update

- tests-e2e/cypress/integration/backstage/backstage_spec.js
- tests-e2e/cypress/integration/backstage/incident_list_spec.js
- tests-e2e/cypress/integration/backstage/playbook_creation_spec.js
- tests-e2e/cypress/integration/backstage/playbook_list_spec.js
- webapp/src/components/backstage/backstage.tsx
- webapp/src/make_update_main_menu.ts
We're planning on putting the stats page behind an experimental feature flag, but no time for that in v1.9, so just effectively hide navigation to it for now.
None.
> Temporarily hide the /stats page

- webapp/src/components/backstage/incidents/incident_backstage/incident_backstage.tsx
- Fixed the background rendering (good eye!)
- Discovered that the playbook edit screen is doing something very cool: the navbar (with the save and back buttons) scrolls then sticks to the top, hiding the Incident/Playbooks/Settings, like so:
- So changing the Incidents page to do the same:
- https://mattermost.atlassian.net/browse/MM-35291
> MM-35291 - Fix incident backstage rendering

- webapp/src/components/backstage/incidents/incident_backstage/overview/participants.tsx
- Don't show the channel members section if there are no other participants
Looks like:
- https://mattermost.atlassian.net/browse/MM-35293
> MM-35293 - Fix for empty channel members header

- LICENSE
Removed specific references to E20 so the tool can be used for limited purposes in other versions of the software.
> Update license to allow for extended usage

- server/api/incidents.go
- server/api/incidents_test.go
- server/command/command.go
- server/incident/incident.go
- server/incident/mocks/mock_service.go
- server/incident/service.go
- server/incident/service_test.go
- server/sqlstore/incident.go
- server/sqlstore/incident_test.go
- We don't ask for the description when starting an incident, it is inherited from the playbook. So:
- Don't put the description in the new incident broadcast message
- Don't put the description in the channel header
- https://mattermost.atlassian.net/browse/MM-35296
> MM-35296 - Fix description bugs

- server/api/incidents.go
- server/incident/incident.go
- server/incident/mocks/mock_service.go
- server/incident/service.go
- server/sqlstore/incident.go
- server/sqlstore/migrations.go
- server/telemetry/noop.go
- server/telemetry/rudder.go
- tests-e2e/cypress/integration/frontstage/rhs/welcome_spec.js
- webapp/src/client.ts
- webapp/src/components/assets/buttons.tsx
- webapp/src/components/backstage/incidents/incident_backstage/incident_backstage.tsx
- webapp/src/components/backstage/incidents/incident_backstage/retrospective/followups.tsx
- webapp/src/components/backstage/incidents/incident_backstage/retrospective/learnings.tsx
- webapp/src/components/backstage/incidents/incident_backstage/retrospective/profile_vertical.tsx
- webapp/src/components/backstage/incidents/incident_backstage/retrospective/report.tsx
- webapp/src/components/backstage/incidents/incident_backstage/retrospective/retrospective.tsx
- webapp/src/components/backstage/incidents/incident_backstage/retrospective/timeline.tsx
- webapp/src/components/backstage/incidents/incident_backstage/retrospective/timeline_retro.tsx
- webapp/src/components/rhs/rhs_welcome_view.tsx
- webapp/src/types/incident.ts
Infrastructure for the backstage retrospective tab. This is all behind the experimental features flag for now. All this is is the tab and and editable field in the backstage. Pressing the save button will save a "draft" that you can't do anything with for now. 
Thanks to @cpoile for the client framework and timeline which is the basis for this PR. 
FYI and feedback appreciated @itao @abhijit-singh 
- **Placeholder Elements**
- **Basic saving of retrospective** <-- We are here
- Ability to publish retrospective
- Reminder to fill out retrospective
- Templating retrospective report
- Configurable persistant reminders
- Polish
https://mattermost.atlassian.net/browse/MM-35041
https://mattermost.atlassian.net/browse/MM-35042
> MM-35041 MM-35042 Basic retrospective tab and infrastructure

- webapp/src/components/backstage/step_edit.tsx
- Just pressing back doesn't prompt me for a save, so I'm not exactly sure what the customer is referring to.
- But maybe they meant: clicking a step title/command/description text box, and then clicking out (without making any changes) causes the prompt for save. Which I /can/ reproduce. So I'm fixing that. 
- Clicking on textareas (all the other larger inputs) and clicking back does not prompt for a save, so no need to change those.
- https://mattermost.atlassian.net/browse/MM-35496
> MM-35496 - Playbook prompts for save despite no changes

- server/api/api.go
- server/api/api_test.go
- server/api/error_handler.go
- server/api/incidents.go
- server/api/incidents_test.go
- server/api/playbooks.go
- server/api/playbooks_test.go
- server/api/stats.go
- server/plugin.go
- the endpoint needed something to send back, because it was a `doPost` -> `doFetchWithResponse` call on the client.
- while investigating, found that the errors logged through logrus are not great--they don't conform to the way the server logs errors, and so they aren't coded correctly. The second commit fixes that.
- https://mattermost.atlassian.net/browse/MM-35600
[x] Unit tests updated
> MM-35600 - Fix JS error on change commander

- LICENSE
- README.md
- server/command/command.go
This PR is for simplifying two date arguments in `/incident test bulk-data` into one number argument. Instead of `/incident test bulk-data 10 3 2020-01-31 2020-11-22 2`, now it's `/incident test bulk-data 10 3 342 2`. And the number of days is expected to be larger than 0.
Fixes https://github.com/mattermost/mattermost-server/issues/17468
> MM-17468: Accept a number of days instead of two date arguments in `/incident test bulk-data`

- webapp/src/components/backstage/backstage.tsx
- webapp/src/components/backstage/playbook_edit.tsx
- webapp/src/components/backstage/route_leaving_guard.tsx
- Using react router's prompt (it's amazing)
- No need for manual confirmation dialog (but it's not as pretty)
Looks like:
- https://mattermost.atlassian.net/browse/MM-35605
[ ] ~~Unit tests updated~~
> MM-35605 - Fix for Playbooks can be closed without changes getting saved

- server/api/incidents.go
- server/api/incidents_test.go
- server/api/telemetry.go
- server/bot/bot.go
- server/bot/poster.go
- server/plugin.go
- server/telemetry/noop.go
- server/telemetry/rudder.go
- webapp/src/client.ts
- webapp/src/components/backstage/upgrade_modal.tsx
- webapp/src/components/rhs/rhs_timeline_placeholder.tsx
- webapp/src/constants.ts
Add telemetry for the pricing differentiation features: when the admins click on Start Trial or the end users click on Notify System Admin.
While I was here, I moved the `/telemetry` API endpoints that were inside the Incident router to a generic telemetry subrouter.
https://mattermost.atlassian.net/browse/MM-35889
> MM-35889: Add telemetry for upgrade features

- server/bot/poster.go
Found this bug while working on something else. This should be cherry-picked to v1.11.1.
The problem was that the string had a typo, so the case never ran, and the message never got populated.
https://mattermost.atlassian.net/browse/MM-36042
> MM-36042: Fix admin notification on playbook restriction

- tests-e2e/cypress/integration/backstage/playbook_details_spec.js
- webapp/src/components/backstage/channel_selector.tsx
The channel selector did not respond to Redux changes to the available channels. While this is rarely a problem in normal usage, when the set of channels aren't likely to change in the backstage, it did cause issues during e2e tests when the selector raced with the messaging application's initial load of available channels.
Switch from `AsyncSelect` to just a controlled `Select` component that directly renders from the selected channels. While we're in here, exclude DMs and GMs from the list of selectable channels.
None
[ ] ~~Unit tests updated~~
> Fix channel selector selector

- server/api/incidents.go
- server/playbook/playbook.go
- server/sqlstore/migrations.go
- server/sqlstore/playbook.go
- webapp/src/components/backstage/playbook_edit.tsx
- webapp/src/types/playbook.ts
Adds the ability to template the retrospective report.
Built on top of https://github.com/mattermost/mattermost-plugin-incident-collaboration/pull/566
- **Placeholder Elements**
- **Basic saving of retrospective** 
- **Ability to publish retrospective** 
- **Reminder to fill out retrospective**
- **Configurable persistent reminders** 
- **Templating retrospective report** <-- We are here
- _NEW:_ Replace reminder message with custom message for interactivity.
- _NEW:_ Add ability to disable retrospectives at playbook level.
- Polish
https://mattermost.atlassian.net/browse/MM-35045
> MM-35045 Template retrospective report

- .golangci.yml
Disable `unusedwrite` in GolangCI:
N/A
> golangci: disable unusedwrite

- webapp/src/components/backstage/backstage.tsx
- webapp/src/components/backstage/incidents/incident_backstage/incident_backstage.tsx
- webapp/src/components/backstage/incidents/incident_backstage/retrospective/report.tsx
- webapp/src/components/backstage/incidents/shared.tsx
Modifies the styling on the retrospective report page to always show as much of the retrospective as possible. 
https://mattermost.atlassian.net/browse/MM-36263
> MM-36263 Fix to show as much of retrospective as possible.

- webapp/src/components/backstage/playbook_edit.tsx
- set changesMade = false after saving so that discard dialog isn't triggered by react router
- https://mattermost.atlassian.net/browse/MM-36349
> MM-36349 - Save playbook triggers "discard changes" dialog

- server/plugin.go
- server/sqlstore/stats.go
- This was weird. MySql's sum returns an int (but not always). Then, squirrel interpreted it as a `[]uint8` (!?). This fixcasts it to something we expect.
- Changing the type check to fail and give us some info, in case this happens again
- Remember that nil dereference we got from community a few days ago? Turns out it was because we were using an uninitialized bot to report errors. Fixed that.
- I think I should write tests for the time-related stats, but these pages are changing so fast I don't think it's worth the time -- propose we wait till the features are a little more stable.
- https://mattermost.atlassian.net/browse/MM-36359
> MM-36359 - Fix backstage stats not working on MySql

- client/playbook.go
- server/api/api.yaml
- server/api/playbooks.go
- server/api/playbooks_test.go
- server/command/command.go
- server/playbook/playbook.go
- server/sqlstore/playbook_test.go
- webapp/src/client.ts
- webapp/src/types/incident.ts
The `member_only` parameter on the playbooks endpoint is unused. Remove it to simplify subsequent changes.
None.
> Removed unused member_only

- webapp/src/hooks.ts
Skip trying to build the openCloudModal function when not in Cloud, returning a void function. This gets rid of the error emitted on self-managed installations that have an older webapp.
https://mattermost.atlassian.net/browse/MM-36474
> MM-36474: Skip useOpenCloudModal creation if not in cloud

- go.mod
- go.sum
This is just to get the latest changes for license checks: https://github.com/mattermost/mattermost-plugin-api/pull/91
--
> Bump mattermost-plugin-api version

- server/api/telemetry.go
- server/bot/bot.go
- server/bot/poster.go
- server/telemetry/noop.go
- server/telemetry/rudder.go
- webapp/src/components/backstage/playbook_runs/playbook_run_details/export_link.tsx
- webapp/src/components/backstage/upgrade_modal_data.tsx
- webapp/src/constants.ts
- webapp/src/hooks.ts
- webapp/src/selectors.ts
This PR modifies the Export channel button in the run details screen to match the UI/UX of all other restricted features.
The button is no longer disabled when the server is not properly licensed, but the usual green key icon is shown:
When clicking on it, we get the usual upgrade modal:
| System Admin 	| End user 	|
|-	|-	|
| ![image](https://user-images.githubusercontent.com/3924815/123703737-1759f500-d865-11eb-884f-42d2035593e4.png) 	| ![image](https://user-images.githubusercontent.com/3924815/123703748-1a54e580-d865-11eb-8ba0-f9b1da2c8186.png) 	|
And clicking on Notify Admin sends the usual message to the System Admins:
| Self-managed 	| Cloud 	|
|-	|-	|
| ![image](https://user-images.githubusercontent.com/3924815/123703782-23de4d80-d865-11eb-9816-ea2e314fe21b.png) 	| …
> MM-36689: Match export channel UX to all other restricted features

- plugin.json
This is a follow-up to @agnivade's changes to use the plugin-api for managing the DB connection pool instead of just hard-coding two. Once deployed, the plugin will only be live on `-daily` until `community` is upgraded on July 16th. Marketplace users will not be prompted to upgrade until they are running at least v5.37.
None.
> Require mattermost-server 5.37

- client/client.go
- client/settings.go
- server/api/api.go
- server/api/settings.go
- server/api/settings_test.go
- server/app/permissions.go
- server/plugin.go
- webapp/src/client.ts
- webapp/src/components/backstage/settings.tsx
- webapp/src/components/backstage/styles.tsx
- webapp/src/hooks.ts
Always allow system administrators to configure who can create playbooks. I took the liberty of refactoring the settings handler and extending the client API accordingly. (Feel free to review by commit!)
As the admin user `test`, I can still configure this:
As the non-admin user `test2`, I can't:
When there are no restrictions, the non-admin user `test2` can't (but `test` can!):
None.
> Adminify settings

- webapp/src/components/retrospective_reminder_posts.tsx
The `type` property of new posts sent to the channel is undefined, resulting in a crash when looking for the latest reminder post, which assumes this field is a string when calling its `startsWith` method.
This simply makes sure that we don't access that property when undefined, assuming it's not a reminder post (as it's a post manually posted by the user).
Why the new posts have no `type` set is still an unknown to me. Old posts that are loaded when entering the channel do have `type` defined as an empty string.
https://mattermost.atlassian.net/browse/MM-36748
> MM-36748: Add optional chaining to prevent undefined error

- server/sqlstore/stats.go
- webapp/src/components/assets/icons/clear_icon.tsx
- webapp/src/components/backstage/playbooks/bar_graph.tsx
- webapp/src/components/backstage/playbooks/line_graph.tsx
- webapp/src/components/backstage/playbooks/playbook_backstage.tsx
- webapp/src/components/backstage/playbooks/playbook_run_list/playbook_run_list.tsx
- webapp/src/components/backstage/playbooks/stats_view.tsx
- webapp/src/components/widgets/pill.tsx
- Can review based on commit
- When clicking on the graph, add a pill to indicate that the runs list is being filtered
- Cursor changed to pointer (only on graphs that are clickable)
- Weeks start on Sunday for stats, and end a millisecond before midnight on the last day of the range. Hopefully this will fix the wonky graphs on community.
- Only show whole numbers on the y axis for the line graphs
- Designs: (see the topleftmost design) https://www.figma.com/file/vhVlHvJVNTxW6g9PLLnzI0/Playbook-Details?node-id=2%3A3949
E.g., after clicking on the `Total Runs` graph:
E.g., after clicking on the `Active Runs` graph:
- https://mattermost.atlassian.net/browse/MM-36540
> MM-36540 - Improve graph searching & polish

- server/app/permissions.go
This PR makes playbook editing possible for all servers, regardless of the license they have.
If a server has more than one playbook in a team and downgrades to the Starter plan, they will still be able to edit and use all the playbooks they had, but I believe that's a good thing. @itao, thoughts?
https://mattermost.atlassian.net/browse/MM-36768
> MM-36768: Allow playbook editing regardless of the license

- webapp/src/hooks.ts
Change `useProfilesInChannel` to only try getting the profiles in the channel once (or, at least as long as the given `channelId` never changes). Previously, the `profilesInChannel` selector would /always/ result in a new value, triggering the effect hook indefinitely.
Relates-to: https://mattermost.atlassian.net/browse/MM-36876
https://mattermost.atlassian.net/browse/MM-36876
> MM-36876: useProfilesInChannel should try once

- webapp/src/components/checklist_item_input.tsx
When editing a playbook, the unconditional `autoFocus=true` on the last visible description forced the page to scroll to that element. Only do this is the description is empty, making it easy to start typing a description when adding one but not scrolling when first loading.
None.
> stop random scroll on edit playbook

- tests-e2e/cypress/support/index.js
`user-2` as a username doesn't actually exist -- its `samuel.tucker` in the test data -- and we weren't correctly initializing preferences for the welcome modal for this users, used in a few tests. I presume the failure itself was upstream from incoming changes around the welcome modal.
None.
> properly initialize fixture users

- tests-e2e/cypress/support/plugin_ui_commands.js
- tests-e2e/cypress/support/ui_commands.js
- webapp/src/components/backstage/backstage.tsx
- webapp/src/components/backstage/backstage_navbar.tsx
- webapp/src/components/backstage/playbook_edit.tsx
Make the playbook navbar sticky. It was technically already sticky, but had a `top: 0px` that prevented it from staying below the sticky header. This makes `Save` front and centre, instead of `X`; it also helps fix a few Cypress unit tests with the (yet to be merged) upgraded Cypress 7.
None.
> make playbook navbar sticky

- server/api/telemetry.go
- server/app/playbook.go
- server/sqlstore/playbook.go
- server/sqlstore/playbook_test.go
- server/telemetry/noop.go
- server/telemetry/rudder.go
- tests-e2e/cypress/integration/backstage/playbook_creation_spec.js
- webapp/src/client.ts
- webapp/src/components/backstage/playbook_list.tsx
- webapp/src/components/backstage/template_selector.tsx
- webapp/src/components/rhs/rhs_home.tsx
As per @itao's [proposal](https://docs.google.com/document/d/1pJscJCqiL3CDemsBN-V_3NRvOeapB3nbjE7eEKTwmGY/edit), replace the existing templates:
* Blank (unchanged)
* Product Release
* Customer Onboarding
* Service Reliability Incident (refreshed)
* Feature Swimlane (basically empty)
The existing template selector scrolls on demand, but to give a slightly better experience on a typical MacBook Pro, I reduced the required margin to avoid scrolling in this case:
On smaller screens, scrolling still works:
And @calebroseland's updated RHS works beautifully with the new templates (though it seems like `num_actions` is hard-coded at the moment to `0`).
Telemetry is updated to track clicks on the template icons in the backstage, as well as the `Use template` option in the new RHS experience. …
> Updated playbook templates

- webapp/src/actions.ts
- webapp/src/components/dot_menu.tsx
- webapp/src/components/multi_checkbox.tsx
- webapp/src/components/rhs/rhs_checklists.tsx
- webapp/src/reducer.ts
- webapp/src/selectors.ts
- webapp/src/types/actions.ts
- webapp/src/types/playbook.ts
- Adds a filter to the checklist task list. Works as described in the figma and in the thread: https://community-daily.mattermost.com/core/pl/4y149srtu7bm3jp5gg1wjzuzhr
- State is saved per user per channel (until webapp refresh)
- The bottom group must always have one option selected, so the user cannot uncheck the last value in the bottom group.
Looks like:
- https://mattermost.atlassian.net/browse/MM-36913
- https://mattermost.atlassian.net/browse/MM-36914 (state saved per user)
> MM-36913 - Filter tasks w/ default (state saved per user)

- client/playbook_run.go
- client/playbook_runs.go
- server/api/playbook_runs.go
- server/api/playbook_runs_test.go
- server/app/mocks/mock_playbook_run_service.go
- server/app/playbook_run.go
- server/app/playbook_run_service.go
- server/app/playbook_run_service_test.go
- server/app/reminder.go
- tests-e2e/cypress/integration/frontstage/rhs/latest_update_spec.js
- tests-e2e/cypress/support/ui_commands.js
- webapp/src/actions.ts
- webapp/src/client.ts
- webapp/src/components/assets/icons/clock.tsx
- webapp/src/components/assets/icons/exclamation.tsx
- webapp/src/components/rhs/rhs_about.tsx
- webapp/src/components/rhs/rhs_about_description.tsx
- webapp/src/components/rhs/rhs_about_title.tsx
- webapp/src/hooks/general.ts
- webapp/src/reducer.ts
- webapp/src/selectors.ts
- webapp/src/types/actions.ts
This PR makes both the title and the description editable inline. It also removes the Description field from the interactive dialog, making the inline edition the only way to change the description.
https://user-images.githubusercontent.com/3924815/127485888-f2872e2b-5982-4071-9bef-8278045123ce.mp4
When editing the title, hitting `Enter` closes the edition and saves the new title. For the description, I chose `Ctrl+Enter` for that. Both the title and description are automatically saved whenever the user clicks outside of the input area.
As you can see in the video and in the code, changing the run name is actually a channel name change. It was the most straightforward way to do it given the time constraints.
This branch is based off of #656, I'll change it to master as soon as that one's …
> MM-37326: Inline editing

- webapp/src/components/rhs/rhs_about_description.tsx
This PR prevents entering the edit mode in the RHS description when the user clicks on a link (or a user mention or a channel link).
https://user-images.githubusercontent.com/3924815/127852459-e8759b58-89cc-4715-bcf0-4a7f415ab267.mp4
https://mattermost.atlassian.net/browse/MM-37529
> MM-37529: Fix clicking on links in the description

- webapp/src/components/rhs/rhs_about_description.tsx
This adds the `white-space: pre-wrap` style to the rendered description, as done in [the `post` class in webapp](https://github.com/mattermost/mattermost-webapp/blob/master/sass/components/_post.scss#L1076) to effectively render new lines in the source text as new lines.
https://user-images.githubusercontent.com/3924815/127861317-07fa9874-d5a7-425e-bf4d-ec817cdfb99c.mp4
https://mattermost.atlassian.net/browse/MM-37526
> MM-37526: Render newlines in the description text

- webapp/src/components/rhs/rhs_about.tsx
The computation of the width in the owner section did not take into account the added border in the participants component, so it was resized when hovering over the participants. 
https://user-images.githubusercontent.com/3924815/128148846-07ef4659-733c-4e9b-9895-21246d37bde6.mp4
https://user-images.githubusercontent.com/3924815/128148842-a44ad11d-7db9-4fe2-93cf-b4a5389704ed.mp4
https://mattermost.atlassian.net/browse/MM-37519
> MM-37519: Make the owner section slightly narrower

- webapp/src/components/rhs/rhs_about_title.tsx
This PR polishes the title editing experience: the title can no longer become empty (an error is shown if the name has less than two characters, and the user cannot save it, only discard the changes) and hitting `Esc` discards the changes and disables the edit mode.
https://user-images.githubusercontent.com/3924815/128179238-2d3d01e5-c5a7-4dcc-b98f-a2bde2e272f7.mp4
https://mattermost.atlassian.net/browse/MM-37569
> MM-37569: Prevent empty title and use Esc to discard changes

- webapp/src/components/rhs/rhs_about_description.tsx
#667 fixed the spacing of new lines in paragraphs, but broke it in lists. It turns out I had to isolate the `white-space` only to `p` elements.
| BEFORE 	| AFTER 	|
|---	|---	|
| ![image](https://user-images.githubusercontent.com/3924815/128144935-1af7ab56-38c1-4719-85ac-d48d8968c5d3.png) 	| ![image](https://user-images.githubusercontent.com/3924815/128144666-761df579-d13c-498a-a13b-7178b7a0a5ff.png) 	|
https://mattermost.atlassian.net/browse/MM-37526
> MM-37526: Fix the newline render fix

- webapp/src/components/rhs/rhs_home.tsx
Use proper theme var
Broken
Fixed
https://mattermost.atlassian.net/browse/MM-37592
> MM-37592: fix rhs_home theme color

- webapp/src/components/rhs/rhs_about_description.tsx
Re-use the same CSS in both the rendered description and the editable textarea to simplify the code. The fix for the layout movement is just the `display: block` line, as `textarea` elements are `display: inline-block` by default, and the change between those two `display` values was creating that slight vertical movement.
Tested on Firefox and Chromium.
https://user-images.githubusercontent.com/3924815/128687904-ff3e1e26-b75b-45ff-afac-a21b61da6f14.mp4
https://mattermost.atlassian.net/browse/MM-37698
> MM-37698: Simplify CSS and fix layout movement

- server/app/playbook.go
- server/app/playbook_run.go
- server/app/playbook_run_service.go
- server/sqlstore/playbook_run_test.go
- server/telemetry/rudder.go
- server/telemetry/rudder_test.go
This was meant to come with the long-awaited API docs rework, but as documenting the public structs is something we'll need to do sooner or later, and there are customers asking for documentation on the webhooks payload, I started simply documenting the structs, so @justinegeffen can point directly to the code in the documentation, while the rework finally comes.
I'm open to how to document some of the fields such as ID (maybe not document them at all?).
--
> Recursively document PlaybookRunWebhookPayload

- webapp/src/components/backstage/backstage.tsx
Compensate for the 40px consumed by the backstage header, allowing the full content on the backstage to be displayed. Previously, page navigation controls rendered outside the viewport and could not be reached.
Fixes: https://mattermost.atlassian.net/browse/MM-37893
> MM-37893: calc global header height in backstage

- tests-e2e/cypress/integration/frontstage/channel_header_spec.js
- webapp/src/components/channel_header.tsx
- webapp/src/index.tsx
Show "Run Playbook" when outside a playbook run channel, and "View Run Details" when inside. Depends on https://github.com/mattermost/mattermost-webapp/pull/8617 before the e2e tests will pass.
Fixes: https://mattermost.atlassian.net/browse/MM-37542
> MM-37542: Support dynamic channel header tooltip

- .circleci/config.yml
Using es7 for pipeline because we no longer support es 5 & 6
https://mattermost.atlassian.net/browse/MM-36445
https://github.com/mattermost/enterprise/pull/1020
- [NA] Telemetry updated
- [NA] Gated by experimental feature flag
- [NA] Unit tests updated
> [MM-36445] Changing elastic search docker version

- server/sqlstore/playbook_run.go
```
{"timestamp":"2021-08-19 15:56:04.915 Z","level":"warn","msg":"public error message: An internal error has occurred. Check app server logs for details.; internal details: can't get playbook runs from the store: failed to query for playbook runs: sql: Scan error on column index 31, name \"CategoryName\": converting NULL to string is unsupported","caller":"app/plugin_api.go:901","plugin_id":"com.mattermost.plugin-incident-management"}
```
N/A
> COALESCE(CategoryName)

- .golangci.yml
- Makefile
- server/app/permissions.go
- server/app/playbook_run_service.go
- server/bot/poster.go
Update our `.golangci.yml` to avoid the warnings currently being emitted (and fix an improvement from the upgraded linters while we're at it):
None.
> Remove deprecated linters

- tests-e2e/cypress/integration/backstage/playbook_list_permissions_spec.js
- These e2e tests test the different permutations of the new playbook run permissions (#708).
- https://mattermost.atlassian.net/browse/MM-38136
> MM-3775 - e2e tests for new runs permissions system

- webapp/src/client.ts
- webapp/src/index.tsx
Our own `client` needed to be aware of a potential subpath, but more insidiously, so did /our version/ of the `Client4` API, since we import ours from `mattermost-redux` and the webapp no longer initializes /that one/ with the requisite SiteURL for subpath awareness.
@hmhealey, including you here largely for visibility as this is one of those "mattermost-redux" things we'll ideally sort out soon.
Fixes: https://mattermost.atlassian.net/browse/MM-38129
> Configure client/client4 for subpaths.

- server/sqlstore/migrations.go
- server/sqlstore/migrations_utils.go
- server/sqlstore/playbook.go
- server/sqlstore/playbook_test.go
- server/sqlstore/store_test.go
- server/sqlstore/support_for_test.go
Adds missing primary keys to IR_PlaybookMember, IR_StatusPosts, IR_TimelineEvent, IR_ViewedChannel
Esentally does:
```sql
ALTER TABLE IR_PlaybookMember ADD PRIMARY KEY (MemberID, PlaybookID);
ALTER TABLE IR_StatusPosts ADD PRIMARY KEY (IncidentID, PostID);
ALTER TABLE IR_TimelineEvent ADD PRIMARY KEY (ID);
ALTER TABLE IR_ViewedChannel ADD PRIMARY KEY (ChannelID, UserID);
```
with more steps.
Added a test so we don't make this mistake again.
http://mattermost.atlassian.net/browse/MM-38188
> MM-38188 Adding missing primary keys

- tests-e2e/cypress/integration/frontstage/channel_header_spec.js
- webapp/src/components/channel_header.tsx
Renaming channel header button.
If a channel is a run then: `Toggle Run Details`
If a channel is not a run then: `Toggle Playbook List`
> Rename channel header button

- webapp/src/components/backstage/playbooks/playbook_backstage.tsx
- webapp/src/types/playbook.ts
Users can still Run deleted playbooks by going to previous playbook runs and clicking on the playbook. This PR aims to fix this by hiding away the Run button if the playbook is already deleted.
See [issue](https://mattermost.atlassian.net/browse/MM-37191) description for more details.
Fixes: mattermost/mattermost-server/issues/18036
JIRA: https://mattermost.atlassian.net/browse/MM-37191
> Mm 37191 omit run deleted

- webapp/src/components/backstage/styles.tsx
- Now looks like:
- https://mattermost.atlassian.net/browse/MM-38058
> MM-38058 - Fix for: Playbook run's backstage button theme is incorrect

- webapp/src/components/rhs/rhs_title.tsx
- Add a conditional for when the RHSTitleText is clickable (instead of a brand new styled component)
- https://mattermost.atlassian.net/browse/MM-37513
> MM-37513 - Fix for: RHS title is styled the same way in both RHS Home and RHS Details

- webapp/src/components/backstage/playbook.scss
- webapp/src/components/backstage/playbook_list_row.tsx
- Fixed three-dot alignment inside
- Also adjusted the three-dot horizontal alignment in the list to look nicer
- https://mattermost.atlassian.net/browse/MM-37545
> MM-37545 - Fix for: Backstage actions icon misaligned

- webapp/src/components/backstage/playbook_runs/playbook_run_backstage/retrospective/timeline.tsx
- Fixed the blank timeline visible line bug
- Added a notice -- same as in the Runs list, and using the same language
- https://mattermost.atlassian.net/browse/MM-36267
> MM-36267 - Fix for: Tiny straight line in empty timeline in dark theme

- webapp/src/components/backstage/automation/input_keywords.tsx
- Fix theming. Followed tertiary buttons and matched to the theming of the `x members` pill in the `Invite Members` selector below it.
- Denim:
on highlighting the remove for the last item:
- Indigo:
- https://mattermost.atlassian.net/browse/MM-38453
> MM-38453 - Fix for: Text theming incorrect for actions->keyword input

- server/sqlstore/migrations_utils.go
- server/sqlstore/store_test.go
Fixes the primary key test. 
The test was not incorrect. The addPrimaryKey migration's check for migration complete did not restrict itself to the selected DB. As a result it would not run if the migration had already been run on anouther DB. This fixes that error.
> Fixing primary key test

- webapp/src/components/backstage/automation/message_on_join.tsx
- webapp/src/components/backstage/playbook_edit.tsx
- webapp/src/components/backstage/styles.tsx
- webapp/src/components/checklist_item.tsx
- webapp/src/components/command_input.tsx
- webapp/src/components/markdown_textbox.tsx
- [MM-38295](https://mattermost.atlassian.net/browse/MM-38295): Adds markdown preview to template textareas in backstage `playbook_edit` by switching to `markdown_textarea`.
- Description tempate
- Status template
- Retro template
> MM-38295: markdown inputs in playbook-edit

- go.mod
Update to depend on `client/v0.6.0` (the tip of `master`) so that the repository names match up.
N/A
> require client/v0.6.0, fixing repository name

- client/client.go
- plugin.json
- server/api/api.yaml
- server/api/playbook_runs_test.go
- server/api/playbooks_test.go
- server/api/settings_test.go
- server/app/playbook_run_service_test.go
- server/command/command.go
- server/plugin.go
- server/sqlstore/migrations.go
- server/sqlstore/store_test.go
- server/sqlstore/support_for_test.go
- tests-e2e/cypress/integration/backstage/backstage_spec.js
- tests-e2e/cypress/integration/backstage/playbook_creation_spec.js
- tests-e2e/cypress/support/api/cloud_default_config.json
- tests-e2e/cypress/support/api/on_prem_default_config.json
- tests-e2e/cypress/support/api/plugin.js
- tests-e2e/cypress/support/plugin/api_commands.js
- tests-e2e/db-setup/mm534.sql
- webapp/webpack.config.js
Updates the plugin id to `playbooks`.
Adds migration to kill off the old version of itself just like last time.
Server PR: https://github.com/mattermost/mattermost-server/pull/18392
https://mattermost.atlassian.net/browse/MM-38122
> MM-38122 Update plugin ID

- README.md
- server/api/api.yaml
- server/app/playbook_run.go
- server/sqlstore/playbook_run.go
- tests-e2e/cypress/integration/frontstage/rhs/open_spec.js
- tests-e2e/cypress/integration/frontstage/slash_command/info_spec.js
- tests-e2e/cypress/integration/frontstage/slash_command/owner_spec.js
- tests-e2e/cypress/support/plugin/api_commands.js
- webapp/src/client.ts
- webapp/src/reducer.ts
- webapp/src/rhs_opener.ts
Signed-off-by: Paul Rothrock <paul@movetoiceland.com>
Replaced all instances of "an playbook" with "a playbook" in strings and comments
> Removed all instances of 'an playbook'

- tests-e2e/cypress/integration/backstage/playbook_run_details_spec.js
- tests-e2e/cypress/support/plugin/api_commands.js
- webapp/src/components/backstage/playbook_runs/playbook_run_backstage/overview/updates.tsx
- webapp/src/components/rhs/post_card.tsx
Ensure status updates from non-participants (i.e. typically the `playbook` bot) are loaded when displaying playbook run details.
Fixes: https://mattermost.atlassian.net/browse/MM-38443
> MM-38443: ensure status post profiles loaded

- server/sqlstore/migrations.go
Migration of KV store is not as easy as I initially anticipated because we actually use the KV store before we use the DB. So there will be a duplicate entry for the bot ID in the KV store which breaks the simple query. 
The modifications here ignore duplicate entries which of course is different between MySQL and PostgreSQL. I also changed the migration to be best effort to not block the plugin from starting if there is a problem.
> Fixing kvstore migration.

- webapp/src/components/profile/profile_selector.scss
- webapp/src/components/profile/profile_selector.tsx
- removed scss, replaced with styled component logic. 
- instead of `right: 0` use `right: -55` -- this will fit the largest possible profile selector width
- See the ticket for what it used to look like (or try it out in a channel, eg: https://community-release.mattermost.com/private-core/channels/playbooks-plugin-and-others-broken-on-daily )
- https://mattermost.atlassian.net/browse/MM-37703
-
> MM-37703 - Fix for: Task assignee dropdown is cut off by center channel

- server/api/api.yaml
- server/api/playbook_runs.go
- server/app/playbook_run.go
- server/sqlstore/migrations.go
- server/sqlstore/playbook_run.go
- tests-e2e/.eslintrc
- tests-e2e/cypress/integration/frontstage/rhs/status_update_spec.js
- webapp/src/actions.ts
- webapp/src/components/backstage/playbook_edit.tsx
- webapp/src/components/modals/update_run_status_modal.tsx
- webapp/src/types/playbook.ts
- webapp/src/types/playbook_run.ts
The bug (see the ticket) was caused by `playbook` being undefined: the request to fetch it failed because the user does not have permissions to open the playbook, so it was not set.
This affected the line below, in the call to `GenericModal`. The value of the `isConfirmDisabled` field was set to false because playbook was undefined.
```ts
isConfirmDisabled={!(hasPermission && message?.trim() && currentUserId && channelId && playbook?.team_id)}
```
This PR completely removes the dependency on the playbook in the Update Status modal: everything should be in the playbook run, as we cannot rely on the current information of a playbook, which has potentially been changed between the run creation and the time we fetch that information.
For doing that, I had to add the …
> MM-38775: Remove dependency on playbook in Update Status modal

- webapp/src/components/backstage/upgrade_modal.tsx
- webapp/src/components/widgets/generic_modal.tsx
#699 changed the styling of the GenericModal footer. This PR changes it back for the upgrade modal, maintaining the checklist item edit modal and the post update modal with the buttons at the right.
I exposed the inner components of GenericModal so callers can define their own styles for each piece. Right now I'm only exposing `FooterContainer` to minimize risks, but I think it's a good way of giving flexibility to generic components.
https://mattermost.atlassian.net/browse/MM-38722
> MM-38722: Fix UpgradeModal misalignment by exposing inner components in GenericModal

- webapp/src/components/backstage/playbook_runs/playbook_run_backstage/retrospective/timeline_event_item.tsx
- webapp/src/components/backstage/playbook_runs/playbook_run_backstage/retrospective/timeline_retro.tsx
- webapp/src/types/rhs.ts
- webapp/src/webapp_globals.ts
- [MM-38569](https://mattermost.atlassian.net/browse/MM-38569)
- Prevent clicks on deleted status posts
- Indicate deleted status posts with strikethrough and timestamp
> MM-38569: Fix timeline permalinks for deleted status posts

- tests-e2e/cypress/integration/frontstage/rhs/open_spec.js
- webapp/src/components/assets/buttons.tsx
- webapp/src/components/checklist_item.tsx
- webapp/src/components/checklist_item_input.tsx
- webapp/src/components/rhs/collapsible_checklist.tsx
- webapp/src/components/rhs/rhs_about.tsx
- webapp/src/components/rhs/rhs_about_title.tsx
- webapp/src/components/rhs/rhs_checklists.tsx
- webapp/src/components/rhs/rhs_post_update.tsx
- webapp/src/components/rhs/rhs_post_update_button.tsx
- webapp/src/rhs_opener.ts
Improved finish semantics:
* Add a Finished tag next to the run name. 
* Disable the Post update button. 
* Change the icon in the update box to a chequered flag 
* Change text to Run finished X minutes/hours/days ago. 
* Disable the checkbox for all the tasks (checked and unchecked)
* Remove/disable options to Add task, reorder tasks, add/edit assignee, edit task, delete task. 
* Hide the ability to “Run” any associated slash command
* Don't open the RHS by default for finished runs
https://mattermost.atlassian.net/browse/MM-37699
> MM-37699: improved finished run semantics

- server/app/playbook_run_service.go
- Don't stop broadcasting. Incidentally, this is how the broadcast start and finish messages are treated (which is why those seemed to keep working).
- Making a judgement call that it's not worth mocking unit tests to simulate this, and e2e tests would not be a valuable use of time given the amount of other bugs we need to finish and the edge-case-ness of this bug.
- I did reproduce on a cloud test server (using `--version release-6.0`) and the PR fixes it.
- https://mattermost.atlassian.net/browse/MM-38744
> MM-38744 - Fix for: Broadcast stops if one channel is read-only

- webapp/src/components/markdown_textbox.tsx
- Render the border outside (avoids overlapping the textbox contents and the scrollbar)
- https://mattermost.atlassian.net/browse/MM-38255
> MM-38255 - Fix for: Update content overlaps with the border of the text box

- tests-e2e/cypress/integration/backstage/playbook_overview_spec.js
- webapp/src/actions.ts
- webapp/src/components/backstage/playbooks/playbook_backstage.tsx
Navigating to a playbook and clicking "Run" sometimes doesn't work, even if Channels has already loaded, because something is forcing the websocket to disconnect and reconnect on the transition to Channels, losing the interactive dialog event. Workaround this with a timeout on dispatching the event in question.
Fixes: https://mattermost.atlassian.net/browse/MM-38251
> MM-38251: workaround "Run" from Playbooks

- server/api/playbook_runs.go
- server/app/reminder.go
- server/bot/bot.go
- webapp/src/client.ts
- webapp/src/components/update_request_post.tsx
- webapp/src/index.tsx
- Trigger the new style dialog using a custom post - it works for webapp and automatically falls back to the interactive dialog for mobile
- https://mattermost.atlassian.net/browse/MM-38731
> MM-38731 - Fix for: Old status update dialog partially exposed in web/desktop

- server/app/playbook_run_service.go
- server/app/playbook_run_service_test.go
An ugly fix for the categorization bug.
Comment in the code is pretty self-explanatory.
When user starts a run, channel is created, and user added to the channel. At that moment server sends the `user_added` socket event to the webapp. Webapp gets the event and tries to categorize the channel for the user by adding the channel to the default `CHANNELS` category. 
Concurrently we are trying to auto-categorize the channel into our category. Depending on what happens first channel might get stuck in `CHANNELS` category.
Unfortunately we can not reliably detect when webapp finished updating the state, that's why we are waiting for 5 seconds(A very magic number) to let webapp do its job.
Fixes: https://mattermost.atlassian.net/browse/MM-37314
- ~~[ ] Gated by …
> [MM-37314] Fix the categorization bug

- .circleci/config.yml
- tests-e2e/cypress/integration/frontstage/playbook_run_automation_spec.js
- tests-e2e/cypress/integration/frontstage/rhs/open_spec.js
Add a test that exercises our e2e suite with the global header enabled. Fix a recent regression in the e2e tests around the bot rename. Clean up some CircleCI stuff while we're in there.
The one failing test should be fixed with https://github.com/mattermost/mattermost-server/pull/18464.
https://mattermost.atlassian.net/browse/MM-38779
> MM-38779: test with globalheader

- Makefile
- webapp/.eslintrc.json
- webapp/babel.config.js
- webapp/i18n/en.json
- webapp/package-lock.json
- webapp/package.json
- webapp/src/components/datetime_input.tsx
- webapp/src/components/modals/update_run_status_modal.tsx
- webapp/src/components/rhs/rhs_home_item.tsx
- webapp/src/index.tsx
- Adds minimum tooling for message extraction to JSON (`webapp/i18n/en.json`)
(i18n-check will come in a later PR)
- Adds registration to provide messages to upstream `<IntlProvider/>`
- Adds a few sanity eslint rules to prevent `id`s and enforce `defaultMessage`s
An important note about `id`s: they are automatically generated via a checksum of the content of a descriptor's `defaultMessage`—this prevents stale translations and ensures duplicate strings will not be created (`"Help"` will always be `"Help"`—if a particular instance of `"Help"` is changed, it will automatically kick out a new `id` yet leave other unaffected instances as-is.)
- https://mattermost.atlassian.net/browse/MM-38935
> MM-38935: Webapp, i18n mvp tooling

- plugin.json
- webapp/src/components/backstage/playbooks/playbook_backstage.tsx
Use the new URL provided by webapp. See [the PR](https://github.com/mattermost/mattermost-webapp/pull/9012) there for more information.
https://mattermost.atlassian.net/browse/MM-38908
> MM-38908: When clicking Run, navigate to the new URL provided by webapp

- plugin.json
- webapp/src/components/backstage/playbooks/playbook_backstage.tsx
Cherry-pick into `release-1.20` of #780.
--
> Cherry-pick MM-38908: When clicking Run, navigate to the new URL provided by webapp (#780)

- tests-e2e/cypress/integration/backstage/playbook_run_list_spec.js
- webapp/src/components/backstage/runs_list/filters.tsx
- webapp/src/components/backstage/runs_list/run_list_header.tsx
Fix case of `Finished runs`:
and `Run name`:
N/A
> tweak case of "Finished runs" and "Run name"

- server/app/playbook_run_service.go
- webapp/src/components/rhs/rhs_run_details.tsx
- Will record interactions with each of the todo list sections. We can total the number of interactions, group based on unique userId, and by section (to see which section is most useful).
- If found, the search param is removed from the url (leaves other search params untouched)
- I added it to the RHSRunDetails component so that in the future we can use this params method to scroll to and/or highlight specific checklist items (e.g., click on the checklist item due, and we'll take you right to that item -- or as close as possible to that)
- cc @stephenvanhemmen 
- POC ✅ 
- Include list of ongoing runs ✅ 
- Include list of overdue updates ✅ 
- Send digest once a day when user logs on ✅ 
- Telemetry (<--- we're here)
- Design polish
- e2e tests (once we have a firmed up design)
- …
> MM-38872 - Telemetry for the todo message

- webapp/src/components/backstage/playbooks/playbook.tsx
- webapp/src/components/backstage/playbooks/playbook_preview.tsx
- webapp/src/components/backstage/playbooks/playbook_preview_navbar.tsx
Add telemetry events for clicks on
- each of the sections in the preview navigation widget,
- the Preview and Usage tabs, and
- the button below the navigation widget, the one that reads "X active runs".
And although it's completely unrelated to telemetry, I also refactored the `Item` component to make the JSX in the `Navbar` component a bit easier to read. That change is isolated in the first commit.
https://mattermost.atlassian.net/browse/MM-39090
> MM-39090: Telemetry on preview page (and tiny refactor)

- webapp/package-lock.json
- webapp/package.json
- webapp/src/components/formatted_duration.test.tsx
- webapp/src/components/formatted_duration.tsx
Migrate FormattedDuration from Moment to Luxon and remove moment dependency
Fixes https://github.com/mattermost/mattermost-server/issues/18595
JIRA: https://mattermost.atlassian.net/browse/MM-39152
> Migrate FormattedDuration from Moment to Luxon and remove moment dependency

- webapp/src/index.tsx
Temporarily lock to english for 1.21 release (aim to open in 1.22)
mattermost.atlassian.net/browse/MM-38151
> [MM-38151] Lock translations to `en`, just for 1.21

- webapp/i18n/en.json
- webapp/src/components/backstage/playbook_runs/playbook_run_backstage/retrospective/timeline_event_item.tsx
Re: https://github.com/mattermost/mattermost-plugin-playbooks/pull/830 / [MM-38841](mattermost.atlassian.net/browse/MM-38841), retro timeline dates off, can potentially result in white-screen errors with `Invalid date` console errors.
> MM-38841: fix retro timeline dates

- server/app/playbook_run_service.go
- server/app/playbook_run_service_test.go
- server/plugin.go
This PR 
1. Makes all participants followers by default
2. Sends status updates to followers  only if they have permission to access run.
Fixes: https://mattermost.atlassian.net/browse/MM-39255
> [MM-39255] Make all participants followers by default

- tests-e2e/cypress/integration/channels/actions_spec.js
- tests-e2e/cypress/integration/channels/broadcast_spec.js
- tests-e2e/cypress/integration/channels/channel_header_spec.js
- tests-e2e/cypress/integration/channels/rhs/checklist_spec.js
- tests-e2e/cypress/integration/channels/rhs/header_spec.js
- tests-e2e/cypress/integration/channels/rhs/home_spec.js
- tests-e2e/cypress/integration/channels/rhs/status_update_spec.js
- tests-e2e/cypress/integration/channels/rhs_spec.js
- tests-e2e/cypress/integration/channels/run_dialog_spec.js
- tests-e2e/cypress/integration/channels/run_spec.js
- tests-e2e/cypress/integration/channels/slash_command/info_spec.js
- tests-e2e/cypress/integration/channels/slash_command/owner_spec.js
- tests-e2e/cypress/integration/channels/slash_command/test_spec.js
- tests-e2e/cypress/integration/channels/slash_command/todo_spec.js
- tests-e2e/cypress/integration/navigation_spec.js
- tests-e2e/cypress/integration/playbooks/creation_button_spec.js
- tests-e2e/cypress/integration/playbooks/edit_spec.js
- tests-e2e/cypress/integration/playbooks/list_permissions_spec.js
- tests-e2e/cypress/integration/playbooks/list_spec.js
- tests-e2e/cypress/integration/playbooks/overview_spec.js
- tests-e2e/cypress/integration/runs/details_spec.js
- tests-e2e/cypress/integration/runs/list_spec.js
- tests-e2e/cypress/integration/runs/timeline_spec.js
- tests-e2e/cypress/support/plugin/ui_commands.js
Organize into the following directory structure, rendering the term `backstage` obsolete in this context and treating `channels` as an integration and not the `frontstage`.
- cypress/integration (all specs live here)
- playbooks/
- runs/
- channels/
- rhs/
- slash_command/
- (other global tests)
The top level `describe` of each spec now contains the path (e.g.  `channels > rhs > spec_name`). There's probably still room for improvement here, both in the organization and naming, but this gets us past the hump as it were.
I'm proposing we do something similar for the `webapp` component. Open for discussion -- hoping this makes the code easier to navigate.
N/A
> Reorganize E2E Tests

- server/plugin.go
`playbookRunService` uses `playbookService` which was created after the `playbookRunService`. This PR fixed this issue
Fixes: https://mattermost.atlassian.net/browse/MM-39908
> [MM-39908] Fix nil reference bug

- tests-e2e/cypress/integration/playbooks/edit_spec.js
- tests-e2e/cypress/support/plugin/ui_commands.js
- webapp/src/components/backstage/automation/broadcast.tsx
- webapp/src/components/backstage/channel_selector.tsx
- webapp/src/components/backstage/playbook_edit.tsx
- webapp/src/components/backstage/styles.tsx
- webapp/src/components/datetime_input.tsx
- webapp/src/components/update_request_post.tsx
- webapp/src/index.tsx
- Refactor and globalize `react-select` theming overrides to support portaling.
- Mount/unmount global style in index-init., as we don't have an always-active, central mounting point.
- Replaces classNamePrefix `channel-selector` with `playbooks-rselect` as the shared select is used for multiple things.
- https://mattermost.atlassian.net/browse/MM-39938
> MM-39938: react-select theming, support portaling

- webapp/src/components/backstage/playbooks/playbook_preview_actions.tsx
- webapp/src/components/backstage/playbooks/playbook_preview_checklists.tsx
- webapp/src/components/backstage/playbooks/playbook_preview_status_updates.tsx
The original ticket focused on the action that automatically selects a default owner when the run starts: when said action was enabled but no actual user was added (which is actually possible, and hopefully something we'll fix when the edit screen is revamped), then its preview rendered in a weird state.
But this happens with most actions: we need to check both that they are enabled and that they have actual content (the owner is selected, there is at least one webhook, there is at least one user invited...).
This PR addresses all these cases, also changing the negative boolean conditions into positive ones, which are way easier to read.
https://mattermost.atlassian.net/browse/MM-39939
> MM-39939: Hide enabled actions that have no actual content

- Makefile
After [this conversation](https://community-daily.mattermost.com/core/pl/bf4kq4i77fnr5qzqrpwqz3befa) in Mattermost, I decided to set up this simple proof of concept to build only one binary when developing locally.
Right now I'm using the environment variable `MM_SERVICESETTINGS_ENABLEDEVELOPER`, but we could also use any ad-hoc variable. This PR is just intended to continue the conversation so it does not die in a poor abandoned thread.
Let me know what you think!
--
> Build just one binary on a developer environment

- webapp/src/components/checklist_item.tsx
This PR removes the `display: flex` style of the description container, fixing the weirdly centered ordered lists in the tasks description.
Before:
After:
For context, this is how lists are rendered in posts (it looked weird to me in the first place in the description, but it's the same in channels)
> MM-40048: Fix ordered lists rendering in playbook preview

- webapp/src/hooks/crud.ts
Change the checklists, tasks and run columns on the /playbooks/playbooks to sort descending on the first click, bringing to the top the playbooks with the most checklists, tasks or runs respectively. Subsequent clicks on the same column should continue to toggle the direction.
* https://github.com/mattermost/mattermost-server/issues/18960
https://mattermost.atlassian.net/browse/MM-39933
> [MM-39933]:On click sort numeric playbook columns in descending order

- server/app/playbook_run_service.go
- server/app/playbook_service.go
- server/app/urls.go
- server/app/urls_test.go
- tests-e2e/cypress/integration/channels/channel_header_spec.js
This PR goal is to use relative URLs instead of absolute in the header of the channel created by a new playbook run.
https://github.com/mattermost/mattermost-server/issues/18905
> [MM-39772] Use relative URLs in the channel header

- webapp/src/components/backstage/automation/patterned_input.tsx
- webapp/src/components/backstage/automation/patterned_text_area.tsx
a couple `<textarea>`s and an `<input>` on the action settings page were not fully disabled when their corresponding toggles were off because they lacked the `disabled` attribute. this PR flips the relevant logic and prop naming so that attribute does actually get set.
fixes https://mattermost.atlassian.net/browse/MM-35201
> [MM-35201] Set `disabled` attribute on settings inputs

- README.md
- tests-e2e/cypress/support/api/on_prem_default_config.json
update `on_prem` `MaxFileSize`  default config and add a README note about `CYPRESS_developerMode`. I'll keep thinking about whether there's a better way to account for config stuff but it's probably worth documenting while we're using it.
> Cypress default config & README updates

- webapp/src/components/rhs/rhs_run_details.tsx
- webapp/src/hooks/general.ts
Scroll to top when the run is finished. To actually finish the run, the user needs to click on an interactive dialog, to which we don't have direct access. Thus, what this PR does is listening to any change of `run.current_status`, and fires the scrolling event when it changes to finished.
https://user-images.githubusercontent.com/3924815/142421094-957bc309-c69a-4257-a3f8-45659dd53518.mp4
https://mattermost.atlassian.net/browse/MM-38954
> MM-38954: Scroll the RHS to top when the run is finished

- plugin.json
Community has the requisite code (Luxon), but didn't actually get bumped to 6.1 like we expected. Let's drop the min version for a few days until it catches up to restore Playbooks to community.
None.
> temporarily drop min version to 6.0

- server/sqlstore/stats.go
- server/sqlstore/stats_test.go
- If there are no incidents for a playbook, the select statement wasn't able to generate the columns that we expect later. There are a couple ways to solve it, this seemed cleanest.
- https://mattermost.atlassian.net/browse/MM-40263
> MM-40263: Stats are erroring when there are no runs for a playbook

- Makefile
- plugin.json
Adding the linux arm64 targets, we start building arm64 for the server and will start adding the targets for the plugins for the ones we prepackage in the build
related to: https://github.com/mattermost/mattermost-server/pull/18491
related to https://mattermost.atlassian.net/browse/DOPS-633
> dist: build linux arm64 targets

- tests-e2e/cypress/integration/channels/rhs/header_spec.js
- webapp/i18n/en.json
- webapp/src/components/dot_menu.tsx
- webapp/src/components/rhs/rhs_about.tsx
- webapp/src/components/rhs/rhs_about_buttons.tsx
- webapp/src/components/rhs/rhs_about_description.tsx
This PR is modifying the hamburger menu of a run in the RHS to add an explicit "Edit run summary" item.
https://github.com/mattermost/mattermost-server/issues/18972
1) My ReactJS skills are not perfect, so I'm not quite sure that the way I implemented the communication between components is the "state of the art" way to do it. I'm happy to change that to whatever is best!
2) I had to use a bit of trickery to have the hamburger menu open in the e2e tests because it appears only when the mouse goes over the container. I tried using `trigger('mouseover')` on the container but it did not work and [cypress has no implementation of `hover` yet](https://docs.cypress.io/api/commands/hover#Workarounds) was not enough. To …
> [MM-39529] Adding an item in the run's RHS dropdown menu to edit a run summary

- plugin.json
This reverts commit abb1f129d7ea5eefb16a4f865082251b45762726, requiring v6.1 again in anticipation of the upcoming v1.22.
N/A
> Revert "temporarily drop min version to 6.0 (#905)"

- tests-e2e/cypress/support/extended_commands.js
Every `cy.visit` and `cy.reload` has some additional waiting applied to it, but it would be nice to reduce that if it doesn't increase test flake significantly. Several local runs seemed ok with these changes, this is to test CI. If that has problems, I'll change this to be included only with `CYPRESS_developerMode` so at least test development will be faster.
> Reduce Cypress waits

- webapp/src/client.ts
This PR fixes the copy link bug. 
Turns out `basePath` stored in the `clients.ts` file contains just the path name - not the entire site URL. What a surprise, amrite? :D
Fixes: https://mattermost.atlassian.net/browse/MM-40500
> [MM-40500] Fix copy link

- tests-e2e/cypress.json
This lowers the numbers of test debug snapshots available in the Cypress runner from the default `50` to `5` in order to avoid OOM crashes when running specs with a large number of tests (`edit_spec.js` for example).
> Cypress: Reduce numTestsKeptInMemory

- tests-e2e/cypress/integration/playbooks/overview_spec.js
- tests-e2e/cypress/support/plugin/api_commands.js
- webapp/src/components/backstage/playbooks/playbook_preview.tsx
Adds a few more tests on the main Playbook preview as well as one for the usage tab. Also slight reorder of the file so all of the single `it` blocks come before the nested `describe` blocks. 
https://mattermost.atlassian.net/browse/MM-39896
> MM-39896: Add more preview tests

- tests-e2e/cypress/support/api/role.js
- webapp/src/components/backstage/runs_list/playbook_selector.tsx
- webapp/src/components/profile/dropdown_selector_style.tsx
- webapp/src/components/profile/profile_selector.tsx
- webapp/src/components/team/create_playbook_team_selector.tsx
Instead of importing a SCSS stylesheet with global definitions, rewrite as a styled components and wrap the affected components.
Note that the profile selector, as a widget, deserves some general refactoring. This PR doesn't attempt to address that.
Fixes: https://mattermost.atlassian.net/browse/MM-37227
> MM-37227: move profile selector to styled components

- .circleci/config.yml
This enables parallel test runs in CircleCI. Based on some test runs it cuts the Cypress jobs to ~9 minutes, which means the whole workflow will also be ~9 min since those are the longest running jobs.
https://mattermost.atlassian.net/browse/MM-35035
> MM-35035: Cypress parallelism

- webapp/src/components/profile/dropdown_selector_style.tsx
- A recent change made the checklist headers change their z-index based on how many checklists there are -- so I'm changing the profile dropdown to have a z-index of 50, under the assumption that we won't ever have that many checklists -- unless you think we should go even higher?
- https://mattermost.atlassian.net/browse/MM-40656
> MM-40656: Z-index issue between sticky headers and user profile dropdown

- client/playbook_runs.go
- server/api/playbook_runs.go
- server/api_runs_test.go
- server/app/mocks/mock_playbook_run_service.go
- server/app/playbook_run.go
- server/app/playbook_run_service.go
- server/telemetry/noop.go
- server/telemetry/rudder.go
- webapp/i18n/en.json
- webapp/src/actions.ts
- webapp/src/client.ts
- webapp/src/components/collapsible_checklist.tsx
- webapp/src/components/collapsible_checklist_hover_menu.tsx
- webapp/src/components/rhs/rhs_checklist.tsx
- webapp/src/components/rhs/rhs_checklist_list.tsx
- webapp/src/reducer.ts
- webapp/src/types/actions.ts
This PR adds the ability to reorder checklists in the RHS:
- It adds an endpoint to move a checklist (the old `/move` now moves checklists, whereas the one to move items is now called `/move-item`)
- It refactors the `DragDropContext` structure from react-beautiful-dnd:
- it first contains a `Droppable`, where all checklists can be dropped,
- every checklist is now a `Draggable`, with a new icon that shows on hover that acts as the handle,
- each checklist is still a `Droppable`, with every item being a `Draggable`.
- To keep the collapsed state of every checklist in sync, I had to add a new action to the store so that we can overwrite the whole state of `Record<number, boolean>` that keeps track of it: if we move the i-th checklist to the j-th position, we need to update the state of …
> MM-40305: Reorder checklists in RHS

- webapp/src/components/rhs/post_card.tsx
Update time spec in Run Overview by adding `Today`, `Yesterday`, `<weekday>`, `month day[, year]`. This is the same format used in Channels post tooltips and date separators.
- https://mattermost.atlassian.net/browse/MM-39124
---|---
Gated by experimental feature flag? | N
> MM-39124: Run Overview timestamp format

- tests-e2e/cypress/integration/runs/retrospective_spec.js
#954 additions:
- adds a test around the new behavior
- change a couple `click({force: true})` calls to `click()` thanks to `findByRole`
> MM-38732: retrospective tests

- server/app/playbook.go
- server/app/playbook_run_service.go
- webapp/src/components/modals/update_run_status_modal.tsx
- webapp/src/components/rhs/rhs_checklist_list.tsx
When the confirmation for a run finish is shown, skipped tasks are no longer considered "outstanding".
https://mattermost.atlassian.net/browse/MM-40659
- ~~Telemetry updated~~
-  ~~Gated by experimental feature flag~~
- ~~Unit tests updated~~
> MM-40659: Skipped tasks incorrectly marked as unfinished

- webapp/src/components/backstage/backstage.tsx
The `-40px` calc was [introduced in mattermost-webapp](https://github.com/mattermost/mattermost-webapp/blob/56d0522/sass/layout/_team-sidebar.scss#L171-L179), now ours can be removed.
- https://mattermost.atlassian.net/browse/MM-40833
---|---
Telemetry updated? | NA
Gated by experimental feature flag? | NA
> MM-40833: fix /playbooks height

- tests-e2e/cypress.json
- tests-e2e/cypress/support/api/cloud_default_config.json
- tests-e2e/cypress/support/api/on_prem_default_config.json
- tests-e2e/cypress/support/api/system.js
`getDefaultConfig()` was trying to fetch `config.enableOnboardingFlow` from `tests-e2e/cypress.json` but that key is actually present under `config.env.enableOnboardingFlow`. This should prevent the view from appearing and failing tests both in CI (which @cpoile already fixed, so should be double good now) and locally.
> e2e: fix config plumbing for EnableOnboardingFlow

- tests-e2e/cypress/integration/api/runs_spec.js
- tests-e2e/cypress/support/plugin/api_commands.js
changes to #975 to shave off some extra boilerplate. 
- `apiRunPlaybook` now accepts a status code and `failOnStatus` so it can handle both fail/success instead of just `201`
> test revisions

- assets/i18n/en.json
- server/app/playbook_run.go
- server/app/playbook_run_service.go
- server/sqlstore/playbook_run.go
- server/sqlstore/playbook_run_test.go
- tests-e2e/cypress/integration/channels/slash_command/todo_spec.js
- tests-e2e/cypress/support/api/user.js
- tests-e2e/cypress/support/index.js
Following up on [this thread](https://community-daily.mattermost.com/core/pl/gza8jybbrtn5ifeqq9r5bbmwhr), let's stop notifying participants about runs with overdue status updates of which they are not the owner. We're not finding this to be an actionable event at this time, and want to "stop the spam" while we revisit the overall approach.
N/A
> Stop notifying others' overdue runs

- server/app/playbook.go
- server/sqlstore/playbook_test.go
Fix [this](https://app.circleci.com/pipelines/github/mattermost/mattermost-plugin-playbooks/5263/workflows/2a5e9589-2a42-4568-9a20-eb5c428a40e0/jobs/34434/tests#failed-test-0):
```
Failed
=== RUN   TestDeletePlaybook/mysql_-_create_and_delete_playbook
assertion_compare.go:313:
Error Trace:	playbook_test.go:1091
Error:      	"1642446666733" is not greater than "1642446666733"
Test:       	TestDeletePlaybook/mysql_-_create_and_delete_playbook
Messages:   	[]
Dropped temporary database dbn9u6tgjuu3g79rgs3hxacubzto
Dropped temporary database dbzfmfwfk77bdfifk4f1ocnrsewa
--- FAIL: TestDeletePlaybook/mysql_-_create_and_delete_playbook (0.00s)
```
N/A
> Fix flaky TestDeletePlaybook/mysql_-_create_and_delete_playbook

- tests-e2e/cypress.json
- tests-e2e/package-lock.json
- tests-e2e/package.json
#951 uses `shelljs` for some file manipulation. @cpoile was seeing this:
I think that's because `shelljs` is currently only in `package-lock.json`. This PR explicitly adds it to `package.json` and updates the lockfile as well.
I also removed `cypress-multi-reporters` as it's no longer used.
> e2e: package update

- webapp/package-lock.json
- webapp/package.json
Fix the following by upgrading to the mattermost-webapp version that includes https://github.com/mattermost/mattermost-webapp/pull/9617:
```
npm ERR! npm WARN tarball tarball data for mmjstool@git+ssh://git@github.com/mattermost/mattermost-utilities.git#17ee7abdc0ccaec5d432123fcabc7fe73abe33ac (sha512-wHUORQrEsVFMgSBJvkXnRPJ1/PpcyNP9B+SHzN35/Y0tGvRqGAN+ZwIPBewIq91b5iEZWxRZX1ufrDnI0rAOwg==) seems to be corrupted. Trying again.
npm ERR! npm WARN tarball tarball data for mmjstool@git+ssh://git@github.com/mattermost/mattermost-utilities.git#17ee7abdc0ccaec5d432123fcabc7fe73abe33ac (sha512-wHUORQrEsVFMgSBJvkXnRPJ1/PpcyNP9B+SHzN35/Y0tGvRqGAN+ZwIPBewIq91b5iEZWxRZX1ufrDnI0rAOwg==) seems to be corrupted. Trying again.
npm ERR! npm ERR! code EINTEGRITY
npm ERR! npm ERR! …
```
> fix mmjstool integrity check

- webapp/src/components/markdown_textbox.tsx
- Added nowrap to the right column. I assumed that we wanted to keep the left as is (since there really isn't anything else we can do -- it's going to wrap)
- https://mattermost.atlassian.net/browse/MM-39571
> MM-39571 - Fix for: Longer-worded languages cause text to wrap in markdown_textarea

- webapp/src/components/backstage/playbook_runs/playbook_run_backstage/overview/updates.tsx
- webapp/src/components/backstage/playbook_runs/shared.tsx
- webapp/src/components/rhs/post_card.tsx
Flex children use `min-width: auto` by default, so setting `min-width: 0` avoids that they expand the width of their parents.
I also deleted some unused code I found.
Before:
And after:
https://mattermost.atlassian.net/browse/MM-40153
> MM-40153: Fix wrapping in run overview

- tests-e2e/cypress/integration/channels/rhs/home_spec.js
- webapp/package-lock.json
- webapp/package.json
- webapp/src/components/backstage/template_selector.tsx
- webapp/src/types/js-trim-multiline-string.d.ts
- webapp/src/types/playbook.ts
Introduce an `Employee Onboarding` playbook based on https://handbook.mattermost.com/operations/workplace/people/working-at-mattermost/onboarding/manager-onboarding-1#onboarding, and a bug bash playbook based on our own [Playbooks: Bug Bash](https://community.mattermost.com/playbooks/playbooks/zp1xp684zig5pg9np4ccixudoh) playbook:
As per @calebroseland, introduce [`mtrim`](https://github.com/md-vanilla/js-trim-multiline-string) for easier handling of multi-line, indented strings.
Tidy up some of the existing templates, adding descriptions and unifying styling.
Note that I'm deferring the use of "new" icons in the template selector until the pending rework of this widget.
Fixes: https://mattermost.atlassian.net/browse/MM-41090
> MM-40838: new & reworked templates

- webapp/src/components/rhs/rhs_shared.tsx
This PR removes h1-h6 styling from the `PostText` component
Before:
After:
Fixes: https://mattermost.atlassian.net/browse/MM-37705
> [MM-37705] Remove h1-h6 styling

- webapp/src/components/assets/right_dots.tsx
- webapp/src/components/assets/right_fade.tsx
- webapp/src/components/backstage/backstage.tsx
- webapp/src/components/backstage/playbook_list.tsx
- There was a change made in https://github.com/mattermost/mattermost-webapp/pull/9639 where the height was changed from `height: calc(100% - 40px)` to `height: 100%`, which I don't totally understand. Boards made a fix in https://github.com/mattermost/focalboard/pull/2217 to change it back, and we're doing similar here. I'm not totally pleased with this solution, but I don't understand why the original change was made in webapp (waiting on an explanation) so I don't want to mess with webapp. And we're broken now, so this fixes our current problem. Hopefully in the future we can change it back.
- While working on this I also fixed the scrollbar problem I've been seeing for awhile:
Previous:
Fixed:
- https://mattermost.atlassian.net/browse/MM-41515
> MM-41515 - Fix for: Cannot paginate playbooks

- webapp/src/components/backstage/backstage.tsx
- The original webapp PR https://github.com/mattermost/mattermost-webapp/pull/9639 is reverted https://github.com/mattermost/mattermost-webapp/pull/9755 -- if that gets into 6.4.0 (it should) then we won't need #1020 .  This is the revert for #1020 .
- https://mattermost.atlassian.net/browse/MM-41615
> MM-41615 - Fix for backstage height needs to be reverted

- go.mod
- go.sum
- server/app/export_test.go
- server/app/playbook.go
- server/app/playbook_run.go
- server/sqlstore/migrations.go
- server/sqlstore/playbook_run_test.go
- server/sqlstore/playbook_test.go
- tests-e2e/cypress/integration/playbooks/edit_metrics_spec.js
- webapp/src/components/backstage/playbook_edit/metrics/metric_edit.tsx
- webapp/src/components/backstage/playbook_edit/metrics/metric_view.tsx
- webapp/src/components/backstage/playbook_edit/metrics/metrics.tsx
- webapp/src/components/backstage/playbook_edit/metrics/shared.ts
- webapp/src/types/playbook.ts
- I'm proposing to use the null.v4 pkg to support storing nulls in sql and json. Here I'm using it for the `int64` target and value fields, but the pkg supports strings and floats etc. It's pretty lightweight, simple to use and seamless (unless you want to do calculations in go, but then you'd have the same problem with using pointers I'd think).
- Here's the docs: https://pkg.go.dev/gopkg.in/guregu/null.v4 and the githup repo: https://github.com/guregu/null
- @lieut-data for visibility and if you want to comment or nix this addition.
- Added e2e tests to lock down our ability to remove target fields or add a 0 value for a target.
- https://mattermost.atlassian.net/browse/MM-41684
> MM-41684 - Support null targets and values

- server/telemetry/rudder.go
- server/telemetry/rudder_test.go
- Add NumMetrics to every playbook telem event, and to the publish retro PlaybookRun event (it's useless to have it attached to every playbookRun event, it would just be noise)
- https://mattermost.atlassian.net/browse/MM-41667
> MM-41667 - Playbook metrics telemetry

- tests-e2e/cypress/integration/playbooks/edit_spec.js
- webapp/src/components/backstage/playbook_list.tsx
When you land explicitly on `/playbooks/start`, and playbooks exist, redirect back to regular `/playbooks/playbooks`.
- 1/N of https://mattermost.atlassian.net/browse/MM-41060
---|---
Gated by experimental feature flag? | N
Unit/E2E tests updated? | Y
> MM-41060: redir to regular playbooks list if playbooks exist

- webapp/src/components/tutorial/tutorial_tour_tip/manager.ts
- webapp/src/components/tutorial/tutorial_tour_tip/tutorial_tour_tip.tsx
`close` will now skip the current tutorial. Previously `close` would glitch-hide then reshow the next tip. Clicking on the backdrop is unchanged and hides the tour tip without removing the dot (can reopen by clicking the dot.)
- https://mattermost.atlassian.net/browse/MM-41724
---|---
Telemetry updated? | Y
Gated by experimental feature flag? | N
> MM-41724: skip on close tour tip

- .circleci/config.yml
set a timeout `-m 5` on the `curl` and don't test the result for now
> e2e: Trial license workaround

- client/playbook.go
- server/api/stats.go
- server/sqlstore/playbook_test.go
- server/sqlstore/stats.go
- server/sqlstore/stats_test.go
This PR Adds backend functionality to spit out metrics statistics info. Front-end will display statistics info on the  `Playbook Key metrics` tab.
PR adds these fields to the `Playbook` stats API:
- `MetricOverallAverage []int64` - Average value for each metric, indexed by metric, in the same order as `playbook.metrics`. Only published metrics are included in the calculations. 
- `MetricRollingAverage []int64` - Average values for the last published `x` runs.
- `MetricRollingAverageChange []int64` - Last 10 days average diff compared to previous 10 days average. For example, value +15 means that the last 10 days value went up by 15% compared to the previous period.
- `MetricValueRange [][]int64` - Each array contains two values, min and max values for each metric.
- `MetricRollingValues …
> Mm 41664 playbook key metrics tab backend

- server/sqlstore/stats_test.go
This PR fixes `TestMetricsStats` test bug. There was a chance that two runs had the same published date, which caused inconsistency in sorting metrics values by `RetrospectivePublishedAt`.  
> Fix PublishedAt time generation issue

- tests-e2e/cypress/integration/channels/rhs/checklist_spec.js
This test fails some low percentage of the time in CI but still seems useful to keep, so retry on failure for now. This could be a Cypress issue (I've seen a few different viewport related failures on various tests) or an actual UI inconsistency, I haven't been able to repro locally so I'm not sure which.
> e2e: enable retries on flaky viewport test

- server/app/playbook_run.go
- server/app/playbook_run_service.go
- server/command/command.go
- tests-e2e/cypress/integration/channels/slash_command/todo_spec.js
Currently, running /playbook todo currently posts from the playbooks bot as a DM to the user.
This PR makes the response an Ephemeral Post on the channel where the command is called.
Fixes: https://mattermost.atlassian.net/browse/MM-40504
Github issue - https://github.com/mattermost/mattermost-server/issues/19171
> MM-40504 - Send ephemeral post to user on channel when `/playbooks todo` command is called

- webapp/src/components/backstage/runs_list/checkbox_input.tsx
This PR fixes checkbox label wrapping on the runs list page. 
This change will fix a similar issue on other pages(where the same checkbox is used):
- Playbooks list page, `"With archived"` filter.
- Playbooks preview page, `"Auto-follow runs"`'
- Playbook run status update popup, `"Also mark the run as finished"`
https://mattermost.atlassian.net/browse/MM-38718-Parts%20of%20/runs%20wrapping%20when%20content%20is%20wide
> Fix checkbox label wrapping

- webapp/i18n/en.json
- webapp/src/components/backstage/playbooks/playbook_preview_actions.tsx
We got a report from a translator asking what this sentence with "no user" meant, but it turns out that this sentence is never shown to the user, as that entry is only rendered if there is at least one user auto-following runs.
https://mattermost.atlassian.net/browse/MM-42422
> MM-42422: Remove unused string

- tests-e2e/cypress/support/plugin/ui_commands.js
- tests-e2e/cypress/support/ui_commands.js
- Adds `cy.clickPostActionsMenu`
- Fixes `cy.startPlaybookRunFromPostMenu`
Before
After
(See checks)
None
---|---
Telemetry updated? | NA
Gated by experimental feature flag? | NA
Unit/E2E tests updated? | Y
> E2E: fix (2) flaky tests—new post actions menu

- tests-e2e/cypress/integration/channels/broadcast_spec.js
This is a fix for a test-bug introduced in #1088. The test added there relies on the channel being completely empty, so we need to create a brand new channel instead of relying on one that was used by other tests before.
https://mattermost.atlassian.net/browse/MM-42437
> MM-42437: Create a new channel for the do-not-broadcast test

- webapp/src/components/actions_modal.tsx
I could not reproduce the bug locally, so let's see if moving it from right after the header to right before the modal body (which ends up being the exact same spot) works.
https://mattermost.atlassian.net/browse/MM-42845
> MM-42845: Move the bar from the header to the modal body

- webapp/src/components/actions_modal_trigger.tsx
Webkit-based browsers seem not to apply `flex-direction: column` when the children are `span`, so this PR changes the trigger header elements to `div` instead to fix the bug. Firefox and Chrome render both implementations in the same way.
I was only able to test this using Midori, which renders the whole webapp in a terrible way, but I was able to reproduce the bug and to confirm that this solution fixes it. However, I still need someone to take a look in Safari.
Screenshot of the solution in Midori:
https://mattermost.atlassian.net/browse/MM-42854
> MM-42854: Use div instead of span to fix a bug in Safari

- webapp/i18n/en.json
- webapp/src/components/backstage/playbook_runs/playbook_run_backstage/overview/participants.tsx
The "Message" button has been present on the run overview for sometime, ostensibly to allow users to directly reach out to the participants in question via a DM. I can't recall ever using this, and there are issues rendering this page with long titles.
Proposing we just remove the messaging functionality altogether as we look forward to a revamped run overview page in Q2.
Fixes: https://mattermost.atlassian.net/browse/MM-38534
Fixes: https://mattermost.atlassian.net/browse/MM-39123
> MM-38534: Remove message button on run overview

- server/api/signal.go
- tests-e2e/cypress/integration/channels/general_actions_spec.js
When porting the ephemeral post to a regular post, I forgot to change this call. Funnily enough, `DeleteEphemeralPost` does delete a regular post temporarily, but when reloading the page, it appears again.
I added an E2E test to check the behaviour of the `No, ignore thread` button too.
https://mattermost.atlassian.net/browse/MM-43037
> MM-43037: Fix prompt post deletion

- server/api_playbooks_test.go
- server/app/permissions_service.go
- server/main_test.go
- webapp/i18n/en.json
- webapp/src/components/backstage/playbook_access_modal.tsx
- webapp/src/components/backstage/public_private_selector.tsx
- webapp/src/hooks/general.ts
Cherry-picks #1017 to `release-1.23`, so we can release a v1.23.1 and add it to a new v6.3.7 (I think it's 7).
I tested this in the following v6.3.6 servers, and the cherry-pick seems to work as expected. @Phrynobatrachus, could you give it a second look?
- https://mm41513-e0.test.mattermost.cloud
- https://mm41513-e10.test.mattermost.cloud
- https://mm41513-e20.test.mattermost.cloud
https://mattermost.atlassian.net/browse/MM-42888
> MM-41513: Restrict private playbooks (#1017)

- tests-e2e/cypress/integration/channels/rhs_spec.js
- webapp/src/components/rhs/rhs_main.tsx
- webapp/src/rhs_opener.ts
In community, in my case, the first request to retrieve runs gets 86 of them, of which only 6 are in progress. This request happens every time the team changes, to populate the Redux store with all the team runs. However, I suspect`*` we only need the runs in progress, which are the ones where we need to automatically open the RHS on channel switch.
This PR changes that initial request to get only in progress runs.
`*` I say suspect because the logic there is a bit complex, and I'm not 100% sure of all the implications, but I'm confident enough to at least try this in community for a while and see how it behaves. I tested it thoroughly locally, but only time, in community, will tell.
https://mattermost.atlassian.net/browse/MM-42509
> MM-42509: Change initial fetch to get only in progress runs

- server/app/playbook_run_service.go
Increases the maximum length of the Add New Task dialog to match with the default character limit in webapp, which is 4000.
Also changes the description input type to `textarea` to support easier entry for long texts.
Fixes https://github.com/mattermost/mattermost-server/issues/19356
> [GH-19356] MM-41063, MM-40565: Increase new task dialog description length

- .circleci/config.yml
I've still been seeing occasional random CI failures on the license upload step recently. It's probably worth having this to save needing to retry in the Circle UI. The last issue with this endpoint was fixed so I think it should be fine to use.
> e2e: curl retries for license upload

- tests-e2e/cypress/integration/tours_spec.js
Some coverage for the recently added tours.
> e2e: Add basic smoke tests for playbook tours

- webapp/src/actions.ts
- webapp/src/components/backstage/playbook_access_modal.tsx
- webapp/src/components/backstage/playbooks/playbook.tsx
On the `Playbook preview` page, public/private icon did not update automatically when converting a playbook to private. 
A similar case was with the number of members, addin/removing a member did not update the number.
`Playbook access modal` and `Playbook preview` have their own copies of playbook object, so changes in the modal didn't reflect on the preview page. This PR fixes both issues by updating the preview page state from the modal.
Note: New Playbook editor has the same issues. I can't fix it now because it's under development.
https://user-images.githubusercontent.com/4368372/163686074-e9cd6a08-26cd-4c01-bc79-f41ad5e66f16.mp4
https://mattermost.atlassian.net/browse/MM-41580
> Fix private/public icon update issue

- server/api/playbook_runs.go
- server/app/playbook_run.go
- server/app/playbook_run_service.go
- server/app/playbook_run_service_test.go
- server/sqlstore/migrations.go
- server/sqlstore/playbook_run.go
This PR removes the `broadcast to followers` flag from run data mode. There is no need for such a flag based on business requirements. 
> Remove followers run action flag

- server/app/playbook_run_service.go
- server/app/playbook_run_service_test.go
This PR excludes summary info from daily digest message when there are only tasks due in the future and returns empty text. As a result, the daily digest message is skipped when we only have tasks due in the future.
https://mattermost.atlassian.net/browse/MM-43586
> Add skipping daiy digest when there are only tasks due after today

- .circleci/config.yml
- Makefile
CI is consistently failing due to `too many clients already` in postgre
I just increased the max_connection in PostgreSQL by triggering a custom command with parameters.
I still don't know if those many connections are an additional problem or if it's expected. Research needs to continue, but with green CI :).
[Link to convo](https://community.mattermost.com/core/pl/fghckz9ng7yi9nc45ixmb17dkw) for anyone who wants to work on it locally.
Fixes https://mattermost.atlassian.net/browse/MM-43833
> CI server tests fixed

- webapp/src/components/update_request_post.tsx
None
---|---
Gated by experimental feature flag? | NA
> Fix long string overflow in status update reminder

- webapp/src/components/backstage/playbooks/playbook_preview_checklists.tsx
- webapp/src/components/checklist_item/checklist_item.tsx
- webapp/src/components/checklist_item/checklist_item_draggable.tsx
- webapp/src/components/rhs/rhs_checklist.tsx
- webapp/src/components/rhs/rhs_checklist_list.tsx
Disable the checklist menu that appears when doing hover if we are currently doing drag&drop.
Menu hover is disabled for:
- the item you are currently dragging 
- any other item you may hover while dragging.
A Flag has to be managed at the top dropable level, so a new prop needs to be passed to checklist and checklist_item. 
https://mattermost.atlassian.net/browse/MM-43415
> disable hover menu in checkist while dragging

- tests-e2e/cypress/integration/channels/rhs/status_update_spec.js
- tests-e2e/cypress/integration/channels/update_request_post_spec.js
- tests-e2e/cypress/integration/runs/details_spec.js
- tests-e2e/cypress/support/plugin/ui_commands.js
- webapp/src/components/modals/update_run_status_modal.tsx
If the user leaves without saving changes in update_run_status modal, a confirmation modal will be shown.
E2E tests added
This modal has a mix of visibility state management that makes it a bit harder to make changes: inside the component uses useState(showModal), and from the outside is controlled by modalProps.onHide().  That is the main reason why I had to replace some setShowModal with modalProps.onHide().
Fixes https://mattermost.atlassian.net/browse/MM-43513
> update run status ask for confirmation if accidental cancel

- tests-e2e/cypress/integration/channels/rhs/status_update_spec.js
- webapp/src/components/modals/update_run_status_modal.tsx
- webapp/src/types/playbook_run.ts
Opens automatically run actions modal when the user navigates from post update modal (RHS)
We use the link in two situations in the modal:
- when there are broadcast channels -> we do open the modal in the navigation
- when there's no followers or broadcast -> we do NOT automatically open the modal
Completes https://mattermost.atlassian.net/browse/MM-43130
> automatically open runactions modal when navigating from post-status

- .circleci/config.yml
The two changes to note besides the image bumps:
1) `CGO_ENABLED=0` - found some history in Community that suggested this might help
2) cache keys modified to ensure caches were regenerated
> Update CircleCI images to Go 1.18

- server/app/playbook_run_service.go
- server/app/playbook_run_service_test.go
Allow one-character playbook names. Channel allows one-character name (`master` on `mattermost-server`), and playbook run name which is a channel name should support one-character naming. The pull request edits the checks on the `model.AppError`.
Fixes: https://github.com/mattermost/mattermost-server/issues/20108
> [MM-43880] Allow one-character playbook names

- tests-e2e/cypress/integration/channels/rhs/checklist_spec.js
- webapp/src/components/checklist/generic_checklist.tsx
This PR fixes issue with RHS Checklist item showing the due date of an item with the same name from another channel. It happened because items with the same name had the same `key` attribute values, and switching between channels did not render the list component.
Updated `key` generation logic, now its value is unique.
This recording shows the problem:
https://user-images.githubusercontent.com/4368372/167859688-d401720a-c88f-40d1-8ff8-8df0809f2797.mp4
https://mattermost.atlassian.net/browse/MM-43936
> Fix checklist item render issue

- server/api/graphql_root.go
Graphql updates need to be guarded with a null check.
> Fix graphql checklist update.

- webapp/src/client.ts
- webapp/src/components/checklist_item/checklist_item.tsx
- webapp/src/components/checklist_item/checklist_item_draggable.tsx
- webapp/src/components/checklist_item/inputs.tsx
Optimistic approach to checkbox state management.
The main reasons why I pushed for this change are:
- offer a more responsive UI in a task that I'd expect to be quick as a user
- be more defensive to websocket failures where users don't see the UI update and even could click several times keeping a trash value
Approach:
**client.ts**
`doPut`and `doFetchWithResponse` already throw a ClientError if status is not OK
Catch that error and return it as data.
**checklist_item_draggable and checklist_item**
type the return value and add the possibility of `undefined`
**inputs**
do the following:
1. handle current value and setter through useState
2. onChange: calculate the new value and set it immediately
3. onChange: await prop passed with `setChecklistItemState`
4. if the result is not …
> handle optimistic updates to checkbox in checklist item

- server/api/playbook_runs.go
- server/app/actions_service.go
Avoid logging errors if we don't have actions in a channel and a new member joins.
Additionally, I changed the order in `getPlaybookRunByChannel` to have a more relevant error (before it reported permissions failure if the run does not exist).  Personally, I would omit this kind of error from the logs since it seems like an expected flow to me (to reproduce leave and rejoin a channel without a run).
Fixes https://mattermost.atlassian.net/browse/MM-43636
> do not log error if 0 actions in channel when a user joins

- webapp/src/websocket_events.ts
To attach the welcome message from channel actions, we are currently triggering 4 requests in each channel switch. The reason this happens is:
- several mark_as_read are sent in channel_switch, for old and new channels (not expected, but apparently they are preventing some race conditions)
- each mark_as_read generates a channel_viewed WebSocket event 
- each channel_viewed event is handled with fetch_actions and handle welcome if not previously viewed
The mitigation is done by changing the order of the WebSocket channel_viewed registered handler:
- return as soon as possible if the channel was already viewed
- fetch actions
- if welcome action is enabled -> execute it
This is not the definitive solution but improves the performance.
Fixes (partially) …
> do not ask for channel actions if the channel has been already visited

- webapp/src/components/dot_menu.tsx
Force the` DropdownMenuItem` title to an empty string. It's needed to prevent the trigger icon from appearing for all his children.
Fixes https://mattermost.atlassian.net/browse/MM-44193
> force empty title in menuItem to prevent trigger title from propagating

- webapp/src/components/actions_modal.tsx
- webapp/src/components/channel_actions_modal.tsx
- webapp/src/components/run_actions_modal.tsx
Vertically center *more* the modals for run&channel actions.
I tried the centered property in react-modal but there were lots of conflicting injected styles. The channel actions modal has a fixed height, but the run actions modal has a variable height, so in some situations could not be perfectly aligned.
Fixes: https://mattermost.atlassian.net/browse/MM-44196
> modal manually centered

- tests-e2e/cypress/integration/runs/actions_spec.js
- webapp/src/components/backstage/channel_selector.tsx
- webapp/src/components/backstage/playbook_edit/automation/broadcast.tsx
- webapp/src/components/broadcast_channel_selector.tsx
- webapp/src/components/run_actions_modal.tsx
**The problem**: When visiting the run overview page directly, the Redux store is not pre-populated by Channels, so the Run Actions modal did not have the information on the channels the user is a member of, thus showing an empty dropdown menu in the channel selector (and showing any channel already added as `Unknown channel`, even if the user had access to them).
**The solution**: When first mounting the channel selector, if the store is empty, just populate the Redux store with the channels the user is a member of.
@lieut-data, I was considering adding a cache similar to #1177 to prevent a problem of the same type in the future in this component. I decided not to do it, though, as it seems rare that we will have more than one of these components mounted at the same time, and much more …
> MM-44160: Fix empty channel selector

- tests-e2e/cypress/integration/channels/rhs/checklist_spec.js
- webapp/src/components/checklist_item/checklist_item.tsx
Do not shrink assigned user pill (hide name) when due date but state closed or skip. Since due date is hidden, the user name should be shown.  
Fixes https://mattermost.atlassian.net/browse/MM-44194
> RHS: keep full assignee pill when due date and not state-open

- server/bot/poster.go
This PR adds message content for the `start_trial_to_access_metrics` admin notification. It was missing, and because of that admin was getting empty messages.
https://mattermost.atlassian.net/browse/MM-44366
> Add message for playbooks metrics admin notification

- server/api/graphql_root.go
- server/api_graphql_playbooks_test.go
Fixes default owner not saving in graphql. 
https://mattermost.atlassian.net/browse/MM-44647
> MM-44647 Fix inverted check for default owner.

- webapp/src/client.ts
- webapp/src/index.tsx
This should fix CORS issues on community caused by the SiteURL not being equal to the URL of access. For community the SiteURL is set to https://community.mattermost.com/ if you access community with https://community-daily.mattermost.com/ you will recieve CORS errors because our graphql and webapp clients are using the SiteURL for access. This PR changes both of those to use the same method as the webapp does by taking the URL from the window object.
> Make plugin fetch consistant with webapp fetch.

- webapp/src/components/checklist_item/checklist_item.tsx
We unintentionally required users to enter edit mode for checklist items to be able to change the owner or due dates, but these should have stayed accessible directly:
Fixes: https://mattermost.atlassian.net/browse/MM-44763
> MM-44763: allow direct dropdown editing again

- webapp/i18n/en.json
- webapp/src/components/backstage/backstage.tsx
- webapp/src/components/backstage/backstage_list_header.tsx
- webapp/src/components/backstage/playbook_editor/playbook_editor.tsx
- webapp/src/components/backstage/playbook_list.tsx
- webapp/src/components/backstage/playbook_list_row.tsx
- webapp/src/components/pagination_row.tsx
- webapp/src/components/templates/template_item.tsx
- webapp/src/components/templates/template_selector.tsx
- webapp/src/components/widgets/header.tsx
- webapp/src/types/global.d.ts
Changes overall layout to match new designs but without additional functionality; new UX/functionality will come in subsequent PRs.
- Update Playbooks List design
- Make full-width (constrained to `max-width: 1160px` on old page; unconstrained on LHS-enabled screen)
- Minor page hierarchy changes
- Update Playbook Editor design
- Make full-width 
- (https://github.com/mattermost/mattermost-plugin-playbooks/commit/a1c1496f46b81a778af9f6239cc0661bc5ed5d7a) Fix: Global Header menus disappearing on Playbooks List page in Safari
(I couldn't repro this one locally, but could repro on community—the fix applied in devtools fixes it)
New list screen
Current list screen (`width` constrained if `experimental == false`, all other changes ungated)
Global Header menus disappearing in Safari …
> MM-44962: Playbooks List and Playbook Editor UI changes to match new LHS experience

- webapp/src/hooks/general.ts
Preserve `hash` in URL replacement when using `useRunsList`.
- https://mattermost.atlassian.net/browse/MM-45127
---|---
Gated by experimental feature flag? | N
> MM-45127: Fix scroll-to section in playbook editor.

- .config/notice-file/Readme.md
- .config/notice-file/config.yaml
We created a tool to automatically generate NOTICE.txt from project folders. And there is a scheduled pipeline configured to run at every Monday which creates a PR if there is a change.
Some sections need to be managed by developers at Notice.txt. And pipeline needs locations/files to search the dependencies. That configuration need to be stored in this repo, so developers will manage those and configure tool without leaving this repo.
Tool repo: https://github.com/mattermost/notice-file-generator
We selected `.config/notice-file` to store the configuration files. And it is configurable, feel free to change it if another location is more convenient.
> Configure playbooks for Notice.txt file auto-generation

- webapp/src/components/backstage/playbook_runs/playbook_run/rhs_info_overview.tsx
Add `text-overflow: ellipsis` to the Playbook link in the Overview section of the RHS of the Run Details Page.
https://mattermost.atlassian.net/browse/MM-45401
> MM-45401: Ellipsize Playbook link in Run Details Page RHS

- webapp/src/components/backstage/playbook_runs/playbook_run/rhs_info_activity.tsx
- webapp/src/components/backstage/playbook_runs/playbook_run/rhs_timeline.tsx
- webapp/src/components/backstage/playbook_runs/playbook_run_backstage/retrospective/timeline_event_item.tsx
Allow participants to navigate post-related events to channel post.
In separate PR, rhs internal navigation will be explored for status updates.
no ticket
> enable post navigation from timeline to channel

- webapp/src/components/backstage/backstage.tsx
- webapp/src/components/backstage/playbook_runs/playbook_run/checklists.tsx
- webapp/src/components/backstage/playbook_runs/playbook_run/playbook_run.tsx
- webapp/src/components/backstage/playbook_runs/playbook_run/retrospective.tsx
- webapp/src/components/backstage/playbook_runs/playbook_run/status_update.tsx
- webapp/src/components/backstage/playbook_runs/playbook_run/summary.tsx
- webapp/src/components/rhs/rhs_checklist_list.tsx
This simply sets up the infrastructure needed to automatically scroll to every element in the main section of the page when using an anchor link. Try, for example, to visit `/playbooks/run_details/<run_id>#playbook-run-retrospective` to see it.
I'll add the actual navigation links in other PR.
https://mattermost.atlassian.net/browse/MM-45446
> MM-45446: Auto scroll infrastructure

- webapp/src/components/backstage/playbook_runs/playbook_run/rhs_info_overview.tsx
- webapp/src/components/checklist_item/assign_to.tsx
This fixes the bug in the Run Details Page where the members in the owner selector appeared in the wrong category. We can now pass an explicit channel ID to the `AssignTo` component instead of always relying on the ID of the current channel, which may not exist.
https://mattermost.atlassian.net/browse/MM-45412
> MM-45412: Fix categorization of users in owner dropdown list

- server/api/actions.go
- server/app/action.go
- server/app/actions_service.go
- server/telemetry/noop.go
- server/telemetry/rudder.go
This adds telemetry to track every update of channel actions. On top of that, it adds the `ChannelID` property to every telemetry event related to channel actions; this should have been there from the beginning.
https://mattermost.atlassian.net/browse/MM-45090
> MM-45090: Track channel action update

- webapp/src/components/backstage/playbook_list.tsx
- webapp/src/components/templates/template_item.tsx
- fix:template item hover in Safari
- fix: playbook menu being clipped
|  before  |  after  |
|---|---|
| <img width="347" alt="CleanShot 2022-06-29 at 23 35 50@2x" src="https://user-images.githubusercontent.com/11724372/176594525-104cc0bb-e9f3-4ce2-a672-faf4a804bde9.png">  |  <img width="331" alt="CleanShot 2022-06-29 at 23 36 38@2x" src="https://user-images.githubusercontent.com/11724372/176594519-b267419b-11a6-4241-ad13-5bbef025bdf1.png"> |
| <img width="331" alt="" src="https://user-images.githubusercontent.com/11724372/176594636-59023b3a-a0a1-4f80-9257-4dfb7068cee1.png">  |  <img width="331" alt="" src="https://user-images.githubusercontent.com/11724372/176594646-09141e80-c978-4554-9053-5257cac28a79.png"> |
- https://mattermost.atlassian.net/browse/MM-44500 …
> MM-44500: fix template item hover, fix playbook menu being clipped

- server/api/playbook_runs.go
- server/app/playbook_run.go
When working on my hackathon idea, I quickly realized I had to copy code from the API layer to create a playbook run, because the `createPlaybookRun` function, containing a lot of important logic, lived there. This PR refactors the important pieces out of that function and into the PlaybookRun struct; namely: populating the run's checklist from the playbook and copying the playbook configuration into the run configuration. The logic is not changed at all, this simply moves code around.
This, in the first place, makes the code much more readable and modularized. As a side effect, it helps me to reuse this logic in my hackathon project :sunglasses: 
--
> Refactor logic from createPlaybookRun 

- webapp/src/components/backstage/playbook_runs/playbook_run/playbook_run.tsx
- webapp/src/components/backstage/playbook_runs/playbook_run/retrospective.tsx
- webapp/src/hooks/telemetry.ts
Implement telemetry event for tracking views of the run details page.
New event instead of reusing previous ones. Additionally, a hack has been included in the telemetry hook to prevent retrospective events to be triggered when we re-use the component inside run-details page.
Fixes https://mattermost.atlassian.net/browse/MM-45546
> create a new telemetry event for run details page view

- webapp/src/components/rhs/rhs_home.tsx
Environment:
- branch 7.1 (without new modal with team selector)
- below E20 (no private playbook permission)
Steps to reproduce:
- open RHS in a channel without RUNs
- click on "use" template to create a playbook
Result: 403 forbidden since we try to create a public playbook
3/5 on solution, I'm not very familiar with permissions. I've been inspired from create_playbook_modal but I'd appreciate some review.
Fixes https://mattermost.atlassian.net/browse/MM-45608
> Mm 45608 create public playbooks from rhs when no e20

- tests-e2e/cypress/integration/runs/rdp_main_checklist_spec.js
- tests-e2e/cypress/integration/runs/rdp_main_retrospective_spec.js
- tests-e2e/cypress/integration/runs/rdp_main_summary_spec.js
- webapp/i18n/en.json
- webapp/src/components/backstage/playbook_runs/playbook_run/retrospective.tsx
- webapp/src/components/backstage/playbook_runs/playbook_run/summary.tsx
Continuation on the e2e effort for Run Details Page
It covers summary, checklist and retro.
The checklist test covers some basic points and relies on full tests done for Channels RHS checklist.
The retrospective is slightly different from other sections because when we definitely remove the old page we will:
- move the retro component inside the new playbook run folder
- remove the older tests (retrospective_spec and metrics_spec)
Also some small changes:
- different placeholder in summary when the user is viewer (instead of "add a summary")
- hide publish retro button if user is viewer (instead of disabled)
Fixes https://mattermost.atlassian.net/browse/MM-45351
> Mm 45351 viewer test rdp

- webapp/src/components/create_playbook_modal.tsx
- webapp/src/components/datetime_selector.tsx
- webapp/src/components/dropdown.tsx
- webapp/src/components/team/team_selector.tsx
https://community.mattermost.com/core/pl/mrrgjqzmhfywbb7hyibmfkxuba
- (https://github.com/mattermost/mattermost-plugin-playbooks/commit/459de7e4b78cee20367ec3488a81b32340b12ae4) Fix: hover menu duedate selector not focusing
- Change: default to portal (during https://github.com/mattermost/mattermost-plugin-playbooks/pull/1306/files#diff-c0e4dc8aa5d743606c160185470180181a25616b7215650bc66d68c50178fb38R91 had mistakenly been set to default off, which did not cause any issues but is better to default on than default off)
- UX: Fix team selector dropdown button not full width
| before | after |
|---|---|
|  <img width="400" alt="image" src="https://user-images.githubusercontent.com/11724372/178362732-a19cba6e-e0ea-416c-beb6-cf28f5c33c62.gif">  |  <img width="400" alt="image" …
> MM-45346: fix duedate selector in hover menu

- server/sqlstore/migrations.go
- server/sqlstore/store_test.go
- server/sqlstore/user_info_test.go
Add all users who are participating in runs to playbooks to they will appear in the LHS when we switch over. 
Any user who is a participant in any of a public playbook's runs should be added to that playbook as a member. 
@Phrynobatrachus could I have your help testing this?
https://mattermost.atlassian.net/browse/MM-45575
> MM-45575 Playbook member migration.

- webapp/src/components/backstage/playbook_runs/playbook_run/context_menu.tsx
- webapp/src/components/dot_menu.tsx
Feedback on the run title:
- adjusted padding 
- hover/active/open styles as the channel context menu
- dot menu works like a toggle now **globally** (click again if open to close it). This affect lots of other dotmenus, but it seems globally desired 
```
2. The hover state on the run name is mis-aligned. Recommended change: padding: 2px 2px 2px 6px;
3. When the run name dropdown is open, the run name should stay in the highlighted state. Please check channel name dropdown for reference.
``` 
Demo:
https://user-images.githubusercontent.com/4096774/178491441-c1236ac1-63b3-40e1-b0c5-5febff991e02.mp4
Fixes: https://mattermost.atlassian.net/browse/MM-45674
> fine tune run title control + toggle open in dotmenu

- webapp/src/components/rhs/rhs_checklist_list.tsx
As stated in the ticket, the padding was increased from 8px to 12px. The functional issue was actually already solved by https://github.com/mattermost/mattermost-plugin-playbooks/pull/1313 :)
https://mattermost.atlassian.net/browse/MM-45676
> MM-45676: Increase margin between title and checklist box

- tests-e2e/cypress/integration/runs/list_spec.js
- webapp/src/components/backstage/playbook_runs/playbook_run/playbook_run.tsx
Now we have team bar, we have to add 72px to our calculatios for max-width
no ticket
> add 72px to avoid teambar in max-width calculations

- .circleci/config.yml
- .golangci.yml
- Makefile
- server/api/playbooks.go
- server/sqlstore/playbook.go
- server/telemetry/rudder.go
- server/telemetry/rudder_test.go
Recover golangci linters: gosimple, unused and staticcheck.
At CI:
- Since cicleci image is forcing 1.45.2 version, a new step is added to force the tool to be udpated
- PR [sent to circleci](https://github.com/CircleCI-Public/cimg-go/pull/183) . If they accept this change, we can remove the additional step to replace the binary.
At Local dev env:
- force version check to 1.46.2 in `make check-style` to force everyone to update :) (Sorry if this makes some noise, but it's important to have the linters locally)
Changes in the codebase:
//nolint tag in the deprecated lines. VScode will still warn about it but we won't break CI.
NOpe
> Recover golangci staticcheck, gosimple and unused linters

- server/api/playbook_runs.go
Fix memory issue. nil posts due to retrieval error were still being used.
A simple continue clause fix that.  
```
Jul 18, 2022 @ 10:39:09.667 | Received HTTP request
  | Jul 18, 2022 @ 10:39:09.653 | Plugin failed to ServeHTTP, RPC call failed
  | Jul 18, 2022 @ 10:39:09.572 | Received HTTP request
  | Jul 18, 2022 @ 10:39:09.487 | Received HTTP request
  | Jul 18, 2022 @ 10:39:09.048 | Plugin failed to ServeHTTP, RPC call failed
  | Jul 18, 2022 @ 10:39:09.048 | plugin process exited
  | Jul 18, 2022 @ 10:39:09.044 | created by net/rpc.(*Server).ServeCodec
  | Jul 18, 2022 @ 10:39:09.044 | Plugin failed to ServeHTTP, RPC call failed
  | Jul 18, 2022 @ 10:39:09.044 | net/rpc/server.go:478 +0x3fe
  | Jul 18, 2022 @ 10:39:09.044 | net/rpc/server.go:381 +0x226
  | Jul 18, 2022 @ …
```
> fix memory issue when looking at nil posts

- webapp/src/components/backstage/playbook_list.tsx
- webapp/src/components/backstage/runs_page.tsx
Removes final remaining experimental flag checks to restore full-width Playbooks List and Runs List.
None
---|---
Gated by experimental feature flag? | Not anymore
> LHS: remove experimental checks (e.g. narrow-width runs/playbooks)

- webapp/src/components/checklist_item/checklist_item.tsx
Long commands use all space until the edge of the checklist, add a margin-right to prevent it.
|before|after|
|--------|----------|
|![Screenshot 2022-07-20 at 12 33 26](https://user-images.githubusercontent.com/4096774/179962817-a6390a02-d770-4fbf-9c5d-714d2e8716e7.png)|![Screenshot 2022-07-20 at 12 35 16](https://user-images.githubusercontent.com/4096774/179962765-e99bf274-c8da-416e-96ec-48d81829b3c9.png) |
|![Screenshot 2022-07-20 at 12 33 06](https://user-images.githubusercontent.com/4096774/179963083-4acfc148-9624-4529-8aa5-0431801dead0.png)| ![Screenshot 2022-07-20 at 12 32 07](https://user-images.githubusercontent.com/4096774/179963118-332f191c-c706-49ac-bb4f-922984921538.png) |
Fixes https://mattermost.atlassian.net/browse/MM-45727
> prevent long commands to get to the edge in checklist

- server/api_runs_test.go
- server/app/playbook_run_service.go
We create an event for run timeline when a status update is requested. We want to additionally link the post sent to the channel so we can navigate from timeline to channel (just participants).
Fixes https://mattermost.atlassian.net/browse/MM-45851
> add postid info to timeline event when requesting an update

- server/api/categories.go
- server/sqlstore/category.go
- webapp/src/client.ts
- webapp/src/components/sidebar/group.tsx
- webapp/src/components/sidebar/item.tsx
- webapp/src/components/sidebar/playbooks_sidebar.tsx
- webapp/src/components/sidebar/sidebar.tsx
This PR will support collapsing categories. 
Currently we do not save `RUNS` and `Playbooks` categories in the DB(we generate them), so this PR does not add the possibility to save collapsed state for those 2 categories. For other categories everything works fine.
If you collapse `RUNS` or `PLAYBOOKS` and refresh they will appear expanded. If this is not usable, I'll add the collapsed state for those too.
https://user-images.githubusercontent.com/2340127/180065696-ac0f76d2-7a46-450e-8d91-dfc39b893c41.mp4
> Collapse categories

- webapp/src/actions.ts
- webapp/src/components/backstage/playbook_runs/playbook_run/playbook_run.tsx
- webapp/src/components/backstage/playbook_runs/playbook_run/rhs_timeline.tsx
- webapp/src/components/backstage/playbook_runs/playbook_run/timeline_utils.ts
- webapp/src/components/backstage/playbook_runs/playbook_run_backstage/retrospective/timeline_retro.tsx
- webapp/src/reducer.ts
- webapp/src/selectors.ts
- webapp/src/types/actions.ts
- webapp/src/types/rhs.ts
The main goal of this task is to be coherent when navigating from recent activity to RHS timeline. We were navigating from partial to complete information, having actually less events (due to filters)
To fix that, several actions have been addressed:
- extract feature from redux, the main component handles the filter state. if you reload the page, you lose the state and have the default.
- when navigating from recent activity "all" filter is automatically enabled 
- tasks events are visible by default
- if you change run in LHS, filters are reset
2/5 on the behavior. With this change, we keep the "all" filter after navigating through recent activity. We could, in addition to that, revert to previous filters if wanted (with some internal double state).
Note that a big part of this PR is …
> extract from redux event filters

- webapp/src/components/backstage/playbook_list.tsx
- webapp/src/components/backstage/playbook_list_row.tsx
This was a piece left over from #1327.
None
> remove unneeded team selector from import flow

- server/plugin.go
Honour `MetricsSettings.Enable` to at least allow turning off prometheus metrics if undesired. A more holistic, upcoming change will integrate plugin metrics directly with the server to avoid even opening a separate port.
Fixes: https://github.com/mattermost/mattermost-plugin-playbooks/issues/1359
> Honour MetricsSettings.Enable

- tests-e2e/cypress/integration/runs/rdp_rhs_runinfo_spec.js
- webapp/src/components/backstage/playbook_runs/playbook_run/rhs_info.tsx
Hide RHS key metrics section when retrospective is disabled.
Fixes https://mattermost.atlassian.net/browse/MM-46081
> hide key metrics in rhs if retro is disabled

- tests-e2e/cypress/integration/runs/rdp_main_header_spec.js
- webapp/src/components/actions_modal.tsx
- webapp/src/components/channel_actions_modal.tsx
- webapp/src/components/patterned_text_area.tsx
- webapp/src/components/run_actions_modal.tsx
Prevent webhooks from being saved at "Run actions modal" when they are invalid. The save button handler is removed temporarily (until content is valid) and the style changed (less opacity). I considered that approach better than just hiding the save button (which is a bit unexpected).
Disabled text color for webhooks (when they are non-editable).
Fixes https://mattermost.atlassian.net/browse/MM-45959
Fixes https://mattermost.atlassian.net/browse/MM-45958
> prevent users from saving invalid webhooks

- tests-e2e/cypress/integration/runs/rdp_main_statusupdate_spec.js
- webapp/src/components/backstage/playbook_runs/playbook_run/status_update.tsx
Prevent participants from requesting updates once the run is finished
Fixes https://mattermost.atlassian.net/browse/MM-46073
> prevent request-update from execute when run is finished

- tests-e2e/cypress/integration/runs/rdp_rhs_runinfo_spec.js
- webapp/src/components/backstage/playbook_runs/playbook_run/playbook_run.tsx
- webapp/src/components/backstage/playbook_runs/playbook_run/rhs_info_activity.tsx
- webapp/src/components/backstage/playbook_runs/playbook_run/rhs_info_overview.tsx
- webapp/src/types/rhs.ts
Don't remove the channel from RHS when the run is finished (only when you don't have permission to join)
Keep all events at timeline enabled by default (no matter the navigation). Filters are kept on the playbook_run state (instead of rhs_timeline) to avoid resetting them if close/reopen rhs.
Fixes https://mattermost.atlassian.net/browse/MM-46119
Fixes https://mattermost.atlassian.net/browse/MM-46123
> recover channel and all timeline by default

- tests-e2e/cypress/integration/runs/rdp_main_retrospective_spec.js
- tests-e2e/cypress/integration/runs/rdp_rhs_runinfo_spec.js
- webapp/src/components/backstage/playbook_runs/playbook_run/rhs_info_overview.tsx
Remove onclick handlers in the items that are pure links in RHS overview at Run Details Page.
That make the cmd+click works natively due to the inner `<a>`. We lose the click handler for the whole row, but it's not critical since the links at the right part catch naturally all the clicks.
Done for playbook and channel links.
Fixes https://mattermost.atlassian.net/browse/MM-45960
> RDP RHS info: remove onclick events and keep regular a elements

- webapp/src/components/checklist_item/checklist_item.tsx
- webapp/src/components/checklist_item/duedate.tsx
After this PR, we will show a due date on finished/skipped tasks without a `late` warning. In such a way, finished tasks will not attract attention, and users can still quickly edit a due date. 
https://user-images.githubusercontent.com/4368372/182888081-af5319d4-f62a-4dc7-9223-d78d418b3316.mp4
https://mattermost.atlassian.net/browse/MM-46015
> Show due date on finished tasks without late warning style

- webapp/src/hooks/general.ts
This PR adds the ability to know in which component the purchase modal opening was initiated from
https://mattermost.atlassian.net/browse/MM-45761
https://mattermost.atlassian.net/browse/MM-45014
https://github.com/mattermost/mattermost-webapp/pull/10920
```release-note
NONE
```
> [MM-45761] - Telemetry: Track how many users end up in purchase/pricing modal/notify admin

- webapp/src/components/backstage/playbook_runs/playbook_run/rhs_participants.tsx
This PR fixes the participant label margin on the `RDP > RHS`
**Before**            vs.         **After**
https://mattermost.atlassian.net/browse/MM-46257
> Fix margin

- webapp/src/components/backstage/playbook_runs/playbook_run/playbook_run.tsx
- webapp/src/components/backstage/playbook_runs/playbook_run/retrospective.tsx
- webapp/src/components/backstage/playbook_runs/playbook_run/rhs_info.tsx
- webapp/src/components/backstage/playbook_runs/playbook_run/rhs_info_overview.tsx
- webapp/src/components/backstage/playbook_runs/playbook_run_backstage/retrospective/retrospective.tsx
- webapp/src/hooks/general.ts
Retrospective view telemetry is being triggered inside the run details page and shouldn't be triggered (already included, was part of old tab navigation).
Status updates and Run metadata were fetched twice when switching Runs in LHS due to permutations in the useEffect deps while new run is being processed.
Playbook hook removed from RHS, and passed as a prop from the main component to avoid duplicate fetch. 
- https://mattermost.atlassian.net/browse/MM-46400
- https://mattermost.atlassian.net/browse/MM-46399
> remove retrospective telemetry and duplicated requests in rdp

- webapp/src/components/backstage/playbook_runs/playbook_run/rhs_info_overview.tsx
This PR fixes two minor UI issues in the `RDP > RHS > Run overview`:
- adds a missing arrow at the end of the `Participants`
- fixes the channel name truncating with an ellipsis
**Before**                                     vs                                      **After**
https://mattermost.atlassian.net/browse/MM-46256
> Add arrow forward icon to participants section

- tests-e2e/package-lock.json
- tests-e2e/package.json
The new Cypress 10 runner has been locking up on me pretty frequently while working on tests. Saturn noticed the same but also tried `10.4` and said that it seemed much better, so :crossed_fingers:.
> e2e: Cypress 10.3 -> 10.6

- server/api/playbook_runs.go
- server/api_runs_test.go
- server/app/playbook_run.go
- server/app/playbook_run_service.go
- server/sqlstore/migrations.go
- server/sqlstore/playbook_run.go
- server/sqlstore/playbook_run_test.go
- server/sqlstore/stats.go
- server/sqlstore/stats_test.go
- server/sqlstore/support_for_test.go
Adding participants to the `IR_Run_Participants` table. Modifying the queries to pull from the updated list.
Note that there is currently no way to actually become a participant from the UI.
Also adding automatic adding and removing of participants/members as this was required to fix tests.
Commits are logical if you want to review incrementally.  
Fixes #1399
Fixes #1401
> Update run participants table and related queries.

- server/api/graphql_root.go
Prevent users without permissions from not being able to leave the playbook
Fixes https://mattermost.atlassian.net/browse/MM-46552
> avoid requiring permission for leaving a playbook

- server/app/playbook_run.go
- server/app/playbook_run_service.go
- server/sqlstore/playbook_run.go
- server/sqlstore/playbook_run_test.go
- webapp/package-lock.json
Before: we passed default role values to update a user channel role, which didn't work in cases when the channel had schema-managed roles. 
After: If the channel has scheme-managed roles, we retrieve them from the database and pass them to the `UpdateChannelMemberRoles`. 
https://mattermost.atlassian.net/browse/MM-39387
> Add channel scheme role support

- server/app/playbook_run_service.go
- webapp/src/components/checklist/generic_checklist.tsx
Duplicates the item next to itself. The behaviour before this was to add to the end of the list.
Instead of a simple append towards the end of the list, this PR creates a new list which is a copy of all the items before and after the duplicated item and returns it after adding the item at the supposedly new position.
Fixes: https://github.com/mattermost/mattermost-server/issues/20824
> [MM-44815] Duplicate task as next task instead of the last task

- Makefile
- server/telemetry/rudder_test.go
Adopt the model the server is using to version golangci-lint, simply installing the version needed instead of checking and failing.
Also fix a Go 1.19 warning re: deprecated `io/ioutil`.
> Switch model for versioning golangci-lint

- webapp/src/components/backstage/playbook_editor/outline/inputs/broadcast_channels_selector.tsx
Add missing hover effects to channel selector in playbook editor
Fixes https://mattermost.atlassian.net/browse/MM-44808
> add hover background color to pbe broadcast channel selector

- webapp/src/components/rhs/rhs_about_description.tsx
- webapp/src/components/rhs/rhs_about_title.tsx
Prevent users from accidentally enter into inline edit when they want to select the title or description in the channel RHS.
Fixes https://mattermost.atlassian.net/browse/MM-38717
> RHS: do not trigger inline edit if user is doing a text-selection

- webapp/src/components/backstage/playbook_editor/controls.tsx
- webapp/src/components/backstage/playbook_editor/playbook_editor.tsx
Removed negative letter-spacing on titles&context menu at PBE 
Set a 220px min width for dropdown options
|before|after|
|--------|-----|
|![Screenshot 2022-08-29 at 14 06 47](https://user-images.githubusercontent.com/4096774/187198260-9875bb02-82f7-4ac0-85c7-696ca2f0e4d3.png)|![Screenshot 2022-08-29 at 14 05 25](https://user-images.githubusercontent.com/4096774/187198288-db8bc8d7-8516-4b22-90dd-2d2ac612e4b1.png)|
Fixes https://mattermost.atlassian.net/browse/MM-45656
> PBE: remove negative letter spacing and set wider min-width for context menu

- webapp/i18n/en.json
- webapp/src/components/datetime_parsing.test.ts
- webapp/src/components/datetime_selector.tsx
- webapp/src/components/formatted_duration.test.tsx
Add a custom text&style for errors to datetime_selector.
Additionally, I added a failing test (skipped) for the case `1 month` parse. [parse duration lib](https://github.com/jkroso/parse-duration/blob/master/index.js#L46) take a month as the real number of days 365.25/12 instead of the standard 30 days (as luxon does). Will follow up on that case in a future PR. 
Fixes (partially) https://mattermost.atlassian.net/browse/MM-44810
[More context](https://community.mattermost.com/core/pl/mbqcs4dctiy95fhts6gxhaskcr)
> datetime selector: set custom error text

- server/api/graphql_root.go
- webapp/src/components/backstage/playbook_edit/automation/auto_assign_owner.tsx
- webapp/src/components/widgets/show_more.tsx
Migrate font-awesome to compass icons:
If merged after https://github.com/mattermost/mattermost-plugin-playbooks/pull/1460, currentColor prop can be removed.
```
src/components/backstage/playbook_edit/automation/auto_assign_owner.tsx:137:                        className='fa fa-times-circle'
src/components/widgets/show_more.tsx:103:        &.fa-angle-up {
src/components/widgets/show_more.tsx:196:    let showIcon = 'fa fa-angle-up';
src/components/widgets/show_more.tsx:199:        showIcon = 'fa fa-angle-down';
```
Opportunistic bugfix in playbook editor. It was not possible to clear the default owner in actions PBE.
**not migrated**
we need a spinner alternative and for system stats I'd do it all at once in mattermost-webapp
```
src/index.tsx:215:                        icon: 'fa-book', …
```
> migrate fa icons to compass + fix pb assign owner clear

- tests-e2e/cypress/integration/runs/rdp_main_header_spec.js
- webapp/src/components/dot_menu.tsx
- webapp/src/components/multi_checkbox.tsx
Resolved task filter context dropdown closing when checked and unchecked.
Now context dropdown is closed only when clicking on parent element, clicking outside the menu, or if dropdown parent appears on hover then hovering outside of the element.
https://github.com/mattermost/mattermost-server/issues/20821
> [MM-45662] Fix context dropdown closing when clicked

- webapp/src/components/backstage/select_users_below.tsx
add a portal=false (thanks @gbochora) in PBE members modal to recover the dropdown
manually tested, created task to [add e2e](https://mattermost.atlassian.net/browse/MM-46970)
Fixes https://mattermost.atlassian.net/browse/MM-46969
> add portal-false to dotmenu in pbe manage members

- webapp/package-lock.json
- webapp/package.json
- webapp/src/components/backstage/playbook_editor/controls.tsx
- webapp/src/components/backstage/playbook_editor/outline/scroll_nav.tsx
- webapp/src/components/backstage/playbook_editor/outline/section_actions.tsx
- webapp/src/components/backstage/playbook_list_row.tsx
- webapp/src/components/backstage/playbook_runs/playbook_run/retrospective/timeline_event_item.tsx
- webapp/src/components/rhs/rhs_about_buttons.tsx
- webapp/src/components/rhs/rhs_home_item.tsx
- webapp/src/components/sidebar/create_playbook_dropdown.tsx
Migrate mdi icons that have been created at https://github.com/mattermost/compass-icons/pull/47
playbook_edit (old) related code still has mdi icons, it will be deleted in a separated pr
I don't have an alternative for [accountcheckoutline icon](https://materialdesignicons.com/icon/account-check-outline), so I used icon-account-plus-outline. Let me know if that's right
Fixes https://mattermost.atlassian.net/browse/MM-46942
> migrate missing icons from mdi to compass

- webapp/webpack.config.js
The crash in the ticket happens when the `CSSTransition` component from `react-transition-group` gets mounted as part of the `ToastBanner` component. We're not sure specifically why that crashes, but it has to do with the Playbooks plugin compiling in a React 16 version of React DOM which is run against web app's React 17.
As I mentioned in the channel, this fixes the case when the web app and plugin are both up to date, but it won't handle the old plugin/new server case since the old plugin will still have React DOM compiled into it.
One big thing thing that this doesn't include those is that Playbooks will still be developed against React 16, so unit tests will be run against React 16 and we won't get any dependency errors due to mismatched React versions. We got quite a few dependency …
> MM-47028 Use version of React DOM provided by web app

- webapp/src/client.ts
- webapp/src/types/playbook.ts
- webapp/src/types/playbook_run.ts
- webapp/src/websocket_events.ts
This has been failing for a while, spamming the console logs, but seemingly providing little value in development. Propose just eliminating it altogether.
N/A
> Remove fetch type checking

- webapp/src/components/widgets/text_with_tooltip_when_ellipsis.tsx
Ensure debounce is cleaned up on unmount to avoid it running asynchronously after the tooltip component has been unmounted:
N/A
> Fix a setState after unmount

- tests-e2e/reporter-config.json
Prevents log output from showing up twice for each line.
> e2e: Fix duplicate logs

- tests-e2e/cypress/integration/lhs_spec.js
- webapp/src/components/backstage/lhs_run_dot_menu.tsx
- webapp/src/components/backstage/playbook_runs/playbook_run/rhs_info_overview.tsx
This PR adds LHS refresh after:
- Unfollowing the run from the LHS dot menu
- Following the run from RDP > RHS
https://user-images.githubusercontent.com/4368372/192373752-439b0108-1929-4c3a-819d-1a91b5c8d6ad.mp4
https://mattermost.atlassian.net/browse/MM-46916
https://mattermost.atlassian.net/browse/MM-46915
> Mm 46916 lhs not refreshed after unfollow

- tests-e2e/cypress/integration/channels/slash_command/test_spec.js
- tests-e2e/cypress/integration/runs/rdp_main_statusupdate_spec.js
- tests-e2e/cypress/support/api/preference.js
- webapp/src/components/backstage/playbook_runs/playbook_run/status_update.tsx
Move request update behind a professional license. It was already done for viewers, this PR cover the participants flow.
Code has been refactored a bit from `RequestUpdateButton` component to `useRequestUpdateUpgrade` hook to share upgrade flow/state among button/dotmenu item (viewer and participant triggers).
https://user-images.githubusercontent.com/4096774/193002562-903373b0-a96c-45e2-a2bd-9f26bf7516a0.mp4
Fixes https://mattermost.atlassian.net/browse/MM-46984
> move participant request-update cases behind professional license

- README.md
- tests-e2e/cypress/integration/channels/rhs/header_spec.js
- tests-e2e/cypress/integration/lhs_spec.js
- tests-e2e/cypress/integration/runs/rdp_general_spec.js
- tests-e2e/cypress/integration/runs/rdp_main_header_spec.js
- tests-e2e/cypress/integration/runs/rdp_main_statusupdate_spec.js
- tests-e2e/cypress/support/plugin/api_commands.js
- tests-e2e/cypress/support/plugin/ui_commands.js
Failures from these specs were due to tests interacting with certain elements while the DOM was unstable. The fixes rely on more accurately describing expected page state (`should(...)`) and/or `wait()`ing on a common request responsible for most of the data used on the page, prior to the problematic interactions.
> e2e: Fix recent failures

- tests-e2e/cypress/integration/channels/post_type_components_spec.js
- webapp/src/components/update_post.tsx
If a status update is permalinked and posted into another channel, and a user views that permalink without being a member of the run channel, the application crashes due to an attempt to resolve channel metadata.
Fixes: https://mattermost.atlassian.net/browse/MM-47558
> MM-47558: fix a crash re: status update posts

- tests-e2e/cypress/integration/channels/post_type_components_spec.js
- webapp/src/components/update_post.tsx
Follow up https://github.com/mattermost/mattermost-plugin-playbooks/pull/1515
- Send empty string when some extra props are undefined
- avoid relying on selectors whose triggers are not ready 
- add telemetry for 3 cases of post_udpate render (run channel + permalink scenarios)
No
> add telemetry testing to post_udpate + rely on post internal props

- server/api/graphql.go
- server/api/graphql_root_playbook.go
- server/api/graphql_root_run.go
- server/app/permissions_service.go
I was seeing a rash of permission logs on community from the GraphQL endpoints, that essentially looked like these two logs:
```
{
"timestamp": "2022-10-12 15:03:58.990 -03:00",
"level": "warn",
"msg": "Not authorized",
"caller": "app/plugin_api.go:979",
"plugin_id": "playbooks",
"error": "does not have permissions\ngithub.com/mattermost/mattermost-plugin-playbooks/server/app.init\n\tgithub.com/mattermost/mattermost-plugin-playbooks/server/app/permissions_service.go:15\nruntime.doInit\n\truntime/proc.go:6321\nruntime.d
oInit\n\truntime/proc.go:6298\nruntime.doInit\n\truntime/proc.go:6298\nruntime.main\n\truntime/proc.go:233\nruntime.goexit\n\truntime/asm_arm64.s:1165",
"request_id": "h4f5h3up7jfoi8saxikzpiypch",
"plugin_caller": "github.com/mattermost/mattermost-plugin-playbooks/server/api …
```
> reduce GraphQL error logs

- webapp/i18n/en.json
- webapp/src/components/backstage/follow_button.tsx
- webapp/src/components/backstage/import_playbook.tsx
- webapp/src/components/backstage/lhs_run_dot_menu.tsx
- webapp/src/components/backstage/playbook_editor/controls.tsx
- webapp/src/components/backstage/playbook_editor/outline/outline.tsx
- webapp/src/components/backstage/playbook_runs/playbook_run/context_menu.tsx
- webapp/src/components/backstage/playbook_runs/playbook_run/controls.tsx
- webapp/src/components/backstage/playbook_runs/playbook_run/header.tsx
- webapp/src/components/backstage/playbook_runs/playbook_run/rhs_info_overview.tsx
- webapp/src/components/backstage/playbook_runs/playbook_run/status_update.tsx
- webapp/src/components/backstage/runs_list/row.tsx
- webapp/src/components/backstage/toast.tsx
- webapp/src/components/backstage/toast_banner.tsx
- webapp/src/components/checklist/checklist_list.tsx
- webapp/src/components/checklist/generic_checklist.tsx
- webapp/src/components/profile/profile_selector.tsx
- webapp/src/components/rhs/rhs_about.tsx
- webapp/src/components/rhs/rhs_about_buttons.tsx
- webapp/src/components/rhs/rhs_about_description.tsx
- webapp/src/components/rhs/rhs_checklist_list.tsx
- webapp/src/components/rhs/rhs_main.tsx
- webapp/src/components/rhs/rhs_post_update.tsx
- webapp/src/components/rhs/rhs_run_details.tsx
- webapp/src/hooks/crud.ts
- webapp/src/hooks/run.tsx
Adds a read-only view for channel members of a run channel who are not participants in the run.
Read only view:
Clicking on:
- Summary
- Owner dropdown
- Status update button
- Finish run button
Causes a toast to appear:
Clicking participate causes the participate first dialog to appear:
Note that is is currently impossible to be in the channel without being a participant.
Note for reviewers there is some refactoring of the toast code and and the checklist code. They are in separate commits. 
Fixes #1442
> Read only view, channel members who are not participants

- webapp/src/components/rhs/rhs_checklist_list.tsx
- webapp/src/types/playbook.ts
Introduce a Show skipped tasks, defaulting on, that allows the user to optionally hide those tasks when filtering the checklists. It has same persistence semantics as Show checked tasks, meaning not remembered after a page reload. New option is shown just below the existing Show checked tasks option below.
Fixes: https://github.com/mattermost/mattermost-server/issues/21265
> [MM-21265] Checkbox to show/hide skipped tasks

- webapp/src/components/backstage/convert_private_playbook_modal.tsx
- webapp/src/components/backstage/playbook_access_modal.tsx
- webapp/src/components/backstage/playbook_editor/controls.tsx
- Add convert to playbook private menu in the dropdown
- Create custom hook for converting playbook private 
- Apply custom hook for playbook access modal for converting private
Fixes: https://github.com/mattermost/mattermost-server/issues/21184
JIRA: https://mattermost.atlassian.net/browse/MM-46382
> [MM-46382] Make convert to private playbook more prominent

- tests-e2e/cypress/integration/channels/rhs/home_spec.js
- tests-e2e/cypress/integration/channels/rhs/template_spec.js
- tests-e2e/cypress/integration/channels/rhs_spec.js
- tests-e2e/cypress/integration/playbooks/edit_metrics_spec.js
- tests-e2e/cypress/integration/runs/rdp_main_header_spec.js
- tests-e2e/cypress/integration/runs/taskinbox_spec.js
- tests-e2e/cypress/support/e2e.js
- tests-e2e/cypress/support/plugin/ui_commands.js
The test failures in `channels > RHS` specs from the past few days appear to be similar to the ones fixed in https://github.com/mattermost/mattermost-plugin-playbooks/pull/1510 - namely that the specs were trying to perform some action (clicking) while the DOM was still unstable. This PR adds some `should()` guards and API `wait()`s to avoid that.
> e2e: Flake fixes

- server/api_runs_test.go
- server/app/playbook_run_service.go
Removes instance where we continued to check channel permissions instead of run permissions. 
Fixes #1539
> Remove reminants of channel permissions.

- server/api/graphql_root_run.go
- server/api/schema.graphqls
- server/api_graphql_runs_test.go
- server/app/playbook_run.go
- server/sqlstore/playbook_run.go
- webapp/src/graphql/generated_types.ts
Adds the ability to list runs by channel using the GraphQL API. 
Note that it's currently impossible to get in a state where this API will actually return multiple results. The unique constraint needs to be removed, see #1560 
There should be no problem with committing this directly to master. 
There was some discussion in the ticket around making `participantOrFollowerID` optional, however it already has a default in the schema. 
I also think the changes here are simple enough not to warrent a new root resolver for this case.
Fixes #1545
> Adding channel filtering support to runs listing graphql API

- server/app/playbook_service.go
- tests-e2e/cypress/integration/playbooks/list_spec.js
- tests-e2e/cypress/integration/playbooks/overview_spec.js
- webapp/src/components/backstage/playbook_list_row.tsx
When duplicating a playbook, don't copy over the members list and instead automatically join it yourself. This allows you to immediately administrate the playbook, and avoids looping in other people who may not be interested.
Fixes: https://mattermost.atlassian.net/browse/MM-48366
> MM-48366: duplicate without members

- webapp/i18n/en.json
- webapp/src/actions.ts
- webapp/src/components/backstage/playbook_runs/playbook_run/rhs.tsx
- webapp/src/components/rhs/rhs_about.tsx
- webapp/src/components/rhs/rhs_main.tsx
- webapp/src/components/rhs/rhs_participants.tsx
- webapp/src/components/rhs/rhs_run_participants.tsx
- webapp/src/components/rhs/rhs_title.tsx
- webapp/src/types/rhs.ts
Adds loading the run participants list in the `Channels RHS`, instead of redirecting to the RDP. 
https://user-images.githubusercontent.com/4368372/201129805-a102f5b8-8046-4444-97d8-fe238e77669d.mp4
Fixes #1551
> 1551 channel rhs show participants

- webapp/src/components/checklist_item/assign_to.tsx
The condensed assignee chip now correctly has a background color and padding to the right.
Additionally, a bug was fixed for smaller screen sizes that caused the dropdown arrow of the chip to overflow.
Here's how it looks now:
[MM-44899](https://mattermost.atlassian.net/browse/MM-44899)
> [MM-44899] Fix assignee chip styling

- client/playbook_run.go
- client/playbook_runs.go
- server/api_runs_test.go
- server/app/playbook_run.go
- server/app/playbook_run_service.go
- server/main_test.go
- webapp/src/components/backstage/runs_list/filters.tsx
Honour PrivacySettings.ShowFullName value at getOwners endpoint.
Added client function and tests.
It's a bit surprising to get a nil value when is false from GetConfig() server calls, but it will be investigated separately.
Fixes https://mattermost.atlassian.net/browse/MM-48008
> respect fullname setting at getOwners

- server/app/playbook_run_service.go
Evolve run websocket approach:
- move all methods that are sending channel-broadcast to individual users messages
- remove channel based broadcast to avoid permissions/security issues (what if a member of the channel is not a run participant)
- optional parameters to enable adding more userIDs to be notified (like in add/moreve participants)
- avoid double getRun from database: sometimes we have an updated run and we can use it, the rest of the time we just get a fresh one.
Demo with two users that are participants but not channel members.
https://user-images.githubusercontent.com/4096774/202272512-fc0254a7-3377-48d1-a606-7f63bc182f81.mp4
Fixes https://mattermost.atlassian.net/browse/MM-48337
> WS updates run for non channel members

- webapp/src/components/checklist/generic_checklist.tsx
Addtask block now is inside droppable area, so drop is accessible even with no items inside.
Addtask is not dragable, and the behavior will be the same. tasks can not be dropped below addtask.
Approaches that I tried and didn't work:
- placeholder: is already in place and is only activated when you drag items from that list
- droppable.snapshot.isDraggingOver: did not trigger because droppable height was 0 
https://user-images.githubusercontent.com/4096774/202436165-4a295d7a-38fc-4c68-9a36-ac19f8f858f4.mp4
Fixes https://mattermost.atlassian.net/browse/MM-48309
> enable empty checklist as droppable are for tasks

- server/app/playbook_run_service.go
- tests-e2e/cypress/integration/channels/rhs/checklist_spec.js
If a task slash command uses `/playbook ...` which in turn modifies the run (e.g. `/playbook owner @username`), the update from that slash command gets overwritten by the code invoking the slash command to record the execution of same.
Fixes: https://mattermost.atlassian.net/browse/MM-48449
> MM-48449: avoid race with /playbook

- webapp/src/components/profile/profile_selector.tsx
If run participants don't come in first page of useProfilesInTeam, they won't be even displayed in the assignto/profileSelector (no matter ensureProfiles). Data is in redux but not in component.
Force retrieval from redux in profileSelector.
Fixes https://mattermost.atlassian.net/browse/MM-48514
> guarantee profiles load from redux for profileselector

- CODEOWNERS
`en.json` gets changed a lot. The initial i18n entries in CODEOWNERS only intended cover the i18n PRs, which only touch non-en.json files. CODEOWNERS [doesn't support negative patterns](https://git-scm.com/docs/gitattributes#:~:text=negative%20patterns%20are%20forbidden), so like https://github.com/NixOS/nixpkgs/pull/31758/files#diff-3d36a1bf06148bc6ba1ce2ed3d19de32ea708d955fed212c0d27c536f0bd4da7R86, we use @ghost to negate en.json.
|  before  |  after  |
|----|----|
| ![CleanShot 2022-11-21 at 11 35 00@2x](https://user-images.githubusercontent.com/11724372/203123117-d2bc70a7-0fb6-41b1-927c-4c5639da98e5.png) | ![CleanShot 2022-11-21 at 11 35 24@2x](https://user-images.githubusercontent.com/11724372/203123029-c4d46431-869c-479d-9b6f-e7c4b6339794.png) |
| ![CleanShot 2022-11-21 at 11 40 …
> Remove en.json from CODEOWNERS

- server/metrics/service.go
A recent version of golangci warns about a missing readtimeout on prometheus metricsserver.
Added timeout of 30s. I was tempted of using ServiceSettings.ReadTimeout but it seemed too large and for another purpose.
Nope
> add readtimeout to prometheus server

- webapp/src/components/backstage/playbook_editor/outline/outline.tsx
- webapp/src/components/backstage/playbook_editor/outline/section.tsx
- webapp/src/components/backstage/playbook_editor/outline/section_retrospective.tsx
- webapp/src/components/backstage/playbook_editor/outline/section_status_updates.tsx
- webapp/src/components/widgets/copy_link.tsx
The hover effects in the playbook outline are now more consistent.
Only section headers with a right header element are highlighted on hovering.
[MM-44807](https://mattermost.atlassian.net/browse/MM-44807)
> MM 44807 Adjust outline hover effects

- webapp/src/components/rhs/rhs_main.tsx
- webapp/src/components/rhs/rhs_run_list.tsx
Two runs list fixups.
- Remove owner from participants display. The run owner will no longer be displayed in the list of participants on the runs list card.
- Refetch when back clicked. This fixes the case where you finish the run (or change some other visible property) and navigate back to the runs list using the back button.
Fixes #1620
Fixes #1619
> Owner display and update on finish

- webapp/.eslintrc.json
- webapp/package-lock.json
- webapp/package.json
Warn if imports are relative.
bad
```ts
import {X} from '../module'
````
Good
```ts
import {X} from 'src/components/folder/module'
```
Motivations:
- Increase awareness on folder/context/parent-component
- Increase how easy is to refactor code from one module to another
- Increase how easy is to copy code from one module to another 
Also, at vscode autoimports can be configured as non-relative. 
Nope
> [Proposal] add eslint warning for relative imports

- server/api/graphql_root_run.go
- server/api/schema.graphqls
- server/api_graphql_runs_test.go
- server/app/playbook_run_service.go
- webapp/src/components/backstage/lhs_run_dot_menu.tsx
- webapp/src/graphql/generated_types.ts
- webapp/src/graphql/hooks.ts
- webapp/src/graphql/runs.graphql
- webapp/src/hooks/run.tsx
* Add new GraphQL mutation to fav/unfav a run
* Remove IsFavorite from UpdateRun mutation
* Add tests in server to test the new functionality
* Update schema
* Change webapp code to use the new mutation
Closes https://github.com/mattermost/mattermost-server/issues/21706
> Refactor code to move out fav/unfav from UpdateRun

- server/api/graphql_root_playbook.go
- server/api/graphql_run.go
- server/api/schema.graphqls
- webapp/src/components/rhs/rhs_run_list.tsx
- webapp/src/graphql/generated_types.ts
Make playbook retrieval optional for runs in GraphQL for the case where the user has permissions to the run but not the playbook that created it. 
Shows as blank in the RHS:
> Make playbook retrieval optional for case where user has no permissions.

- tests-e2e/cypress/integration/channels/rhs/header_spec.js
- webapp/src/client.ts
- webapp/src/components/rhs/rhs_about.tsx
The `update-description` endpoint no longer exists, and the e2e tests verifying the RHS run summary updates didn't reload the page to ensure the updates were persisted.
Fix the test and use the new GraphQL endpoint instead.
Fixes: https://mattermost.atlassian.net/browse/MM-48783
> MM-48783: Ensure run summary updates in RHS.

- webapp/src/components/rhs/rhs_main.tsx
- webapp/src/components/rhs/rhs_run_list.tsx
When opening Insights or Threads, there is no `currentChannelId`, and this can lead to a crash. Detect this early, and render the same screen we show when there has never been a run in the channel.
Fixes: https://mattermost.atlassian.net/browse/MM-48866
Fixes: https://mattermost.atlassian.net/browse/MM-48866
> MM-48866: avoid assuming current channel

- webapp/src/components/backstage/backstage.tsx
- webapp/src/components/login_hook.tsx
- webapp/src/components/rhs/rhs_main.tsx
- webapp/src/hooks/general.ts
- webapp/src/index.tsx
Plugin settings are needed, among other things, to handle feature flags.
When a user initializes app unlogged, settings call returns a 401 (obviously) and is not refetched anymore.
Added hook to ensure settings are fetched, if empty will retry the fetch. Triggered in two main points backstage and main rhs.
Fixes https://github.com/mattermost/mattermost-plugin-playbooks/issues/1644
> ensure settings are fetched after login

- server/api/settings.go
- server/api_settings_test.go
- tests-e2e/cypress/integration/api/settings_spec.js
Force the feature flag for linking multiple runs to a channel to be `true`, regardless of its actual setting. We'll rip this out altogether in an upcoming release.
Fixes: https://github.com/mattermost/mattermost-plugin-playbooks/issues/1656
> Force enable link run feature flag

- tests-e2e/cypress/integration/playbooks/overview_spec.js
- webapp/src/components/login_hook.tsx
- webapp/src/index.tsx
Move fetching roles to logged-in codepath to prevent repeat/infinite loop on login page.
- Fixes https://mattermost.atlassian.net/browse/MM-48888
> MM-48888: Infinite loop on fetching roles when logging out

- tests-e2e/cypress/integration/playbooks/start_run_spec.js
- webapp/src/components/modals/new_run_playbook_modal.tsx
This PR fixes an issue with an empty default owner. If the playbook was set to assign the default owner, but the owner value was empty, the `new run playbook modal` set an empty text as an owner id. Because of that, a run start was failing. 
No task
> Fix empty default owner issue

- server/api/playbook_runs.go
govet is complainig about two blocks of errs being checked twice
```
server/api/playbook_runs.go:650:9: nilness: impossible condition: nil != nil (govet)
if err != nil {
^
server/api/playbook_runs.go:1001:9: nilness: impossible condition: nil != nil (govet)
if err != nil {
```
One of them is treated as 400 and 500 error, I kept the 400 but 0/5 on that
No
> remove double check of errs

- tests-e2e/cypress/integration/runs/list_spec.js
- tests-e2e/cypress/integration/runs/permissions_spec.js
- webapp/src/components/backstage/runs_page.tsx
"My Runs Only" is disabled by default when visiting run lsit
Fixes https://github.com/mattermost/mattermost-plugin-playbooks/issues/1670
> make view all runs the default filter at run list

- webapp/src/components/backstage/playbook_edit/automation/auto_assign_owner.tsx
- webapp/src/components/backstage/playbook_edit/automation/categorize_playbook_run.tsx
- webapp/src/components/backstage/playbook_edit/automation/channel_access.tsx
- webapp/src/components/backstage/playbook_edit/automation/invite_users.tsx
- webapp/src/components/backstage/playbook_edit/automation/styles.tsx
- webapp/src/components/backstage/playbook_edit/automation/toggle.tsx
- webapp/src/components/backstage/playbook_edit/automation/webhook_setting.tsx
- webapp/src/components/backstage/playbook_editor/outline/section_actions.tsx
- webapp/src/components/modals/new_run_playbook_modal.tsx
- webapp/src/components/modals/run_playbook_modal.tsx
Makes configuration labels clickable by changing sibling to labels and using `for` with a reference to the respective input. 
[Screencast from 09.12.2022 15:09:38.webm](https://user-images.githubusercontent.com/8669935/206720881-2db6cf6e-dd56-48fa-9cf4-5b71890451bd.webm)
fixes #1667
> 1667  Make run configuration labels clickable

- webapp/src/components/playbooks_selector.tsx
Add a loading indicator to the new playbook run modal. 
I could only reproduce the long loading times that are mentioned in the issue by manually throttling the connection.
[Screencast from 15.12.2022 17:46:06.webm](https://user-images.githubusercontent.com/8669935/207919524-f4614d2d-95c5-45e5-8aee-8ff711aaedbb.webm)
Fixes #1681
> 1681 Add loading indicator to new playbook run modal

- tests-e2e/cypress/integration/channels/rhs_spec.js
- webapp/src/components/rhs/rhs_home_item.tsx
- webapp/src/rhs_opener.ts
Adds a check to ensure we're viewing a channel before opening RHS. `currentChannelId` can sometimes have a value even though you're not in a channel. 
- Fixes: #1676 
- ~[ ] Telemetry updated~
- ~[ ] Gated by experimental feature flag~
>  GH-1676: only open rhs when in a channel

- assets/i18n/en.json
- server/api/playbook_runs.go
- server/app/playbook_run.go
- server/app/playbook_run_service.go
- server/command/command.go
Changed all hard-coded strings of the interactive dialogs related to playbook runs in the backend to use the i18n translated string instead.
This means, that the following dialogs can now be translated to the user's locale:
-  AddChecklistItemDialog - `/playbook checkadd 0 0`
- FinishPlaybookRunDialog - `/playbook finish 0`
- PlaybookRunDialog - `/playbook run`
- UpdatePlaybookRunDialog - `/playbook update 0`
- AddToTimelineDialog
[MM-48917](https://mattermost.atlassian.net/browse/MM-48917)
> MM-48917 Make interactive playbook run dialogs translatable

- tests-e2e/cypress/integration/channels/rhs_spec.js
- tests-e2e/cypress/integration/playbooks/overview_spec.js
In `mm webapp`, a couple of button labels were changed, and it caused some e2e tests to fail. This PR updates labels in e2e tests.
NONE
> Fix e2e tests

- tests-e2e/cypress/integration/playbooks/start_run_spec.js
- webapp/i18n/en.json
- webapp/src/components/assets/inputs.tsx
- webapp/src/components/modals/new_run_playbook_modal.tsx
- webapp/src/constants.ts
Implement visual feedback when a run name is invalid. A detailed error message will be shown in that case. 
Currently, it will only be checked if the run name exceeds 64 characters.
[Screencast from 21.12.2022 15:18:00.webm](https://user-images.githubusercontent.com/8669935/208926553-743590ef-30c8-485b-9d40-07fa01476cb1.webm)
[MM-46983](https://mattermost.atlassian.net/browse/MM-46983)
> MM-46983 Visual feedback for invalid run names

- webapp/src/components/run_actions_modal.tsx
The run actions modal did not show the correct data when changing runs.
This was caused because `useState` does not use the provided initial state if the component has mounted with a state already which is the case here, when the first run is visited. 
To avoid this issue, all states will be synced when the run changes.
[Screencast from 04.01.2023 15:49:45.webm](https://user-images.githubusercontent.com/8669935/210581554-ca316de4-49b3-4e6e-bc15-c6f7e697b954.webm)
[MM-48600](https://mattermost.atlassian.net/browse/MM-48600)
[MM-48600]: https://mattermost.atlassian.net/browse/MM-48600?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MM-48600 Fix run actions modal not updating state when changing run

- webapp/src/components/backstage/toast.tsx
- webapp/src/components/backstage/toast_banner.tsx
- webapp/src/components/rhs/rhs_run_details.tsx
Increased the duration the toast for participating in a run is shown from 3 to 4.5 seconds. 
Additionally, toasts will not be hidden while hovered. 
[Screencast from 04.01.2023 17:54:43.webm](https://user-images.githubusercontent.com/8669935/210608030-39b7800e-5c77-49de-91b0-652c250313be.webm)
[MM-48599](https://mattermost.atlassian.net/browse/MM-48599)
[MM-48599]: https://mattermost.atlassian.net/browse/MM-48599?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MM-48599 Improve toast for participating in a run and toasts in general

- tests-e2e/cypress/integration/playbooks/edit_spec.js
- tests-e2e/cypress/integration/runs/rdp_main_retrospective_spec.js
- webapp/src/components/backstage/playbook_runs/playbook_run/retrospective.tsx
- webapp/src/components/backstage/profile_autocomplete.tsx
- webapp/src/components/backstage/runs_list/filters.tsx
- webapp/src/components/datetime_input.tsx
- webapp/src/components/datetime_selector.tsx
- webapp/src/components/rhs/rhs_run_list.tsx
- webapp/src/components/widgets/text_with_tooltip.tsx
- webapp/src/hooks/crud.ts
- webapp/src/hooks/general.ts
`debounce` requires memoization, otherwise every component re-render recreates the debouncing function. We change some existing, memoized instances of `debounce` using `useCallback` to use `useMemo` primarily to address (es)linting issues.
While I'm in here, fix an instance of `should('not.be.visible')` to be `should('not.exist')` that failed a recent CI run -- see https://docs.cypress.io/guides/references/migration-guide#Non-existent-element-assertions.
Fixes: https://mattermost.atlassian.net/browse/MM-48509
> useMemo with debounce

- .golangci.yml
- Makefile
- server/app/playbook_run_service.go
Some MacOS users (@jecepeda and I for example) can not run `make check-style` since golangci is broken after Ventura upgrade.
Apparently the native diff is not compatible with some time format used by `gofmt diff`.
More info https://github.com/golangci/golangci-lint/issues/3402, https://github.com/golangci/golangci-lint/issues/3087 and https://github.com/golangci/golangci-lint/issues/3375
```
/Users/jpeso/code/mattermost-plugin-playbooks/bin/golangci-lint run ./...
level=warning msg="[runner] Can't run linter goanalysis_metalinter: gofmt: can't extract issues from gofmt diff output \"--- /Users/jpeso/code/mattermost-plugin-playbooks/server/manifest.go.orig\\t2023-01-13 16:25:14\\n+++ /Users/jpeso/code/mattermost-plugin-playbooks/server/manifest.go\\t2023-01-13 16:25:14\\n@@ -3,8 +3,8 …
```
> force golangci to recent commit to solve macos issue

- tests-e2e/cypress/support/api/preference.js
Set tutotial point for draft as viewed in e2e tests.
No
> set to true tutorial point for drafts in e2e

- .circleci/config.yml
- client/go.mod
- go.mod
Update plugin to go1.19
server and focalboard have been updated to 1.19, do it here as well
No
> update go to 1.19

- server/api/graphql.go
- server/api_graphql_runs_test.go
Errors of the form:
```
error [2023-01-24 10:19:15.485 -08:00] Error executing request                       caller="app/plugin_api.go:976" plugin_id=playbooks error="graphql: Cannot query field "id" on type "RunConnection". (line 8, column 5)" operation=PlaybookLHS request_id=mqdpw6c3ntynfbi4qquazt59xc plugin_caller="github.com/mattermost/mattermost-plugin-playbooks/server/api/graphql.go:159"
```
where appearing in production systems where playbooks was upgraded as old clients where trying to make requests for fields that had been removed.
Downgrading the warning to an error and changing the text to be more specific will allow the reduction of noise errors in production. These errors will now be of the form:
```
warn  [2023-01-24 10:48:20.503 -08:00] Query for non existent field …
```
> Downgrade field missing errors to warnings for logging.

- server/api/signal.go
- server/app/action.go
- server/app/actions_service.go
- server/app/playbook_run.go
- server/app/playbook_run_service.go
- server/app/urls.go
- server/command/command.go
- server/plugin.go
- tests-e2e/cypress/integration/channels/run_dialog_spec.js
The impetus for this change was to find and eliminate the source of the following ERROR logs in production:
> GetSessionByld: We encountered an error finding the session.
and logging a blank `sessionID`. The code in question was our `MessageHasBeenPosted` hook handler, which assumed that all messages posted had come from an active session. But this isn't the case for bots, to which the actions service intentionally wanted to respond.
Upon examining how the fetched session was used, I realized it was only to suppress one line in the `/playbook run` modal that linked to the Playbooks product as a way of explaining how to create a playbook:
As this functionality is not available on mobile, the message made no sense, so we attempted to suppress it in that case:
Unfortunately, the suppression …
> Avoid spurious session errors

- server/api/playbook_runs.go
- server/api_runs_test.go
- server/app/permissions_service.go
Revert https://github.com/mattermost/mattermost-plugin-playbooks/pull/1554
Allow run participants to post updates without checking permissions on every channel configured for broadcast.
Fixes https://github.com/mattermost/mattermost-plugin-playbooks/issues/1690
> revert #1554 - allow run participants to post update 

- tests-e2e/cypress/integration/channels/rhs/header_spec.js
- tests-e2e/cypress/integration/runs/rdp_main_summary_spec.js
- webapp/src/components/backstage/playbook_runs/playbook_run/checklists.tsx
- webapp/src/components/backstage/playbook_runs/playbook_run/summary.tsx
- webapp/src/components/checklist/checklist_list.tsx
- webapp/src/components/checklist/generic_checklist.tsx
- webapp/src/components/checklist_item/checklist_item.tsx
- webapp/src/components/checklist_item/checklist_item_draggable.tsx
- webapp/src/components/checklist_item/inputs.tsx
- webapp/src/components/rhs/rhs_checklist_list.tsx
- webapp/src/components/rhs/rhs_run_details.tsx
This is a client-side only change to disable the functionality for editing a run summary after a run has finished. The GraphQL endpoint currently seems to allow edits regardless, and I didn't want to tackle locking that down here.
Fixes: https://mattermost.atlassian.net/browse/MM-49791
> MM-49791: Disable edit summary after run finished

- client/playbook_runs.go
- server/api_runs_test.go
- server/app/playbook_run_service.go
Set again the lastCommandRunAt to 0 when the command is updated (with a different command). The goal is to avoid the situation where we have a command with "Rerun" label in UI and timestamp in DB but the command that was run is another different previous one.
The history for the first command is still kept in the timeline. We don't store in the timeline which task triggered the slash command, but we still don't have task ids anyway.
Added tests for SetCommand and RunCommand that were missing (+ client functions).
Fixes https://github.com/mattermost/mattermost-plugin-playbooks/issues/1760
> reset commandLastRunAt when command is updated

- webapp/src/components/sidebar/playbooks_sidebar.tsx
The desktop app loads playbooks in the background on startup and has the LHS visible. This will cause the polling for LHS updates to run in the background which is not desired. 
This patch attempts to mitigate this by only polling when the LHS is actually in focus.
> When focus is lost on LHS stop polling

- webapp/src/components/channel_actions_modal.tsx
Extracted from https://github.com/mattermost/mattermost-plugin-playbooks/pull/1748. The rest of the original PR is being discussed more in-depth.
**/plugins/playbooks/api/v0/actions/channels/**
Make channel actions modal fetch action ONLY when is shown, not when it's rendered but hidden. Before this change, channel actions were fetched on every channel switch.
Fixes (partially) #1731
> make get actions trigger just if modal is shown

- tests-e2e/cypress/integration/channels/rhs/start_run_rhs_spec.js
- tests-e2e/cypress/integration/playbooks/start_run_spec.js
- webapp/src/components/modals/run_playbook_modal.tsx
If a playbook defaults to "Create a run channel" and "Link run to an existing channel" is chosen, the default channel will be the current one instead of none.
Fixes #1767
> GH-1767 Default to current channel when linking a new playbook run

- webapp/src/components/modals/run_playbook_modal.tsx
When the internet of the user or the server is slow, it is possible to start multiple runs at once by clicking the "Start run" button multiple times. The "Start run" button is now disabled while the client is waiting for the response from the server.
[Screencast from 01.02.2023 16:06:50.webm](https://user-images.githubusercontent.com/8669935/216080548-7966b752-3c38-49b2-ae8d-b2c19d471e47.webm)
Fixes #1773
> GH-1773 Fix potential duplicate runs

- webapp/src/components/templates/template_data.test.ts
I didn't really want to do this PR but this is how it is 😬 Because this is kind of a "first", I opened a thread here: [community.mattermost.com/core/pl/t7d16sx83tnw7phhh8bp9h844a](https://community.mattermost.com/core/pl/t7d16sx83tnw7phhh8bp9h844a)
Work templates rely on the fact that certain playbook templates exist, but we have no way to guarantee this on the mattermost-server/webapp side. This test acts as a warning that something might break in work templates because a templates has been renamed/removed.
N/A
N/A
> Add a test to help detect potential sync issues with work template

- .github/workflows/cd.yaml
Fixed release notes path
Fix duplicate package on Github Release that makes matterbuild fail . 
Relevant [line](https://github.com/mattermost/matterbuild/blob/59f5f2df3571c981871ed21cf78a420d1934e539/server/plugin_release.go#L590)
> hotfix(release): Remove latest package publish for matterbuild to work .

- webapp/webpack.config.js
The errors that we were seeing where either Boards or Playbooks were failing to load when they were both loaded at the same time seems like it was happening due to an issue with the resolution of shared modules by module federation. Specifically, it seems to be due to how it was trying to choose which version of those shared modules to use between the ones bundled with the web app, Boards, and Playbooks.
Since I've been trying to make the web app the authority for these dependencies, I just changed it so that the Playbooks build will never include "fallback" versions of React and such since we know they'll always exist in the web app.
https://mattermost.atlassian.net/browse/MM-50818
https://github.com/mattermost/focalboard/pull/4605 …
> MM-50818 Fix module loading issues caused by shared modules

- webapp/src/components/checklist_item/command.tsx
- webapp/src/constants.ts
- webapp/src/utils.ts
PR adds support for running Calls slash commands from Playbooks checklist items. The change on this side is minimal as we are simply sending a client event to trigger the handler on the Calls side (see related PR below). Let me know if it makes sense.
https://github.com/mattermost/mattermost-plugin-calls/pull/343
https://user-images.githubusercontent.com/1832946/220467796-65bf1711-7dec-4459-af2a-333058140fdb.mp4
https://mattermost.atlassian.net/browse/MM-50623
> [MM-50623] Add support for Calls slash commands

- server/api/playbook_runs.go
- server/api/signal.go
- server/app/actions_service.go
- server/app/playbook_run.go
- server/app/playbook_run_service.go
- server/command/command.go
Removes the editing of the keyword prompt action post and instead deletes it, leaving the notifications of run creation to the regular channels. 
https://mattermost.atlassian.net/browse/MM-50738
> MM-50738 Remove keyword prompt post instead of editing it.

- README.md
Update the README to reflect that this repository is now obsolete.
Preview at https://github.com/mattermost/mattermost-plugin-playbooks/tree/obsolete-readme.
> update README to reflect repository being obsoleted

- README.md
Reverts mattermost/mattermost-plugin-playbooks#1843
Playbooks is moving back to a plugin: https://mattermost.atlassian.net/browse/MM-53155
> Revert "update README to reflect repository being obsoleted"

- .github/workflows/cd.yaml
We are currently using the scheme: `${GITHUB_REPOSITORY#*/}-${GITHUB_REF_NAME}.tar.gz` to name the playbook-plugin artifact, in the CD process. 
CircleCI pipelines used the following naming scheme: `${GITHUB_REF_NAME}.tar.gz`
Previous CircleCI release example: https://github.com/mattermost/mattermost-plugin-playbooks/releases/tag/v1.36.2
We are aligning with the previous naming scheme.
Ticket: https://mattermost.atlassian.net/browse/CLD-5870
> [fix] CD revisiting naming for artifacts generated

- .github/workflows/ci.yaml
- server/app/playbook_run_service.go
Instead of erroring out on `/playbook todo` or the weekly digest message, just log a warning when a user's timezone isn't recognized:
```
{"timestamp":"2023-07-21 14:03:56.435 -03:00","level":"warn","msg":"failed to get user timezone","caller":"app/plugin_api.go:979","plugin_id":"playbooks","error":"unknown time zone Asia/Jerusalem2","user_id":"soa5qdiwnig8dkmekej37p8gmw","plugin_caller":"github.com/mattermost/mattermost-plugin-playbooks/server/app/playbook_run_service.go:2262"}
```
In practice, this won't occur because the timezone is really invalid, but because the operating system lacks the necessary tzdata.
None.
> Warn instead of Error on unrecognized user tz

- build/custom.mk
- server/plugin.go
For now, we're just hard-coding this while still honouring the server configuration as to whether or not to emit telemetry in the first place.
In the future, we should integrate knowledge of the service environment and use that to key off which key (if any) to use.
None.
> restore the missing Plugin telemetry key

- server/api/actions.go
- server/api/playbook_runs.go
- server/api_actions_test.go
- server/app/playbook_run.go
- server/app/playbook_run_service.go
https://mattermost.atlassian.net/browse/MM-54130
https://mattermost.atlassian.net/browse/MM-54149
https://mattermost.atlassian.net/browse/MM-54151
> MM-54130 MM-54149 MM-54151 Fix validation

- server/api_runs_test.go
- server/sqlstore/playbook.go
- server/sqlstore/playbook_run.go
- server/sqlstore/user_info.go
Turns out that if you wrap a nil error it returns nil instead of a new error. We were using Wrapf when we meant Errorf leading to a function returning (`nil`, `nil`) instead of (`nil`, `error`) as intended.
> MM-53753 Fix error messages for too long json

- server/api/graphql.go
- server/api/graphql_loader_run.go
- server/api/graphql_root_run.go
- server/api/graphql_run.go
- server/api_graphql_runs_test.go
- server/app/playbook_run.go
- server/plugin.go
- server/sqlstore/playbook_run.go
- webapp/src/graphql/generated/graphql.ts
- webapp/src/index.tsx
- webapp/src/rhs_opener.ts
Migrates the RHS opener logic to GraphQL to reduce the overhead of fetching all the runs on the team. We where fetching all the data on each run when all we really needed was if there was an active run in the channel.
Status posts, timeline events, and metrics where set behind an option that GraphQL excludes and fetches separately itself if requested. 
This came up because a customer was encountering the `getTimelineEventsForPlaybookRun` subquery executing with near 1000 runs. This appears to be the only situation outside of having 1000 runs in a channel that this could happen.
> Move RHS opener to GraphQL

- tests-e2e/cypress/integration/channels/rhs_spec.js
- webapp/src/rhs_opener.ts
> MM-54364: backport playbooks 1.36 -> mattermost 7.8 ESR

- server/plugin.go
Not closing the store would keep DB connections open,
allowing them to remain in the server connection pool.
https://mattermost.atlassian.net/browse/MM-56402
> MM-56402: Close the store on Deactivate

- server/api_runs_test.go
- server/app/playbook_run_service.go
Fix promotion of channel members when attaching a playbook run to an existing channel.
https://mattermost.atlassian.net/browse/MM-56041
> Fix run channel attachment promotion

- server/plugin.go
Adding `time/tzdata` as import for systems and docker images without tzdata installed.
> Adding time/tzdata for systems without tzdata installed.

- e2e-tests/tests/integration/playbooks/runs/rdp_rhs_runinfo_spec.js
- server/app/playbook_run_service.go
- webapp/i18n/en.json
- webapp/src/components/backstage/playbook_runs/playbook_run/playbook_run.tsx
- webapp/src/components/backstage/playbook_runs/playbook_run/rhs_info.tsx
- webapp/src/components/backstage/playbook_runs/playbook_run/rhs_info_overview.tsx
This PR allows for a run page to be visited even if the associated channel has been removed.
https://mattermost.atlassian.net/browse/MM-47629
> [MM-47629] Don't crash when a run channel has been deleted

- webapp/src/components/markdown_textbox.tsx
All the Textboxes in playbooks were displaying a live preview,, it was not a desired behavior. I guess something changed in Mattermost's textbox causing this issue to appear.
[MM-55473](https://mattermost.atlassian.net/browse/MM-55473)
[MM-55473]: https://mattermost.atlassian.net/browse/MM-55473?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MM-55473] Hide preview box if not in preview mode

- webapp/src/components/backstage/metrics/metrics_row.tsx
- webapp/src/components/formatted_duration.test.tsx
- webapp/src/components/formatted_duration.tsx
Add support for negative durations into the duration formatting
https://mattermost.atlassian.net/browse/MM-58234
> [MM-58234] Support negative duration

- e2e-tests/tests/integration/playbooks/api/graphql_errors_spec.js
- server/api/graphql.go
- server/api_graphql_runs_test.go
Restrict how much error we display and log on Graphql requests.
https://mattermost.atlassian.net/browse/MM-58791
> [MM-58791] Restrict graphql errors

- go.mod
- server/api_playbooks_test.go
- server/main_test.go
- server/plugin.go
Add license check when starting playbooks if the version is 2.0+
Also see the Mattermost PR: https://github.com/mattermost/mattermost/pull/27335
Note: there is another ticket for cleaning up all the license checks for pro and enterprise:  https://mattermost.atlassian.net/browse/MM-58700
https://mattermost.atlassian.net/browse/MM-58377
> [MM-58377] Make sure we have an enterprise license when activating the plugin

- webapp/src/components/rhs/rhs_checklist_list.tsx
Fixed issue with the hover state on the checklist area where the title background was set and preventing the hover background from showing through. 
| Before | After |
| --- | --- |
| <img width="474" alt="image" src="https://github.com/mattermost/mattermost-plugin-playbooks/assets/2040554/a8ee2521-8e38-4157-b2c4-c9ebeb5c2ff6"> | <img width="481" alt="image" src="https://github.com/mattermost/mattermost-plugin-playbooks/assets/2040554/6657b3be-2e27-4712-b4f3-f41db79564fe"> |
Fixes: https://mattermost.atlassian.net/browse/MM-48603
> MM-48603 Fixed RHS hover styling on checklist area

- webapp/src/components/sidebar/sidebar.tsx
Fixed an issue in the sidebar where long team names wrapped on multiple lines and displayed poorly.
| Before | After |
| --- | --- |
| <img width="306" alt="image" src="https://github.com/mattermost/mattermost-plugin-playbooks/assets/2040554/ea5a77eb-1f76-4afb-a9b0-614a95a8f5ad"> | <img width="307" alt="image" src="https://github.com/mattermost/mattermost-plugin-playbooks/assets/2040554/ead7347f-308f-4d48-b100-b9cd4944b703"> |
Fixes https://mattermost.atlassian.net/browse/MM-48411
> MM-48411 Fixed truncation on long team names

- webapp/src/components/checklist/checklist_list.tsx
- webapp/src/components/checklist/collapsible_checklist.tsx
- webapp/src/components/rhs/rhs_checklist_list.tsx
Reverts mattermost/mattermost-plugin-playbooks#1926
See https://mattermost.atlassian.net/browse/MM-60057
Did not find a way to quickly fix the underlying ticket, but this change results in a more degraded UI and we need to revert this for the v10 release!
> Revert "MM-48603 Fixed RHS hover styling on checklist area"

- Makefile
We added `DEFAULT_GOOS` and `DEFAULT_GOARCH` a while back so it was easy to cross compile for a quick deploy, e.g.:
```sh
export MM_SERVICESETTINGS_ENABLEDEVELOPER=true 
export MM_DEBUG= 
export DEFAULT_GOOS=linux 
export DEFAULT_GOARCH=amd64 
make dist 
```
Somehow or another, this was just done wrong. I need to fix this "upstream" in the starter template too.
None
> fix DEFAULT_* handling

- server/sqlstore/playbook_run.go
- server/sqlstore/playbook_run_test.go
- server/sqlstore/stats.go
- server/sqlstore/stats_test.go
In support of the MS Teams Tab App, and to unlock other security workflows involving bot participation in runs, let's allow bots to be participants of playbook runs.
Fixes: https://mattermost.atlassian.net/browse/MM-60420
> MM-60420: treat bots as participants

- webapp/src/components/backstage/playbook_runs/playbook_run/add_participant_modal.tsx
- webapp/src/components/widgets/generic_modal.tsx
Fixes https://github.com/mattermost/mattermost/issues/27537
Jira https://mattermost.atlassian.net/browse/MM-58182
Before Screenshot:- 
After Screenshot:-
> Add participant modal footer alignment fix

- .github/workflows/ci.yaml
> fix: Revert testing to free runners

- .gitignore
- webapp/src/components/pagination_row.tsx
The PaginationRow components didn't have any margin and the next/previous buttons where to close to the border
[MM-61918](https://mattermost.atlassian.net/browse/MM-61918)
[MM-61918]: https://mattermost.atlassian.net/browse/MM-61918?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Add horizontal margins to PaginationRow component

- webapp/src/components/retrospective_post.tsx
- webapp/src/utils.ts
Validate props in the retrospective post
https://mattermost.atlassian.net/browse/MM-61164
> Validate props in retrospective post (aider assisted)

- server/api/tabapp.go
- server/api/tabapp_test.go
- server/api_tabapp_test.go
Require the `ServiceSettings.EnableDeveloper` and `ServiceSettings.EnableTesting` flags to allow local development mode that doesn't enforce JWT validation.
None
> combine EnableDeveloper and EnableTesting

- e2e-tests/tests/integration/playbooks/runs/rdp_rhs_runinfo_spec.js
- e2e-tests/tests/support/api/cloud_default_config.json
- e2e-tests/tests/support/api/on_prem_default_config.json
Remove deprecated `ExperimentalViewArchivedChannels` setting from e2e test configuration files. This setting has been deprecated by Mattermost and should no longer be used. This will fix the CI.
No ticket - cleanup of deprecated configuration setting
> Remove deprecated ExperimentalViewArchivedChannels from e2e test configs

- e2e-tests/tests/support/ui/playbooks.js
- plugin.json
- webapp/src/components/post_menu.tsx
- webapp/src/index.tsx
- Replace deprecated `registerPostDropdownMenuComponent` with `registerPostDropdownMenuAction`
- Move text labels and action/filter into webapp/src/components/post_menu.tsx
- Add `makeStartPlaybookRunAction` and `makeAttachToPlaybookRunAction`
- DRY filter with `shouldShowPostMenuForPost` returning strict boolean
- Simplify webapp/src/index.tsx to always register actions (min server bumped)
- Remove deprecated component-based post menu items
- Cleanup unused imports
**Note* this also bumps `min_server_version` to 7.10 to ensure we have `registerPostDropdownMenuAction`
https://mattermost.atlassian.net/browse/MM-65008
> MM-65008: migrate post menu to registerPostDropdownMenuAction

- server/api/graphql_root_run.go
- server/app/playbook_run.go
- server/app/playbook_run_service.go
When we add a new participant because we added a owner or assignee from outside of the run, we were sending two different websocket events with the same update at:
- One for adding the participant
- One for setting the assignee
This makes sure only one websocket is sent in this scenario.
Fix https://mattermost.atlassian.net/browse/MM-65176
> Fix double websocket when changing owner or assignee

- server/app/playbook_run_service.go
When an update would happen to a playbook run, the fields would disappear from the screen.
https://mattermost.atlassian.net/browse/MM-65692
- Create playbook with properties
- Start a run
- Rename the run
- The properties should still be visible on the page.
> Fix websocket not returning properties

- webapp/src/license.test.ts
- webapp/src/license.ts
Fixes frontend license validation functions to properly support the 'entry' SKU type.
Note that the backend works as expected and relies on Mattermost's "number" for the license (0 for free, 10 for pro...); So we overlooked the fact that the frontend would use a different system: the SkuShortName.
And because playbooks works "as licensed" if your setup has dev mode and debug mode turned on (which we do locally and on test server), we missed this.
https://mattermost.atlassian.net/browse/MM-65748
> MM-65748: License validation missing support for 'entry' SKU type

- plugin.json
Updates the minimum required Mattermost server version from 7.10.0 to 11.0.0 in plugin.json.
This is required because of the new plugin apis we use for properties.
Part of the Mattermost version requirement update initiative.
> bump minimum mattermost version to 11.0.0

- server/api/graphql_run.go
- server/api/graphql_run_test.go
- webapp/i18n/en.json
- webapp/src/components/checklist/collapsible_checklist.tsx
- webapp/src/components/checklist_item/checklist_item.tsx
- webapp/src/components/checklist_item/condition_indicator.test.tsx
- webapp/src/components/checklist_item/condition_indicator.tsx
- webapp/src/components/rhs/rhs_checklist_list.tsx
Adds UI support for conditional checklist items by filtering out hidden items from display and adding visual indicators to show when items have conditions applied.
Blocked by #2089 
https://mattermost.atlassian.net/browse/MM-65159
> [MM-65159] Add UI support for hiding checklist items with condition
