mattermost/mattermost-plugin-playbooks

.circleci/config.yml
server/incident/incident.go
server/playbook/filter_options.go
server/playbook/playbook.go
server/playbook/service.go
server/sqlstore/data_migration.go
server/sqlstore/incident.go
server/sqlstore/incident_test.go
server/sqlstore/migrate.go
server/sqlstore/migrations.go
server/sqlstore/playbook.go
server/sqlstore/playbook_test.go
server/sqlstore/store.go
server/sqlstore/support_for_test.go

- tests the playbook store
- Adds descriptions to incident and migrates them (https://mattermost.atlassian.net/browse/MM-28316)
- Add descriptions to playbooks and migrates them (https://mattermost.atlassian.net/browse/MM-28292)
- https://mattermost.atlassian.net/browse/MM-27006
- https://mattermost.atlassian.net/browse/MM-28316
- https://mattermost.atlassian.net/browse/MM-28292

MM-27006 - Unit test the playbook store

---

tests-e2e/cypress/integration/backstage/incident_list_spec.js
tests-e2e/cypress/support/ui_commands.js
tests-e2e/package-lock.json
tests-e2e/package.json
webapp/src/components/backstage/incidents/incident_details/incident_details.tsx

- it's tough to use class names as we move to styled-components, so I'm proposing to put 'data-testid' tags on any element we want to reference
- https://mattermost.atlassian.net/browse/MM-28448

MM-28448 - Fix cypress test

---

webapp/src/components/assets/icons/warning_icon.tsx

- before (same for not-found incident):
- after:
- https://mattermost.atlassian.net/browse/MM-28621

MM-28621 - "Incident" & "Playbook Not Found" image in backstage don't render properly

---

webapp/src/components/checklist.scss

- Before:
- After:
- https://mattermost.atlassian.net/browse/MM-28174

MM-28174 - Wrap task labels

---

tests-e2e/cypress/integration/frontstage/incident_rhs_list_spec.js
webapp/src/components/assets/icons/dot_menu_icon.tsx
webapp/src/components/assets/icons/three_dots_icon.tsx
webapp/src/components/backstage/playbook.scss
webapp/src/components/backstage/playbook_list.tsx
webapp/src/components/dot_menu.tsx
webapp/src/components/rhs/incident_details.tsx
webapp/src/components/rhs/rhs_list_view.tsx

- Does what it says, uses same dimensions as all the other UI button hovers
- Some alignment fixes
- https://mattermost.atlassian.net/browse/MM-29482

MM-29482 - Add button hovers on triple dots

---

tests-e2e/cypress/integration/frontstage/incident_creation_spec.js
tests-e2e/cypress/integration/frontstage/incident_rhs_list_spec.js
tests-e2e/cypress/support/plugin_api_commands.js

- Adding a wait to fix a race
- See https://mattermost.atlassian.net/browse/MM-29617 for a description of what was happening
- Renamed a cypress function (sorry for the noise)
- https://mattermost.atlassian.net/browse/MM-29606

MM-29606 - Fix flaky RHS list spec

---

webapp/src/client.ts

I changed a bit too much in #325, including the URL to channel export plugin. This PR reverts that change.
--

Revert change in channel export path

---

client/go.mod
go.mod

Uses replace directives for the new local module. Should fix the issues in #290

Use replace for local modules.

---

go.mod
go.sum
server/api/incidents.go
server/api/incidents_test.go
server/api/playbooks.go
server/api/playbooks_test.go
server/command/command.go
server/incident/incident.go
server/incident/mocks/mock_service.go
server/incident/service.go
server/incident/service_test.go
server/playbook/mocks/mock_service.go
server/playbook/playbook.go
server/playbook/service.go
server/telemetry/noop.go
server/telemetry/rudder.go
server/telemetry/rudder_test.go

- Does what it says.
- Couldn't fix all of Eric's problems in https://docs.google.com/document/d/1X7VK9El-WjXKzsQY8CVzcOmATkodIjtFBXWpUuESfoI/edit# . Will see if the next ticket can do it.
- https://mattermost.atlassian.net/browse/MM-29720

MM-29720 - Consistently track Mattermost User ID aross telemetry events

---

docs/SUMMARY.md
docs/administrator-guide/installation-and-activation.md

Added installation steps for admins.
@itao: I wasn't able to test the cloud activation steps; if you could validate that would be awesome.

Admin Installation Steps

---

webapp/src/client.ts

- We were trying to fetch json, but the update endpoint is now returning nothing.
- Fixing that, and a bunch of other little mistakes we were making in the client file. We probably need to clean `client.ts` up a bit, but leaving that for next version.
- https://mattermost.atlassian.net/browse/MM-30135

MM-30135 - Fix: Playbook update in 1.1 is a bit broken

---

.circleci/config.yml
tests-e2e/cypress/integration/backstage/playbook_creation_spec.js
webapp/src/components/backstage/template_selector.tsx
webapp/src/components/rhs/rhs_welcome_view.tsx

- Does what it says
- https://mattermost.atlassian.net/browse/MM-30166

MM-30166 - Rename playbook to incident management

---

webapp/src/components/duration.tsx
webapp/src/components/rhs/rhs_incident_summary.tsx
webapp/src/components/rhs/rhs_list_view.tsx

- Add last updated line in rhs shortlist
- Looks like:
https://mattermost.atlassian.net/browse/MM-29712

MM-29712 - "Last updated" time in RHS Incident list view

---

server/api/incidents.go
webapp/src/client.ts

- `doPut` was expecting something back from these endpoints, so it was throwing a JSON parsing error.
- https://mattermost.atlassian.net/browse/MM-30262

MM-30262 - Checking and unchecking the checklist items throws JS error

---

webapp/src/components/backstage/playbook_edit.tsx
webapp/src/components/tabs.tsx

Adds preferences tab to playbook edit. Preferences page is just a placeholder. 
Also changed the titles in the "Permissions" sidebar to their new names. 
Screenshot:
https://mattermost.atlassian.net/browse/MM-30518

MM30518 Adding preferences tab to playbook edit.

---

server/command/command.go
tests-e2e/cypress/integration/frontstage/slash_command/info_spec.js

Updated the ephemeral message in command.go
Fixes: https://github.com/mattermost/mattermost-server/issues/16400
JIRA: https://mattermost.atlassian.net/browse/MM-29685

[MM-29685]: Change text of the ephemeral message in command.go

---

tests-e2e/cypress/integration/frontstage/incident_rhs_list_spec.js

- Logging out and logging back in with cypress is very annoying, I don't think it's working like I think it's working. So doing other things so we don't have to do that.
- none

Fixing flaky e2e tests

---

server/incident/incident.go
server/incident/incident_test.go
server/incident/service.go
server/sqlstore/incident.go
server/sqlstore/migrations.go
tests-e2e/cypress/integration/frontstage/rhs/latest_update_spec.js
tests-e2e/cypress/support/ui_commands.js

- Added a SQL column, migrations, pretty simple to put the reminder as the default. 
- Added e2e tests for it so Prapti doesn't have to do it.
- Based off #400 
- https://mattermost.atlassian.net/browse/MM-31039

MM-31039 - Previous reminder time becomes default for next reminder time

---

.circleci/config.yml

- We don't use coverage anymore

Move from make coverage to make test

---

plugin.json
server/manifest.go
webapp/src/manifest.js

bump to v1.2.0

---

webapp/src/components/post_menu.tsx

- Noticed this while working on the timeline stuff, and didn't want it lost in a feature branch for weeks.

Fix start incident double execute

---

tests-e2e/cypress/integration/frontstage/slash_command/test_spec.js
tests-e2e/cypress/support/ui_commands.js
tests-e2e/package-lock.json
tests-e2e/package.json

- This time the webapp's cypress code was a bit different than our previous code, and cypress needed to be updated to get the `ensureScrollable` option. 
- Updated cypress and related packages to match what we use in webapp.
- none

Fix e2e tests again

---

tests-e2e/cypress/integration/frontstage/incident_rhs_checklist_spec.js
webapp/src/components/checklist.scss
webapp/src/components/checklist_item.tsx

Deleting a task from an active incident.
https://mattermost.atlassian.net/browse/MM-32130

MM-32130 Deleting tasks from an active incident.

---

server/command/command.go
tests-e2e/cypress/integration/backstage/incident_list_spec.js
tests-e2e/cypress/integration/frontstage/rhs/footer_spec.js
tests-e2e/cypress/integration/frontstage/slash_command/test_spec.js
tests-e2e/cypress/support/server_api_commands.js
tests-e2e/cypress/support/ui_commands.js

- Final e2e fix for awhile (I hope)
- Some tests were failing locally, figured out why, here are the fixes.
- https://mattermost.atlassian.net/browse/MM-32431

MM-32431 - Fix local e2e tests

---

server/incident/filter_options.go
webapp/src/components/backstage/incidents/incident_list/incident_list.tsx

Fixing sorting on status.
https://mattermost.atlassian.net/browse/MM-32519

MM-32519 Fixing sorting on status.

---

.circleci/config.yml
tests-e2e/cypress/integration/frontstage/incident_rhs_list_spec.js
tests-e2e/cypress/support/plugin_api_commands.js

- Clicking on the LHS channel name broke for some reason (only on cloud). I don't fully understand why. Moved to using the cmd-k switcher.
- Turning on the master branch helps with debugging, so I'm leaving the job in, but ignoring it in all branches (until we need it).
- https://mattermost.atlassian.net/browse/MM-32544

MM-32544 - fix e2e

---

README.md

This links out to a page that doesn't appear to exist anymore.
N/A

Remove reference to contribution docs

---

server/incident/service.go
server/incident/service_test.go
tests-e2e/cypress/integration/frontstage/incident_creation_spec.js

This reverts commit 2a7169c92e3d11175f98ff1c1e484602b514217f.
N/A

Revert "MM-25755: promote incident commander to channel admin (#420)"

---

webapp/src/components/checklist_item.tsx

Removes checklist timestamps.
https://mattermost.atlassian.net/browse/MM-32744

MM-32744 Remove checklist item timestamps

---

server/incident/service.go

- Simple solution
- tests will fail until the fix is merged in another 3 PRs
- https://mattermost.atlassian.net/browse/MM-32637

MM-32637 - Incident reminders shouldn't apply on archiving

---

server/api/api.yaml
server/api/incidents.go
server/command/command.go
server/incident/incident.go
server/incident/mocks/mock_service.go
server/incident/mocks/mock_store.go
server/incident/service.go
server/sqlstore/incident.go
tests-e2e/cypress/integration/frontstage/rhs/timeline-spec.js
webapp/src/client.ts
webapp/src/components/checklist_item.tsx
webapp/src/components/rhs/rhs_shared.tsx
webapp/src/components/rhs/rhs_timeline_event_item.tsx
webapp/src/types/incident.ts
webapp/src/types/rhs.ts

- Can remove any event from the timeline
- Looks like:
- https://mattermost.atlassian.net/browse/MM-32547

MM-32547 - Remove any event from Timeline

---

tests-e2e/cypress/integration/backstage/incident_list_spec.js
tests-e2e/cypress/integration/frontstage/incident_rhs_checklist_spec.js
tests-e2e/cypress/integration/frontstage/rhs/footer_spec.js
tests-e2e/cypress/support/index.js
tests-e2e/cypress/support/test_commands.js
webapp/src/components/backstage/incidents/incident_list/incident_list.tsx
webapp/src/components/profile/profile_selector.scss
webapp/src/components/profile/profile_selector.tsx
webapp/src/hooks.ts

- Shift the assignee dropdown up if it goes past the window's `innerHeight`
- https://mattermost.atlassian.net/browse/MM-31913

MM-31913 Fix assignee dropdown

---

webapp/src/components/rhs/incident_details.scss
webapp/src/components/rhs/rhs_incident_summary.tsx
webapp/src/components/rhs/rhs_list_incident.tsx
webapp/src/components/rhs/rhs_shared.tsx

- Replaced `ProfileSelector` with `SmallerProfile` in rhs_incident_summary
- https://mattermost.atlassian.net/browse/MM-33790

MM-33790: Fix the reporter in the RHS is clickable but does nothing

---

webapp/src/components/checklist_item.tsx
webapp/src/components/rhs/rhs_timeline_event_item.tsx

- Small update to the confirm modal text. See the linked Ticket for the original, and the changes for the new text. Let me know if you can think of a better way to explain the effects, thanks!
- https://mattermost.atlassian.net/browse/MM-33309

MM-33309 - Update confirm modal text

---

server/api/incidents.go
server/command/command.go
server/incident/incident.go
server/incident/mocks/mock_service.go
server/incident/service.go
tests-e2e/cypress/integration/frontstage/incident_rhs_checklist_spec.js
tests-e2e/cypress/support/plugin_ui_commands.js
webapp/package-lock.json
webapp/src/actions.ts
webapp/src/client.ts
webapp/src/components/assets/buttons.tsx
webapp/src/components/assets/inputs.tsx
webapp/src/components/backstage/step_edit.tsx
webapp/src/components/backstage/styles.tsx
webapp/src/components/checklist_item.tsx
webapp/src/components/checklist_item_input.tsx
webapp/src/components/command_input.tsx
webapp/src/components/rhs/rhs_incident_tasks.tsx
webapp/src/components/rhs/rhs_shared.tsx
webapp/src/components/widgets/generic_modal.tsx

Allows editing of the incident task list. Supports add, remove, edit, and reorder operations.
https://mattermost.atlassian.net/browse/MM-33855

MM-33855 Ad-hoc Tasks

---

server/sqlstore/stats.go

Some old data on community is disrupting the stats. This helpfully hardens the queries to fix that.

Improve stats queries.

---

webapp/src/components/backstage/stats.tsx

Fixes the theme colors in the stats view. Not totally the best, but better designs for the stats view are coming. At least this doesn't burn your retinas. 
https://mattermost.atlassian.net/browse/MM-34604

MM-34604 Better stats colours

---

server/api/incidents_test.go

Fix merge error.

---

.circleci/config.yml

- Need to inject AWS env keys on master
- Turn on e2e tests on master (before deploying the plugin)
- none

Fix CI on master

---

plugin.json
server/api/api.go
server/config/configuration.go
webapp/src/browser_routing.ts
webapp/src/components/backstage/backstage.tsx
webapp/src/hooks.ts
webapp/src/make_update_main_menu.ts
webapp/src/types/settings.ts

Adding experimental features flag for users to turn on and off in the system console.
https://mattermost.atlassian.net/browse/MM-35051

MM-35051 Experimental features flag

---

.circleci/config.yml
server/api/incidents.go
server/permissions/permissions.go

- Found that we had a permissions function that wasn't doing what it said it was doing.
- It was named incorrectly. Luckily, it was only being used incorrectly in one place. But to avoid this mistake in the future I removed it and replaced all its calls with the correct permissions function.
- none

Fix permissions server-side

---

webapp/src/websocket_events.test.ts
webapp/src/websocket_events.ts

Avoid websocket reconnect errors if we reconnect and there is no active team or user.
https://mattermost.atlassian.net/browse/MM-35153

MM-35153: avoid reconnect errors

---

server/api/incidents.go
server/incident/incident.go
server/incident/mocks/mock_service.go
server/incident/service.go
server/telemetry/noop.go
server/telemetry/rudder.go
server/telemetry/rudder_test.go
webapp/src/components/rhs/rhs_timeline.tsx

I combed through the actions and properties of our current telemetry and the in-product experience, adding the following:
* remove timeline event
* ChecklistItem properties
* updated Incident and Playbook properties
* timeline_tab_filter_selected event to track additional timeline interactions
Proposing including this in v1.9 -- cc @prapti.
https://mattermost.atlassian.net/browse/MM-35244

MM-35244: updated telemetry

---

server/incident/service.go

The function `sendWebhookOnCreation` reads the incident data and sends it to the configured webhook URL. This is done in a goroutine, but the timeline events were populated after that routine was started. Moving the call after that makes the sent data reliable, with the expected timeline events always included.
I also changed the argument to the function to be passed by value, instead of pointer, as it is read-only (this, by itself, does not fix the issue, as the slice of events is still mutable).
https://mattermost.atlassian.net/browse/MM-35135
~~[ ] Telemetry updated~~
~~[ ] Gated by experimental feature flag~~
~~[ ] Unit tests updated~~

Fix race condition

---

tests-e2e/cypress/integration/backstage/playbook_creation_spec.js
webapp/src/components/backstage/playbook_edit.tsx
webapp/src/types/playbook.ts

- Default is now for playbooks to be accessible by everyone. 
~~- Default is now to create a public channel.~~

Set defaults for playbooks to be open. Access to all and create public channel.

---

webapp/src/components/backstage/new_playbook.tsx

- Don't know how this passed before

MM-35605 - Fix a linting error that snuck in somehow

---

webapp/src/components/checklist_item.tsx
webapp/src/components/widgets/text_with_tooltip_when_ellipsis.tsx

- Show a tooltip, but only for commands that ellipsis
- https://mattermost.atlassian.net/browse/MM-35650
[ ] ~~Unit tests updated~~

MM-35650 - Long slash commands don't ellipsis

---

server/api/api.yaml

I needed to generate an HTML API doc and had to make some tweaks to the API spec to get it to work
[ ] Telemetry updated
[ ] Gated by experimental feature flag
[ ] Unit tests updated

Fixed errors when rendering HTML

---

webapp/src/components/backstage/playbook_edit.tsx
webapp/src/types/playbook.ts

- Fix how we insert the default message on join, that was the problem.
- https://mattermost.atlassian.net/browse/MM-35951
[ ] ~~Unit tests updated~~

MM-35951 - Fix default message on join

---

README.md
plugin.json

Remove the header from the plugin settings and reword the hard requirement on an E20 license in the README.
--

Reword license mentions

---

webapp/src/index.tsx
webapp/src/make_update_main_menu.ts

Change the client-side licensing logic to hide Incident Collaboration on TE/E0/E10, despite server-side support for same. We'll expose this functionality alongside upcoming product suite changes.
Fixes: https://mattermost.atlassian.net/browse/MM-36122

MM-36122: delay e0/e10 release

---

server/command/command.go

Fix the `/timeline` command displaying publish/cancel retrospective events. 

Fix timeline command.

---

webapp/src/types/playbook.ts

correct grammar

---

webapp/src/components/backstage/backstage.tsx
webapp/src/components/backstage/incidents/incident_backstage/incident_backstage.tsx
webapp/src/components/backstage/playbook_edit.tsx

- Put the dashboard behind the experimental features flag
- https://mattermost.atlassian.net/browse/MM-36572

MM-36572 - Experimental features flag for new playbook dashboard

---

webapp/src/index.tsx
webapp/src/make_update_main_menu.ts

Make the plugin available for TE, E0 and E10 servers. Kind of revert (but not exactly) https://github.com/mattermost/mattermost-plugin-incident-collaboration/pull/578.
https://mattermost.atlassian.net/browse/MM-36713

MM-36713: Make the plugin available for all users

---

webapp/src/components/backstage/backstage.tsx
webapp/src/components/backstage/playbook_edit.tsx

- Remove experimental feature flag for Playbook Dashboard
- https://mattermost.atlassian.net/browse/MM-36707

MM-36707 - Remove experimental feature flag for Playbook Dashboard

---

webapp/src/components/backstage/backstage.tsx

Based on a [discussion](https://community-daily.mattermost.com/core/pl/bj9dczq79byfmgdw7b6dkyef3h) with @itao, preserving old links that might be embedded in chat or channel headers
N/A

redirect /incidents to /runs

---

server/api/playbook_runs.go
server/sqlstore/playbook_run_test.go
webapp/src/client.ts
webapp/src/components/backstage/playbook_runs/playbook_run_list/playbook_run_list.tsx
webapp/src/components/backstage/playbook_runs/playbook_run_list/status_filter.scss
webapp/src/components/backstage/playbook_runs/playbook_run_list/status_filter.tsx
webapp/src/components/backstage/playbooks/playbook_run_list/playbook_run_list.tsx
webapp/src/components/multi_select.tsx
webapp/src/types/playbook_run.ts

This PR adds capabilities to filter playbook run list using multiple statuses
https://github.com/mattermost/mattermost-server/issues/17861

[GH-17861] Modify the playbook run list status filter to be a multiselect like the RHS timeline filter

---

webapp/src/components/backstage/backstage.tsx

Swap runs icon.

---

README.md
client/client.go
client/doc.go
client/playbook_runs.go
client/playbooks.go
server/api/api.yaml
server/app/playbook_run_service_test.go
server/bot/poster.go
server/command/command.go
server/plugin.go
tests-e2e/cypress/support/index.js
tests-e2e/cypress/support/plugin_ui_commands.js
tests-e2e/db-setup/mm534.sql
webapp/src/make_update_main_menu.ts

- s/Incident Collaboration/Playbooks/
- Remove some instances of collaboration.
- Fixup README

Removing some references to old names.

---

server/sqlstore/playbook_run.go
server/sqlstore/support_for_test.go

- Bots in query should be capitalized for mysql
- none

Fix for table 'mattermost.bots' not found in query 

---

webapp/src/actions.ts
webapp/src/components/rhs/rhs_about.tsx
webapp/src/reducer.ts
webapp/src/selectors.ts
webapp/src/types/actions.ts

- Save the state of the collapsed about header per channel
- https://mattermost.atlassian.net/browse/MM-37508

MM-37508 - RHS About collapsed saved state per user

---

server/app/playbook_run_service.go
server/app/playbook_run_service_test.go
server/plugin.go

Remove channel from previous category and fix the concurrency bug
Fixes: https://mattermost.atlassian.net/browse/MM-37314

[MM-37314] Remove channel from prev category

---

webapp/src/components/rhs/rhs_checklists.tsx

- Return null if no visible tasks
- https://mattermost.atlassian.net/browse/MM-37533

MM-37533 - Empty checklists after filtering should omit the body

---

server/sqlstore/stats.go

- Omit bots in the participant count (like we do elsewhere)
- https://mattermost.atlassian.net/browse/MM-37546

MM-37546 - Fix for: Wrong participant count

---

server/app/playbook_run_service.go

When updating the status to Archived, reset the reminder timer so the RHS does not show a status update still scheduled in the future. Instead, it shows when the last status update was posted and styles the Post update button as tertiary.
https://user-images.githubusercontent.com/3924815/127842007-11cdc79d-3bcb-49ef-a09b-e02ef1dfe396.mp4
@abhijit-singh, do you think this makes sense from a UX viewpoint?
https://mattermost.atlassian.net/browse/MM-37538

MM-37538: Reset reminder when updating status to Archived

---

webapp/src/components/rhs/rhs_about.tsx
webapp/src/components/rhs/rhs_about_title.tsx

cherry-pick-671-672

---

webapp/src/components/backstage/playbook.scss
webapp/src/components/backstage/playbook_list.tsx
webapp/src/components/backstage/playbook_runs/playbook_run_list/playbook_run_list.scss
webapp/src/components/backstage/playbook_runs/playbook_run_list/playbook_run_list.tsx

This PR will split playbook name and team name
Fixes: https://mattermost.atlassian.net/browse/MM-37532

Mm 37532 split name and team

---

webapp/src/components/backstage/playbook_runs/playbook_run_list/playbook_run_list.scss
webapp/src/components/backstage/playbook_runs/playbook_run_list/playbook_run_list.tsx

This PR splits playbook run name and team name
Fixes: https://mattermost.atlassian.net/browse/MM-37532

Split run name and team name

---

webapp/src/components/rhs/rhs_home.tsx

- cherry pick #677 to release-1.16 branch

Cherry pick 677 to release-1.16

---

webapp/src/components/backstage/playbook_edit.tsx
webapp/src/components/backstage/template_selector.tsx
webapp/src/types/playbook.ts

Address a few capitalization issues found by @justinegeffen, and incorporate an updated feature template from @itao. In addition to @itao's [requested changes](https://community-daily.mattermost.com/core/pl/e4bdiiz59pnjbdo6yubhhrp8ay), I took the liberty to simplify down to "target release" (from cloud/self-managed) and a few other "obvious" tweaks. Let me know your thoughts!
Fixes: https://mattermost.atlassian.net/browse/MM-37548
Fixes: https://mattermost.atlassian.net/browse/MM-37588

MM-37588 updated templates

---

webapp/src/components/backstage/backstage.tsx
webapp/src/components/backstage/playbook_runs/playbook_run_backstage/playbook_run_backstage.tsx
webapp/src/components/backstage/playbooks/playbook_backstage.tsx
webapp/src/hooks/routing.ts

Updates the `document.title` to be:
- `Playbooks - [config.SiteName]` in backstage. 
- `[playbook.title] - Playbooks - [config.SiteName]` if viewing playbook. 
- `[run.name] Playbooks - [config.SiteName]` if viewing run.

Update document.title in backstage.

---

README.md

- just to create a new commit, from which to package a new version 
n/a

Small doc change

---

webapp/src/components/rhs/rhs_about_title.tsx

While we decide how to handle run titles decoupled from channel names, this PR completely disables the ability to edit the title from the RHS when the user has no permissions to change the channel name.
This mimics the feature to change the channel name from the channel header: the menu entry `Rename Channel` is only shown to users that have permissions to actually change it.
https://mattermost.atlassian.net/browse/MM-37678

MM-37678: Disallow title editing if user has no permissions to change channel name

---

server/sqlstore/playbook.go

I missed the playbooks SQL queries :cry:
N/A

COALESCE(CategoryName) when querying playbooks too

---

server/sqlstore/stats.go
server/sqlstore/stats_test.go
server/sqlstore/support_for_test.go

- Exclude bots in the select statement
- https://mattermost.atlassian.net/browse/MM-37701

MM-37701 - Fix: Active participants in stats graph is including bots

---

server/sqlstore/migrations.go
server/sqlstore/store_test.go

Fixes the creation and adds a migration to change the charset in the IR_System table to be utf8mb4 which is consistant with the rest of the system.
https://mattermost.atlassian.net/browse/MM-38208
Fixes https://github.com/mattermost/mattermost-server/issues/18021

MM-30208 Fix incorrect character set being used for IR_System table.

---

webapp/src/components/backstage/automation/input_keywords.tsx
webapp/src/components/backstage/automation/settings.tsx
webapp/src/components/backstage/playbook_edit.tsx

This PR implements keywords selector. It's an improved version of the https://github.com/mattermost/mattermost-plugin-playbooks/pull/608 (Will be closing the old one). It uses `react-select` component and does not implement pills from the scratch. 
https://user-images.githubusercontent.com/2340127/131167092-324a05dc-4fe6-4776-82a8-0ba1cf546061.mp4

Add keywords selector

---

webapp/src/components/backstage/runs_list/runs_list.tsx

- Add the my-runs-only filter to the isFiltering condition
- https://mattermost.atlassian.net/browse/MM-38254

MM-38254 - Fix for: Wrong filter summary text

---

server/app/playbook_service.go

- Change the url
- https://mattermost.atlassian.net/browse/MM-38245

MM-38245 - Fix for: ...playbooks.../edit/automation no longer deep links

---

server/api/playbook_runs.go

log playbook_runs permission error internally

---

webapp/src/components/rhs/rhs_about_title.tsx

Fixes the `/leave` bug
https://user-images.githubusercontent.com/2340127/133467467-640aabf2-1900-4e66-abff-055e52a382ec.mp4
Fixes: https://mattermost.atlassian.net/browse/MM-38256

[MM-38256] Fix /leave Bug

---

server/api/playbook_runs.go
tests-e2e/cypress/integration/frontstage/playbook_run_dialog_spec.js

Trim space before checking length.
Fixes: https://mattermost.atlassian.net/browse/MM-38439

MM-38438: Don't allow empty channel names.

---

server/app/playbook_run_service.go
server/app/playbook_run_service_test.go
server/httptools/client.go

Small improvment to outgoing webhooks.
https://mattermost.atlassian.net/browse/MM-37247

MM-37247 Improving outgoing webhooks.

---

webapp/src/components/rhs/rhs_home.tsx

Fixes SVG mask issue on FF
https://mattermost.atlassian.net/browse/MM-37541

MM-37541 Fix svg mask on FF

---

webapp/src/components/team/create_playbook_team_selector.tsx
webapp/src/hooks/general.ts

- Removed some unnecessary code, simplified it to not use the clientRect
- https://mattermost.atlassian.net/browse/MM-38037

MM-38037 - Fix for: Team selector opens off screen (in Playbooks backstage)

---

server/api/playbooks.go
server/api/playbooks_test.go

Unknown channels ie channels you don't have permissions to where being removed incorrectly on save. This fixes that. 
https://mattermost.atlassian.net/browse/MM-38734

MM-38734 Fix unknown channels being removed when somone without premissions saves playbook.

---

server/plugin.go

Change bot's username to `@playbooks`, display name to `Playbooks` and description to `Playbooks bot`.
@itao, do we want to change the bot's description to something more descriptive?
https://mattermost.atlassian.net/browse/MM-38566

MM-38566: Rename Playbooks bot

---

webapp/src/components/rhs/rhs_post_update.tsx

Adds a magic size to the icon to match the size of the other icons.
As an aside: I'm not sure I like how mdi handles sizes.
https://mattermost.atlassian.net/browse/MM-38852

MM-38852: Fix size of checkered flag icon

---

webapp/src/components/backstage/playbook_runs/playbook_run_backstage/playbook_run_backstage.tsx
webapp/src/components/backstage/runs_list/row.tsx

- As per Tao's message in the channel (quoted in the ticket) don't show the playbook info (even that there is a playbook) if the playbook is private and the user doesn't have access.
- https://mattermost.atlassian.net/browse/MM-38585

MM-38585 - Fix for: Rendering of private playbooks for users in a run

---

tests-e2e/cypress/integration/backstage/playbook_run_list_spec.js
webapp/src/components/backstage/playbooks/playbook_backstage.tsx
webapp/src/components/backstage/runs_list/filters.tsx
webapp/src/components/backstage/runs_list/runs_list.tsx

- Simplify the status filter, which fixes a couple bugs we found in the v1.20 fit&finish bug bash 
- https://mattermost.atlassian.net/browse/MM-38582

MM-38582 - Simplify status filtering widget for playbook runs

---

webapp/src/components/update_request_post.tsx

Fix linting issue probably introduced across today's merges.
None.

fix linting issue

---

server/app/mocks/mock_playbook_run_service.go
server/app/mocks/mock_playbook_run_store.go
server/app/playbook_run.go
server/app/playbook_run_service.go
server/command/command.go
server/sqlstore/playbook_run.go
server/sqlstore/playbook_run_test.go

- Does what it says on the tin
- Design
- Actual (I made some slight changes to the english, but there will be a polish pass later)
- POC ✅ 
- Include list of ongoing runs (<--- we're here)
- Include list of overdue updates
- Send digest once a day when user logs on
- Checklist directly in the digest (custom post)
- Design polish (if needed)
- e2e tests (once we have a firmed up design)
- Telemetry (total number of in-notification link clicks, unique users who click)
- https://mattermost.atlassian.net/browse/MM-38608

MM-38608 - Include list of Runs in Progress

---

.circleci/config.yml
.github/PULL_REQUEST_TEMPLATE.md
webapp/src/components/rhs/rhs_home_item.tsx

- Add CI step to validate i18n messages were properly extracted
- Add reminder in PR template
- part of https://mattermost.atlassian.net/browse/MM-38151

[MM-38151]: add i18n ci check

---

server/app/playbook_run_service.go

- Rearrange the sections based on feedback in the channel.
- Please let me know if there's anything else you'd like polished for the MVP.
When a section has no items:
It will say the same kind of message for each, e.g. `You have 0 total assigned tasks.` and `You have 0 runs currently in progress.`
https://mattermost.atlassian.net/browse/MM-38670

MM-38670 - Design polish

---

webapp/src/components/backstage/automation/patterned_text_area.tsx

This PR Fix number of webhooks check
Fixes: https://mattermost.atlassian.net/browse/MM-39570

[MM-39570] Fix number of webhooks check

---

webapp/src/components/backstage/playbooks/playbook.tsx
webapp/src/components/backstage/playbooks/playbook_preview_cards.tsx
webapp/src/components/checklist_item.tsx

Cherrypick #847 and #848 to release 1.21
--

Cherrypick #847 and #848 to release 1.21

---

server/api/bot.go
server/api/bot_test.go
server/app/permissions.go

Fix the API endpoint /start-trial
https://mattermost.atlassian.net/browse/MM-39465

MM-39465: API fix

---

server/api/bot.go
server/api/bot_test.go
server/app/permissions.go

Cherry-pick API fix into release-1.21
--

MM-39465: API fix (#863)

---

server/app/playbook_run_service.go
tests-e2e/cypress/integration/channels/rhs_spec.js

- Uses the feature from #860 to force the RHS open when a user clicks on todo digest links
- https://mattermost.atlassian.net/browse/MM-39171

MM-39171: Force RHS open when clicking from Todo list

---

tests-e2e/cypress/integration/runs/retrospective_spec.js
tests-e2e/cypress/support/plugin/api_commands.js

- adds a basic test for the retro functionality
I will probably add another test around the upgrade screen later, but I need to consider [MM-40034](https://mattermost.atlassian.net/browse/MM-40034) in more detail first for that
https://mattermost.atlassian.net/browse/MM-39897

[MM-39897] test spec for run retrospective

---

webapp/i18n/en.json
webapp/src/components/backstage/playbooks/playbook_preview_checklists.tsx
webapp/src/components/checklist_item.tsx
webapp/src/components/rhs/rhs_checklists.tsx
webapp/src/components/rhs/rhs_shared.tsx

Add collapsible (default expanded) task descriptions to the RHS.
https://user-images.githubusercontent.com/3924815/142251913-7bd61711-2a43-498b-bcba-f89457ac316d.mp4
https://mattermost.atlassian.net/browse/MM-39364

MM-39364: Inline task description in RHS

---

webapp/src/components/collapsible_checklist.tsx
webapp/src/components/rhs/rhs_checklists.tsx

- Subheaders are sticky now
https://user-images.githubusercontent.com/1490756/142899480-93627b3e-1075-4c62-b736-203862f247ed.mp4
- https://mattermost.atlassian.net/browse/MM-37531

MM-37531: Make subheaders in RHS sticky

---

webapp/src/components/backstage/playbook_runs/playbook_run_backstage/retrospective/timeline_event_item.tsx
webapp/src/components/profile/profile_selector.scss
webapp/src/components/rhs/rhs_shared.tsx

- Problem:
- While fixing, found another z-index bug:
Now fixed:
- https://mattermost.atlassian.net/browse/MM-40335

MM-40335: Fix for: z-index for owner dropdown is off

---

server/app/mocks/mock_playbook_run_service.go
server/app/playbook.go
server/app/playbook_run.go
server/app/playbook_run_service.go
server/app/playbook_run_service_test.go
server/app/playbook_service.go
server/telemetry/noop.go
server/telemetry/rudder.go

Add telemetry for:
* follow
* unfollow
* autofollow
* autounfollow
Fixes: https://mattermost.atlassian.net/browse/MM-40431

[MM-40431] Add telemetry to follow/unfollow

---

webapp/src/components/update_request_post.tsx

This PR fixes broken status update reminder select in RHS
https://user-images.githubusercontent.com/2340127/144250795-8355b767-c7f9-4a69-9a49-f65871b7dd13.mp4
Fixes: https://mattermost.atlassian.net/browse/MM-40170

Fix broken select in RHS

---

webapp/src/components/backstage/start_trial_notice.tsx

Fix crash on playbook usage page when you are the system admin on and E10 or unlicenced server. 
https://mattermost.atlassian.net/browse/MM-40503
https://mattermost.atlassian.net/browse/MM-40270

MM-40503/MM-40270: Fix formatted message page crash

---

webapp/src/components/backstage/backstage.tsx
webapp/src/components/backstage/playbooks/playbook_preview.tsx

This PR fixes unfilled screen of the playbook
Fixes: https://mattermost.atlassian.net/browse/MM-39958

[MM-39958] Fix screen fill for playbook view

---

webapp/src/components/rhs/rhs_checklists.tsx

- Fix unassigned tasks filter
- Add comments so we don't get confused again
- No e2e tests because we're not testing these (and pretty low return on investment, imo)
- https://mattermost.atlassian.net/browse/MM-40505

MM-40505: Fix: "Unassigned" and "Others" checklist filter broken

---

client/playbook_runs.go
server/api/playbook_runs.go
server/api_runs_test.go
webapp/src/client.ts

- Changed endpoint to PUT
- client method didn't exist so added that (and tests)
- https://mattermost.atlassian.net/browse/MM-40490

MM-40490: Endpoint to add a checklist item should be a POST, not PUT

---

webapp/src/components/checklist_item.tsx

Fix cannot assign tasks in RHS
- https://mattermost.atlassian.net/browse/MM-40748
---|---
Telemetry updated? | NA
Gated by experimental feature flag? | NA
Unit/E2E tests updated? | NA

MM-40748: Fix cannot assign tasks in RHS

---

server/api/playbooks.go
server/app/playbook_service.go

This PR makes `/restore` endpoint idempotent
Fixes: https://mattermost.atlassian.net/browse/MM-39899

[MM-39899] Make restore idempotent

---

tests-e2e/cypress/integration/playbooks/creation_button_spec.js

When a user is on multiple teams, they are shown a dropdown to pick which team the Playbook is being created for.
https://mattermost.atlassian.net/browse/MM-40684
- [:heavy_check_mark:] E2E tests updated

MM-40684: Tests for team selection when creating a Playbook

---

server/app/playbook_run_service.go
server/app/playbook_run_service_test.go
server/app/playbook_service.go
server/app/service_test.go
server/app/urls.go

This PR converts absolute urls to relative ones.
Fixes: https://mattermost.atlassian.net/browse/MM-40658

[MM-40658] Convert to relative URLs

---

webapp/src/components/create_playbook_modal.tsx
webapp/src/components/team/team_selector.tsx

Fix autoselection of teams in playbook creation modal so there is always a team selected. 
Part of: https://mattermost.atlassian.net/browse/MM-40862

Fix autoselection of team in playbook creation modal.

---

webapp/src/components/dot_menu.tsx

Fix the dot menus floating too far to the right.
https://mattermost.atlassian.net/browse/MM-40845

MM-40845 Fix the menu button opening too far right.

---

client/playbooks.go
server/api/playbooks.go
server/api_playbooks_test.go
server/app/export.go
server/app/export_test.go
server/app/playbook.go
webapp/package-lock.json

Server side of Export functionality. 
Decided to go with this approach for ease of use and to allow for checks to verify that export is being considered when fields are being added.
For an explanation of use see the comment above the Playbooks struct. (Improved wording of that comment welcomed!) 
https://mattermost.atlassian.net/browse/MM-40840

MM-40840 Server side of export functionality.

---

client/playbooks.go
server/api/playbooks.go
server/api_playbooks_test.go

Server side of import functionality. 
https://mattermost.atlassian.net/browse/MM-40842

MM-40842 Server side of import functionality.

---

webapp/src/components/checklist_item_input.tsx

- Added spacing.
- Same spacing as between the Cancel and Done buttons above on the same page
Before:
After:
- https://mattermost.atlassian.net/browse/MM-40965

MM-40965 - Fix for: Missing spacing between task and slash command

---

webapp/src/components/backstage/playbook_edit/automation/categorize_playbook_run.tsx

This PR fixes category selector styling.
Fixes: https://mattermost.atlassian.net/browse/MM-40964

[MM-40964] Fix category selector theme

---

server/app/playbook_run_service.go
server/app/playbook_run_service_test.go

Changes the user on the broadcast message from the owner to the creator.
https://mattermost.atlassian.net/browse/MM-40131

MM-40131 Fix broadcast creator.

---

webapp/src/hooks/general.ts

Fixes run list filters so they update properly. 
https://mattermost.atlassian.net/browse/MM-41212

MM-41212 Fix run list filters not persisting.

---

webapp/src/components/backstage/playbook_runs/playbook_run_backstage/retrospective/report.tsx

Publish button was highlighting on hover when disabled.
https://mattermost.atlassian.net/browse/MM-40868

MM-40868 Prevent hover for DisabledPrimaryButtonSmaller

---

server/bot/poster.go

- @justinegeffen I removed mentioning the sysadmin (since it's a message sent to the sysadmin). Would you like to edit the message further? (see linked ticket for context)
- https://mattermost.atlassian.net/browse/MM-37167

MM-37167 - Fix for: System admin prompt prompts system admin

---

webapp/src/components/backstage/toast_banner.tsx

This PR will fix toast in dark theme
https://user-images.githubusercontent.com/2340127/153838270-076866ab-b0fe-4207-9785-452b78d05fa6.mp4
Fixes: https://mattermost.atlassian.net/browse/MM-41725

[MM-41725] Toast dark theme

---

tests-e2e/cypress/integration/playbooks/creation_button_spec.js
tests-e2e/cypress/integration/playbooks/edit_spec.js
webapp/src/components/backstage/playbook_edit/playbook_edit.tsx
webapp/src/components/create_playbook_modal.tsx
webapp/src/components/templates/template_selector.tsx
webapp/src/selectors.ts
webapp/src/types/playbook.ts

For single team environments skip the create dialog when clicking on a template, automatically create the playbook, and land on the playbook preview screen.
https://user-images.githubusercontent.com/3191642/153639344-d63a98f0-99db-45ec-afda-901eb15aa733.mp4
https://mattermost.atlassian.net/browse/MM-41059

MM-41059 Automaticly create a playbook from template in single team enviroments.

---

webapp/src/components/backstage/playbook_edit/playbook_edit.tsx
webapp/src/components/backstage/playbooks/playbook.tsx
webapp/src/components/backstage/playbooks/playbook_preview_navbar.tsx
webapp/src/components/rhs/rhs_checklist_list.tsx
webapp/src/components/rhs/rhs_post_update.tsx
webapp/src/components/rhs/rhs_run_details.tsx

This PR adds telemetry for tutorials
Fixes: https://mattermost.atlassian.net/browse/MM-41675

[MM-41675] Telemetry for tutorials

---

client/playbook.go
server/api/playbooks.go
server/api_playbooks_test.go

Refactor playbook validation
https://mattermost.atlassian.net/browse/MM-41948

MM-41948 Refactor playbook validation.

---

server/api/playbooks.go
server/app/mocks/mock_playbook_service.go
server/app/playbook.go
server/app/playbook_service.go
server/telemetry/noop.go
server/telemetry/rudder.go
webapp/src/components/backstage/playbook_list_row.tsx
webapp/src/components/backstage/playbooks/playbook.tsx

This PR adds telemetry for import, export, duplicate
Fixes: https://mattermost.atlassian.net/browse/MM-41676

[MM-41676] Add telemetry for import, export, duplicate

---

webapp/src/components/backstage/playbook_edit/automation/assign_owner_selector.tsx
webapp/src/components/backstage/playbook_edit/automation/broadcast.tsx
webapp/src/components/backstage/playbook_edit/automation/categorize_playbook_run.tsx
webapp/src/components/backstage/playbook_edit/automation/invite_users_selector.tsx
webapp/src/components/backstage/profile_autocomplete.tsx
webapp/src/components/backstage/runs_list/checkbox_input.tsx
webapp/src/components/backstage/search_input.tsx
webapp/src/components/checklist_item.tsx

A recent update to compass icons removing older, deprecated glyphs broke our product because we hadn't updated to use those new glyphs. Fix that, while also aligning some styling.
Fixes: https://mattermost.atlassian.net/browse/MM-42246

MM-42246: fix compass icons

---

server/api/playbooks.go
server/api_playbooks_test.go
server/main_test.go

Fix import not working for unlicenced servers because licencing doesn't allow private playbooks.
https://mattermost.atlassian.net/browse/MM-42210

MM-42210 Fix import of private playbooks.

---

webapp/src/components/backstage/playbooks/playbook_preview.tsx

This PR fixes the z-order of the dropdown
Fixes: https://mattermost.atlassian.net/browse/MM-41581

[MM-41581] Fix dropdown z-order

---

webapp/src/components/assets/buttons.tsx
webapp/src/components/modals/update_run_status_modal.tsx
webapp/src/components/rhs/rhs_about.tsx

This PR fixes longer translations in the status update modal
Fixes: https://mattermost.atlassian.net/browse/MM-40860

[MM-40860] Fix long translations in status update modal

---

.circleci/config.yml

I added the license upload success/fail check back in now that the server issue there is fixed, and also updated legacy convenience images to new versions as [recommended by Circle](https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034).

e2e: CircleCI housekeeping

---

webapp/src/components/backstage/playbook_edit/playbook_edit.tsx
webapp/src/components/tutorial/tutorial_tour_tip/manager.ts
webapp/src/components/tutorial/tutorial_tour_tip/tutorial_tour_tip.tsx

After finishing/skipping the Playbook edit tour tip, it did not automatically navigate to the start point. This PR fixes issue, and now you are automatically navigated to the Checklists page
p.s. ignore  pulsating dot in the demo videos.
https://user-images.githubusercontent.com/4368372/159292123-5ae0e4f7-3f49-4c09-8b90-03111aba5876.mp4
https://user-images.githubusercontent.com/4368372/159292147-685c35cd-36ef-4103-bbe2-aa726b516316.mp4
https://mattermost.atlassian.net/browse/MM-42436

Mm 42436 playbooks edit onboarding should return to checklists

---

tests-e2e/cypress/integration/channels/general_actions_spec.js

I revised the setup slightly so that each action test happens in its own channel, and added a couple new tests.

e2e: update and add more action tests

---

server/main_test.go
tests-e2e/cypress/fixtures/ldap-add-user.ldif
tests-e2e/cypress/fixtures/ldap-reset-data.ldif
tests-e2e/cypress/fixtures/saml_ldap_users.json
tests-e2e/cypress/fixtures/saml_users.json

swap occurences of `test.com` to `example.com`
https://mattermost.atlassian.net/browse/MM-42017

MM-42017: Fix test data emails

---

webapp/src/components/command_input.tsx

Trash can icon for slash command when editing task when none defined 
https://mattermost.atlassian.net/browse/MM-42843

Mm 42843 hide trash icon command

---

webapp/src/components/checklist_item/command.tsx
webapp/src/components/checklist_item/duedate.tsx

This PR fixes hover effect for checklist item pills
https://user-images.githubusercontent.com/2340127/163462529-e3cbed1f-e7f8-447f-beee-8a66282c9454.mp4
Fixes: https://mattermost.atlassian.net/browse/MM-43429

[MM-43429] Fix hover effect for checklist item

---

webapp/src/components/checklist_item/command.tsx
webapp/src/components/command_input.tsx

This PR fixes the command dropdown in checklist item
https://user-images.githubusercontent.com/2340127/163465396-373876fa-57fe-4c30-90a3-d5f9e5c7ee51.mp4
Fixes: https://mattermost.atlassian.net/browse/MM-43430

[MM-43430] Fix command dropdown in checklist item

---

webapp/src/components/checklist_item/checklist_item.tsx

This PR hides the due date info for skipped and finished tasks.
https://mattermost.atlassian.net/browse/MM-43358

Hide due date for finished and skipped tasks

---

webapp/src/components/backstage/playbook_editor/outline/section_checklists.tsx

Add missing prop to SectionChecklist to be complaint with https://github.com/mattermost/mattermost-plugin-playbooks/pull/1156
Value is forced a true since there are no Draggable/droppable containers
N/A

add menuEnabled forced in outline section checklist

---

README.md

This PR adds the `Help wanted` section to the `README` file. This can increase the visibility of `Playbooks` tasks to the community..

Add help wanted section to the readme file

---

.gitlab-ci.yml

Adding this to `master` so I can start trying full scheduled runs.

e2e: Include `.gitlab-ci.yml`

---

tests-e2e/cypress/integration/channels/rhs/checklist_spec.js
webapp/i18n/en.json
webapp/src/components/rhs/rhs_about_buttons.tsx
webapp/src/components/rhs/rhs_checklist_list.tsx

Add the title to filter icon and kebab icon (rhs_about one) in RHS
Fixes https://mattermost.atlassian.net/browse/MM-43425

mm-43425 add missing titles in RHS icons 

---

.circleci/config.yml
webapp/src/client.ts

Apply the effects of https://mattermost.atlassian.net/browse/MM-40751 to Playbooks in the January ESR. Note that this is already fixed for newer versions of Playbooks that updated our webapp Client4 dependencies.
I opted to manually apply the patch here vs. bringing in all of the updated webapp dependencies.
Fixes: https://mattermost.atlassian.net/browse/MM-40751
Fixes: https://github.com/mattermost/mattermost-plugin-playbooks/issues/1175

MM-44241: ensure application/json

---

webapp/src/components/checklist/checklist_list.tsx

Remove the following error from the console during development:
None.

Fix console spam

---

webapp/src/components/checklist/collapsible_checklist.tsx
webapp/src/components/checklist_item/hover_menu.tsx

This PR fixes checklist UI issues
input text fix:
hover menu fix:
Fixes: 
https://mattermost.atlassian.net/browse/MM-44549
https://mattermost.atlassian.net/browse/MM-44553
https://mattermost.atlassian.net/browse/MM-44554

[MM-44549] Fix checklist ui issues

---

server/api/graphqli.html

Adding subresource integrity to the graphqli html.
https://mattermost.atlassian.net/browse/MM-44410

MM-44410 Add subresource integrity to graphql html

---

server/api/graphql_root.go
server/api/schema.graphqls
server/api_graphql_playbooks_test.go
server/app/playbook.go
server/sqlstore/playbook.go
webapp/src/graphql/generated_types.ts

Add handling for playbook metrics in GraphQL endpoint.

Add GraphQL metrics handing.

---

webapp/src/components/backstage/playbook_edit/automation/channel_access.tsx
webapp/src/components/backstage/playbook_editor/outline/section_actions.tsx
webapp/src/graphql/hooks.ts
webapp/src/hooks/general.ts

- Stabilizes `updatePlaybook` identity 
- Adds `useProxyState` hook to debounce side effects or upstream state-setting
- Debounces channel name input with `useProxyState`
- https://mattermost.atlassian.net/browse/MM-44498
---|---
Telemetry updated? |
Gated by experimental feature flag? |
Unit/E2E tests updated? |

MM-44498: Fix typing UX on channel name input

---

webapp/src/components/markdown_edit.tsx
webapp/src/components/text_edit.tsx

Adding ESC and Enter handing for text inputs. 
Shift-Enter saves for multiline inputs while unmodified enter saves for single line.
https://mattermost.atlassian.net/browse/MM-44508

MM-44508 Add ESC and Enter handing to text inputs.

---

webapp/src/components/rhs/rhs_about_description.tsx

Now you can save summary with `cmd+enter` on mac
Fixes: https://mattermost.atlassian.net/browse/MM-44556

Add cmd+enter support

---

webapp/src/components/rhs/rhs_home_item.tsx
webapp/src/hooks/routing.ts

This PR fixed the create playbook bug. 
I took the simpler approach to fix this. On create it will:
1. POST playbook creation to the server
2. Receive the id of the newly created playbook
3. Open up the edit view of the playbook
Fixes: https://mattermost.atlassian.net/browse/MM-44744

[MM-44744] Fix create playbook

---

server/app/actions_service.go

Scan Slack attachments (Title, PreText, Text, Footer)  for keywords.
Fixes: https://github.com/mattermost/mattermost-server/issues/20069

[MM-42914] Scan SlackAttachments for trigger

---

webapp/src/components/backstage/backstage.tsx
webapp/src/components/backstage/lhs_navigation.tsx
webapp/src/components/backstage/main_body.tsx
webapp/src/index.tsx

Adds just a very basic starting point for the LHS navigation. This is just so we can get started.
All of this is hidden behind the experimental features flag in the system console.
https://mattermost.atlassian.net/browse/MM-44748

MM-44748 Basic new LHS layout.

---

webapp/src/components/sidebar/group.tsx
webapp/src/components/sidebar/item.tsx
webapp/src/components/sidebar/sidebar.tsx

This PR adds playbook sidebar start files. Here is the example of the sidebar
https://user-images.githubusercontent.com/2340127/172856129-abe104ec-72e3-4d3a-9777-32295da931d8.mp4
Example is not provided in the PR.

Playbook sidebar starter

---

webapp/src/components/backstage/playbook_runs/playbook_run/playbook_run.tsx

Demo https://www.loom.com/share/c211de187c91420d83db118778684aad
Keep sticky header if we scroll in RDP.
Fix width when space is lower than 780px
No ticket

RDP header sticky when doing scroll

---

tests-e2e/cypress/integration/channels/rhs_spec.js

To be honest, I still don't know why those failures are occurring. I'm unable to reproduce locally, and nothing seems out of the ordinary in the CI video artifacts. These changes are passing repeatedly though.

e2e: Fix RHS failures

---

webapp/src/components/checklist_item/command.tsx
webapp/src/components/create_playbook_modal.tsx
webapp/src/components/dropdown.tsx
webapp/src/components/team/team_selector.tsx
webapp/src/components/widgets/generic_modal.tsx

Fix 2 tickets
- https://mattermost.atlassian.net/browse/MM-45609
- https://mattermost.atlassian.net/browse/MM-45610

MM-45609, MM-45610: fix team selector nav issue, fix command open/close

---

webapp/i18n/en.json
webapp/src/components/sidebar/group.tsx
webapp/src/components/sidebar/item.tsx
webapp/src/components/sidebar/playbooks_sidebar.tsx
webapp/src/components/sidebar/sidebar.tsx

This PR adds view all links to the LHS
https://user-images.githubusercontent.com/2340127/178324588-280c2d36-6d98-452e-95ba-50ddc756a846.mp4
Fixes: https://mattermost.atlassian.net/browse/MM-44751

Add view all links

---

webapp/i18n/en.json
webapp/src/components/backstage/playbook_runs/playbook_run/rhs_info_overview.tsx

use followers to be more consistent since all the rest of the items are nouns
no ticket

use followers noun to be consistent

---

server/api/categories.go
server/app/playbook.go
server/sqlstore/playbook.go
server/sqlstore/playbook_test.go

This PR fixes playbooks filter for LHS. See https://community.mattermost.com/core/pl/omaawaxwtfgf7eff55bunc7fic for details

Filter playbooks for LHS

---

webapp/src/components/backstage/playbook_editor/playbook_editor.tsx
webapp/src/components/backstage/playbook_runs/playbook_run/header.tsx
webapp/src/hooks/general.ts

This PR adds support of favoriting runs.  Currently you'll have to refresh to see changes in the LHS
Fixes: https://mattermost.atlassian.net/browse/MM-45728

[MM-45728] Favoriting runs

---

server/sqlstore/category.go
server/sqlstore/category_test.go

This PR fixes the category store
see
https://community.mattermost.com/core/pl/c93bqizxminhmk6uzchykr38ee

Fix category store

---

tests-e2e/cypress/integration/playbooks/creation_button_spec.js
tests-e2e/cypress/integration/playbooks/edit_metrics_spec.js
tests-e2e/cypress/integration/playbooks/overview_spec.js

Update specs that were disabled during Better Playbook Editor work. 
https://mattermost.atlassian.net/browse/MM-45611

e2e: Update temporarily ignored specs

---

webapp/src/components/backstage/playbook_editor/playbook_editor.tsx
webapp/src/components/backstage/playbook_runs/playbook_run/header.tsx

This pr fixes favorites theme bug
See conversation here https://community.mattermost.com/core/pl/r9g4wbchzpyszrrejnggf5tqro

Fix favorites theme bug

---

tests-e2e/cypress/integration/runs/rdp_main_retrospective_spec.js

Improve state management in e2e test [as suggested](https://github.com/mattermost/mattermost-plugin-playbooks/pull/1303#discussion_r918072318) 
Fixes https://mattermost.atlassian.net/browse/MM-45651

change e2e to avoid mixing state

---

server/app/category.go
server/app/category_service.go
server/plugin.go
server/telemetry/noop.go
server/telemetry/rudder.go

This PR adds telemetry for favoriting runs and playbooks
Fixes: https://mattermost.atlassian.net/browse/MM-45417

Add favoriting telemetry

---

webapp/i18n/en.json
webapp/src/components/backstage/lhs_navigation.tsx
webapp/src/components/sidebar/playbooks_sidebar.tsx
webapp/src/hooks/general.ts

This PR switches `Favotire` to `Favorites`
See the conversation https://community.mattermost.com/core/pl/r9g4wbchzpyszrrejnggf5tqro

Switch Favorite to favorites

---

tests-e2e/cypress/integration/playbooks/edit_metrics_spec.js
tests-e2e/cypress/integration/playbooks/edit_spec.js
tests-e2e/cypress/integration/playbooks/status_update_spec.js
tests-e2e/cypress/integration/runs/rdp_main_header_spec.js
tests-e2e/cypress/integration/runs/rdp_rhs_runinfo_spec.js
tests-e2e/cypress/support/plugin/ui_commands.js

Attempting to resolve issues seen in the flaky list:
https://app.circleci.com/insights/github/mattermost/mattermost-plugin-playbooks/workflows/ci/tests?branch=master&reporting-window=last-30-days

e2e: Flake fixes

---

webapp/src/components/backstage/backstage.tsx
webapp/src/components/backstage/playbook_runs/playbook_run/playbook_run.tsx
webapp/src/components/backstage/playbook_runs/playbook_run/rhs.tsx
webapp/src/components/backstage/playbook_runs/playbook_run/rhs_info_overview.tsx
webapp/src/components/backstage/playbook_runs/playbook_run/status_update.tsx
webapp/src/components/checklist_item/assign_to.tsx

Use cssgrid to be more resilient to changes in other external points (i.e team bar, app bar).
Fixes https://mattermost.atlassian.net/browse/MM-45855

migrate RHS UI management to  cssgrid

---

webapp/src/components/backstage/playbook_runs/playbook_run/rhs_participants.tsx

At RHS participants (run details page), force a padding-bottom at participant list to ensure we can scroll until the last item
Fixes https://mattermost.atlassian.net/browse/MM-45876

force padding at rdp participants 

---

webapp/src/components/checklist_item/checklist_item.tsx

This PR hides due date info for finished/skipped tasks on the RDP.
https://user-images.githubusercontent.com/4368372/180964956-57ba5896-8852-4310-92c8-1cb3b9f7c3f4.mp4
https://mattermost.atlassian.net/browse/MM-45961

Add hiding due date if task is done

---

server/api/graphql.go
server/api/graphql_playbook.go
server/api/graphql_root.go
server/api/graphql_run.go
server/api/schema.graphqls
server/api_graphql_playbooks_test.go
server/plugin.go
webapp/src/components/sidebar/playbooks_sidebar.tsx
webapp/src/graphql/generated_types.ts
webapp/src/graphql/hooks.ts
webapp/src/graphql/playbook.graphql
webapp/src/graphql/runs.graphql
webapp/src/graphql_client.ts
webapp/src/hooks/general.ts
webapp/src/hooks/routing.ts
webapp/src/index.tsx

Move playbooks LHS listing to GraphQL to allow for basic automatic updates of the LHS.
Note that this is the first iteration of this and only works locally. 
Favorites:
https://user-images.githubusercontent.com/3191642/180880689-5504327f-ef50-40a2-9d6c-a83bce7e57fe.mp4
New Playbooks:
https://user-images.githubusercontent.com/3191642/180880781-b1a69d34-d3a5-4f16-b8b6-6e6ad9bb4784.mp4
https://mattermost.atlassian.net/browse/MM-45575

MM-45575 GraphQL updates for LHS list

---

webapp/src/components/rhs/rhs_post_update.tsx
webapp/src/components/rhs/rhs_post_update_button.tsx

Fixes post update button from being squished.

Fix RHS post update button.

---

webapp/src/components/sidebar/playbooks_sidebar.tsx

Adds a poll every 60 seconds to update the LHS with any new content. Only active if you have the LHS in view.

Add LHS polling.

---

webapp/src/components/backstage/playbook_list_row.tsx

We already do this:
So now do this too:
Fixes: https://mattermost.atlassian.net/browse/MM-40666

Explain why run is disabled

---

webapp/src/components/backstage/playbook_runs/playbook_run/context_menu.tsx
webapp/src/components/backstage/playbook_runs/playbook_run/playbook_run.tsx

This PR fixes run long name truncate bug in the RDP. 
https://user-images.githubusercontent.com/4368372/185310622-b13062ee-9f36-4209-aede-e14ab8236fa7.mp4
https://mattermost.atlassian.net/browse/MM-46094

Mm 46094 long run name issue

---

webapp/src/components/backstage/playbook_editor/playbook_editor.tsx
webapp/src/components/checklist/checklist_list.tsx
webapp/src/components/checklist/collapsible_checklist.tsx

Fixes issue with the checklist dropdown menu, It was falling behind the checklist title.
**Before** 
https://user-images.githubusercontent.com/4368372/185943097-6d26eee9-bfe4-4b7f-b6af-68f8d38d0626.mp4
**After**
https://user-images.githubusercontent.com/4368372/185943145-1d0349e0-d637-4515-86a5-2d2d8f2f4dba.mp4
https://mattermost.atlassian.net/browse/MM-46120

Fix checklist dropdown z-index issue

---

webapp/src/components/backstage/playbook_runs/playbook_run/status_update.tsx

Fixes RDP > Status updates section > `View all updates` button width.
https://user-images.githubusercontent.com/4368372/185971771-4e8b86b4-942a-4c6c-b1a6-a4beea3fe6c4.mp4
https://mattermost.atlassian.net/browse/MM-46383

Fix view all updates button width

---

webapp/src/components/modals/run_playbook_modal.tsx

Fix import globalstate, fix CI lint
problem introduced in https://github.com/mattermost/mattermost-plugin-playbooks/pull/1245, pr was started long time ago and import style changed (and webapp version)
no ticket

fix type for globalstate -> fix CI

---

webapp/src/components/checklist/generic_checklist.tsx

Remove border-radius in add-new-task button at checklist.
Fixes https://mattermost.atlassian.net/browse/MM-44507

remove rounded edges in add-new-task button

---

webapp/src/components/backstage/playbook_editor/controls.tsx
webapp/src/components/backstage/playbook_list.tsx
webapp/src/components/backstage/restore_playbook_modal.tsx

Fixes playbook list refresh issue after archived playbook is restored.
https://user-images.githubusercontent.com/4368372/186358112-bfff24bc-dd68-4720-a58e-0912df01505e.mp4
https://mattermost.atlassian.net/browse/MM-46084

Fix playbooks list refresh issue

---

webapp/i18n/en.json
webapp/package-lock.json
webapp/package.json
webapp/src/components/actions_modal.tsx
webapp/src/components/backstage/backstage.tsx
webapp/src/components/backstage/playbook_editor/controls.tsx
webapp/src/components/backstage/playbook_editor/outline/section_actions.tsx
webapp/src/components/backstage/playbook_list_row.tsx
webapp/src/components/backstage/playbook_runs/playbook_run/finish_run.tsx
webapp/src/components/backstage/runs_list/row.tsx
webapp/src/components/modals/run_playbook_modal.tsx
webapp/src/components/rhs/rhs_about_buttons.tsx
webapp/src/components/rhs/rhs_home.tsx
webapp/src/components/rhs/rhs_home_item.tsx
webapp/src/components/rhs/rhs_post_update.tsx
webapp/src/components/update_post.tsx

Migrate all material design icons that exist in compass to compass icons.
The SVG version of the icons has been used for most of the cases. The icons library has been upgraded to have the default color to currentColor, which makes the code far simpler.
**Deprecated code that has not been migrated because it's about to be removed**
- webapp/src/components/backstage/playbook_runs/playbook_run_backstage/retrospective/timeline_event_item.tsx:14:import {mdiClockOutline} from '@mdi/js';
- webapp/src/components/backstage/playbook_runs/playbook_run_backstage/playbook_run_backstage.tsx:11:import {mdiLightningBoltOutline} from '@mdi/js';
- webapp/src/components/backstage/playbook_edit/styles.tsx:5:import {mdiClockOutline, mdiCurrencyUsd, mdiPound} from '@mdi/js';
- …

migrate md icons  to compass

---

webapp/src/components/backstage/playbook_list_row.tsx

With #1245 merged, playbook-list can now use the new Start Run Dialog.
- https://mattermost.atlassian.net/browse/MM-46679

Use new Start Run Dialog in Playbook List

---

server/api/api.go
server/api/graphql.go
server/api_graphql_playbooks_test.go
server/api_playbooks_test.go
server/api_runs_test.go
server/sqlstore/actions.go
server/sqlstore/playbook.go
server/sqlstore/playbook_run.go
server/sqlstore/store.go
server/sqlstore/user_info.go
tests-e2e/cypress/integration/lhs_spec.js

This PR cherry picks a portion of 4dd42f9e174a5acb1c4ccad6b038f5b819226dd5.
https://mattermost.atlassian.net/browse/MM-46829

MM-46829: Cherry-pick limit size incoming requests (v1.32/v7.3)

---

.circleci/config.yml
server/api/api.go
server/api/graphql.go
server/api_graphql_playbooks_test.go
server/api_playbooks_test.go
server/api_runs_test.go
server/sqlstore/actions.go
server/sqlstore/playbook.go
server/sqlstore/playbook_run.go
server/sqlstore/store.go
server/sqlstore/user_info.go

This PR cherry picks a portion of 4dd42f9e174a5acb1c4ccad6b038f5b819226dd5.
https://mattermost.atlassian.net/browse/MM-46829

MM-46829: Cherry-pick limit size incoming requests (v1.29, v7.1 & v7.2)

---

.github/PULL_REQUEST_TEMPLATE.md

Sometimes the pr summary is complex enough to have it's own sections. Why not the current sections are bigger (##) to create more space for smaller headings (### and ####)
Nope

more nesting allowed for pull requests

---

webapp/src/components/sidebar/item.tsx

Fixes collapsed lhs
https://user-images.githubusercontent.com/2340127/190161971-f41c6242-bf1f-4776-a524-22fa446c40d1.mp4
Fixes: https://mattermost.atlassian.net/browse/MM-46891

[MM-46891] Fix collapsed LHS

---

CODEOWNERS

I18n: codeowners for auto-request PR reviews

---

README.md

Short description of how to actually get Playbooks setup for development.

Add some dev guidance to the README

---

tests-e2e/cypress/integration/playbooks/overview_spec.js
webapp/src/actions.ts
webapp/src/components/backstage/playbook_editor/controls.tsx
webapp/src/components/backstage/playbook_list_row.tsx
webapp/src/components/modals/run_playbook_modal.tsx

Add LHS refresh after:
- starting a run from the Playbook details page
- starting a run from the Playbooks list page
https://user-images.githubusercontent.com/4368372/192954396-7c6c467c-c087-486c-8eea-9641024132b2.mp4
https://mattermost.atlassian.net/browse/MM-46914

Mm 46914 refresh lhs after starting run

---

.circleci/config.yml

Store failed test screenshots. (Easily jump to any failures instead of scrubbing through the videos.)

CI: store screenshots

---

README.md

Added short description where db migrations should be placed and why.

Add DB migration info to README

---

server/api/graphql_root_run.go
server/api/schema.graphqls
server/api_graphql_runs_test.go
server/app/playbook_run.go
server/app/playbook_run_service.go
tests-e2e/cypress/integration/runs/rdp_rhs_participants_spec.js
tests-e2e/cypress/support/plugin/api_commands.js
webapp/src/components/backstage/playbook_runs/playbook_run/add_participant_modal.tsx
webapp/src/graphql/generated_types.ts
webapp/src/graphql/hooks.ts
webapp/src/graphql/runs.graphql

Add the ability to automatically add participants to the channel when inviting them.
https://user-images.githubusercontent.com/4368372/198704724-af0e18e0-c21d-4fd1-a0ac-0b7e9c53c713.mp4
https://github.com/mattermost/mattermost-plugin-playbooks/issues/1417

1417 add participants automatically

---

tests-e2e/cypress/integration/runs/rdp_main_checklist_spec.js
webapp/src/components/backstage/rhs/task_inbox/task.tsx
webapp/src/components/checklist/checklist_list.tsx
webapp/src/components/checklist/generic_checklist.tsx
webapp/src/components/checklist_item/checklist_item.tsx
webapp/src/components/checklist_item/checklist_item_draggable.tsx
webapp/src/components/checklist_item/inputs.tsx
webapp/src/components/rhs/rhs_checklist_list.tsx
webapp/src/components/rhs/rhs_run_details.tsx

This PR adds toast when a channel member with read-only access to the run tries to change the checklist state.
https://user-images.githubusercontent.com/4368372/200803827-ff705ebd-d090-4ecd-bf88-be2ee675e828.mp4
Fixes #1553

1553 read only rhs toast on checklist

---

client/playbook_run.go
client/playbook_runs.go
server/api_runs_test.go
server/app/playbook_run_service.go
server/main_test.go
tests-e2e/cypress/integration/channels/app_bar_spec.js
tests-e2e/cypress/integration/channels/rhs/home_spec.js
tests-e2e/cypress/integration/channels/rhs/template_spec.js
tests-e2e/cypress/support/api/preference.js
tests-e2e/cypress/support/plugin/ui_commands.js
webapp/src/components/assets/buttons.tsx
webapp/src/components/backstage/runs_list/filters.tsx

See https://github.com/mattermost/mattermost-plugin-playbooks/pull/1576

cherry-pick getowners into 1.32

---

client/playbook_run.go
client/playbook_runs.go
server/api_runs_test.go
server/app/playbook_run_service.go
server/main_test.go

See https://github.com/mattermost/mattermost-plugin-playbooks/pull/1576

cherry-pick getOwners into 1.29

---

client/playbook_run.go
client/playbook_runs.go
server/api_runs_test.go
server/app/playbook_run_service.go
server/main_test.go
tests-e2e/cypress/integration/channels/app_bar_spec.js
tests-e2e/cypress/integration/channels/rhs/template_spec.js
tests-e2e/cypress/integration/channels/rhs_spec.js
tests-e2e/cypress/support/api/preference.js
tests-e2e/cypress/support/plugin/ui_commands.js
webapp/src/components/backstage/runs_list/filters.tsx

See https://github.com/mattermost/mattermost-plugin-playbooks/pull/1576

cherry-pick getOwners into 1.31

---

webapp/src/components/backstage/playbook_runs/playbook_run/status_update.tsx

Clicking on the `Request update...` button was not displaying the confirmation modal, and because of that, e2e tests were failing. Replaced the custom hook on the component, and it has fixed the issue. Unfortunately don't know why this fix worked.
No ticket

Fix request update e2e test issue

---

assets/i18n/sv.json

FIxes syntax error in the translation file. CI/CD was wailing because of this issue.
No ticket

Fix sv translation file syntax issues

---

webapp/src/components/checklist_item/assign_to.tsx
webapp/src/components/checklist_item/checklist_item.tsx
webapp/src/components/checklist_item/command.tsx
webapp/src/components/checklist_item/hover_menu.tsx
webapp/src/components/profile/profile_selector.tsx

Make UX of skipped tasks more consistent with the following changes:
- The title, as well as the assignee-, command-, and due-date-button are greyed out and allow no interaction when the task is skipped, except the task is being edited
- The assignee-, and due-date-button are hidden from the hover menu when the task is skipped
- Reduced opacity for text and buttons of skipped tasks, except the hover menu
- Run-command button hidden when the task is skipped
[MM-40657](https://mattermost.atlassian.net/browse/MM-40657)
[MM-48410](https://mattermost.atlassian.net/browse/MM-48410)

MM-42517 Make UX of skipped tasks more consistent

---

webapp/i18n/en.json
webapp/package-lock.json
webapp/package.json
webapp/src/components/rhs/rhs_run_list.tsx

Visual improvments to runs list sorting.
Fixes #1603

RHS runs sort list visual improvements.

---

webapp/src/components/assets/loading_spinner.tsx
webapp/src/components/rhs/rhs_main.tsx
webapp/src/components/rhs/rhs_run_list.tsx

Adds loading states for playbooks RHS
Gifs below on simulated slow connection. 
Fixes #1605

Loading states for runs RHS

---

tests-e2e/cypress/tsconfig.json

Adds typings for `@testing-library/cypress` for better autocomplete and docs access.
None

chore: add testing-library typings

---

webapp/src/components/rhs/rhs_run_list.tsx
webapp/src/components/rhs/rhs_title_common.tsx

Updates RHS header for runs list:
Fixes #1602

Modify RHS header for runs list

---

tests-e2e/cypress/integration/playbooks/feedback_spec.js
tests-e2e/cypress/integration/runs/taskinbox_spec.js
webapp/src/components/global_header_right.tsx

This feature was mistakenly put behind the experimental feature flag when we introduced task inbox (partly because I reused the code task inbox introduced to host this feature :p)
Fixes: https://mattermost.atlassian.net/browse/MM-45738

MM-45738: ensure give feedback button

---

webapp/src/components/backstage/follow_button.tsx

This seems to avoid a React hook order issue as well (I think).

Avoid instantiating styled components inside a render

---

webapp/src/components/checklist_item/task_actions_modal.tsx

- Task Actions user search now allows searching all users in the installation
- N/A

TaskActions: Allow searching all users

---

tests-e2e/cypress/integration/channels/rhs/about_spec.js
webapp/src/components/rhs/rhs_about.tsx
webapp/src/components/rhs/rhs_about_title.tsx

Fix inline edit in channels rhs that updated channel name when changing run name
Fixes https://github.com/mattermost/mattermost-plugin-playbooks/issues/1674

update channel run name does not imply changing channel name

---

tests-e2e/cypress/integration/channels/rhs/list_spec.js
webapp/src/components/give_feedback_button.tsx
webapp/src/components/rhs/rhs_run_list.tsx

Add give feedback button to Channels RHS run list.
it's not positioned fixed, it appears at the end of the list.
Fixes https://github.com/mattermost/mattermost-plugin-playbooks/issues/1600

add give feedback to run rhs list

---

server/app/playbook_run_service.go

- Exclude from daily digest message information about tasks without a due date. 
- Skip the daily digest message If there are only tasks due after tomorrow or without a due date.
https://mattermost.atlassian.net/browse/MM-47796
[MM-47796]: https://mattermost.atlassian.net/browse/MM-47796?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Exclude tasks without a due date from daily digest

---

webapp/src/components/rhs/rhs_participants.tsx

Fix jumpy participant list in RHS by using a transparent border when not hovered and adjusting margins and paddings.
[Screencast from 05.01.2023 16:41:57.webm](https://user-images.githubusercontent.com/8669935/210821343-11d083cf-0168-4006-97c4-3d17320a4950.webm)
[MM-48913](https://mattermost.atlassian.net/browse/MM-48913)
[MM-48913]: https://mattermost.atlassian.net/browse/MM-48913?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MM-48913 Fix jumpy participant list in RHS

---

server/api/actions.go
server/api/bot.go
server/api/playbook_runs.go

This PR adds missing returns to api error handlers. 
Also added missed returns in `playbook_runs.go` file(not in the ticket).
Fixes: https://mattermost.atlassian.net/browse/MM-49579

[MM-49579] Add missing returns

---

server/app/playbook_run_service.go

After some debugging and help from @crspeller, I understood that an encoding/gob [issue](https://github.com/golang/go/issues/4609) was playing here. 
Removed comment and simplified code.
Fixes https://mattermost.atlassian.net/browse/MM-48464

simplify code and remove comment at getowners

---

Makefile

Fixes build for Macs.
See [conversation](https://community.mattermost.com/core/pl/1yzxitk31ff1jd16958zp8f5wa) for details

Fix build for Mac

---

webapp/graphql_gen.ts

Fix a minor typo in gql_gen config

---

tests-e2e/cypress/integration/playbooks/edit_spec.js
tests-e2e/cypress/integration/playbooks/list_spec.js
webapp/src/components/backstage/playbook_editor/controls.tsx
webapp/src/components/backstage/playbook_list.tsx

Update LHS when duplicating a playbook.
Fixes #1772

GH-1772 Update LHS when duplicating playbook

---

webapp/src/components/backstage/playbook_editor/playbook_editor.tsx

Fix background not spanning whole content and header disappearing due to that.
[Screencast from 02.02.2023 14:07:19.webm](https://user-images.githubusercontent.com/8669935/216333297-a578c551-8aff-4e21-aa1e-005a54e956c6.webm)
Fixes #1765

GH-1765 Fix editor background and header issue

---

.github/actions/e2e-test/action.yaml
.github/actions/test-with-db/action.yaml
.github/workflows/cd.yaml

Remove working directory directive from cd

fix(ci): Hotfix for CD pipeline

---

webapp/webpack.config.js

Both of these changes are to fix some issues with the Webpack dev server since I run my local instance on https after having had to set it up for something else.

Update Webpack dev server configuration in product mode

---

server/api/graphql_root_playbook.go
server/api/playbooks.go
server/api_graphql_playbooks_test.go
server/api_playbooks_test.go
server/app/permissions_service.go
server/main_test.go

Backport of https://github.com/mattermost/mattermost/pull/23279

Backport: MM-52476 Fix guest users access to playbooks. (#23279)

---

server/api/graphql_root_playbook.go
server/api/playbooks.go
server/api_graphql_playbooks_test.go
server/api_playbooks_test.go
server/app/permissions_service.go
server/main_test.go

Backport: MM-52476 Fix guest users access to playbooks. (#23279) (#1849)

---

.github/workflows/cd.yaml

Dynamically generating and injecting GitHub token used for GH tool
Ticket: https://mattermost.atlassian.net/browse/CLD-5870

[fix] CI fix cd/deploy-release step

---

.github/workflows/cd.yaml

CI release deletion of `latest` artifact
Rationale documented @ https://mattermost.atlassian.net/browse/CLD-5870?focusedCommentId=153109
Ticket: https://mattermost.atlassian.net/browse/CLD-5870

[fix] CI release deletion of `latest` artifact

---

README.md

Updated legacy links

---

server/api/graphql_root_run.go
server/api_graphql_runs_test.go

https://mattermost.atlassian.net/browse/MM-54401

Fix task actions validation

---

server/api_runs_test.go
server/app/permissions_service.go

Adding checks for team permissions when accessing runs. 
https://mattermost.atlassian.net/browse/MM-54989

MM-54989 Fix team run team interaction.

---

server/api/actions.go
server/api_actions_test.go
server/app/action.go
server/app/actions_service.go
server/safemapstructure/safemapstructure.go
server/safemapstructure/safemapstructure_test.go

Prevents extra JSON from being stored in the DB for channel actions.
https://mattermost.atlassian.net/browse/MM-54130

Prevent extra JSON from being stored in actions.

---

server/api/graphql_root_run.go
server/api_graphql_runs_test.go

Fix task actions validation (#1871)

---

e2e-tests/tests/integration/playbooks/channels/rhs/status_update_spec.js
e2e-tests/tests/integration/playbooks/channels/rhs_spec.js
e2e-tests/tests/integration/playbooks/playbooks/edit/checklists_spec.js
e2e-tests/tests/integration/playbooks/playbooks/start_run_spec.js
e2e-tests/tests/support/ui/global_header.js
e2e-tests/tests/support/ui/post.ts

Fixing E2E Tests

---

server/api/graphql_root_run.go

Fix guest user access to public channel runs. 
https://mattermost.atlassian.net/browse/MM-56461

MM-56461 fix guest user access to public runs.

---

server/app/reminder.go

Fixing websocket behavour. 
https://mattermost.atlassian.net/browse/MM-56463

Fix websocket events

---

server/api/graphql_root_run.go
server/api/playbook_runs.go
server/api_graphql_runs_test.go

Fixing moving channel links behavour. 
https://mattermost.atlassian.net/browse/MM-56158

Fixing moving channel links behaviour

---

server/command/command.go

Fixing `/playbook add <postid>` slash command.
https://mattermost.atlassian.net/browse/MM-56345

Fixing behavour of /playbook add slash command.

---

server/api/playbook_runs.go
server/api_runs_test.go

Fixing slash commands on runs. Note this doesn't fix the UI around this feature. Followup ticket: https://mattermost.atlassian.net/browse/MM-57509
https://mattermost.atlassian.net/browse/MM-56343

Fixing slash commands on runs

---

server/api/playbook_runs.go
server/app/playbook_run_service.go

Simplifying permissions check for slash command permissions
https://mattermost.atlassian.net/browse/MM-56343
Also see: https://hub.mattermost.com/private-core/pl/fggnupqbz3nxbmorgapdepfcyr

Simplify permissions check

---

.config/notice-file/config.yaml
.gitignore
NOTICE.txt

Introduce new packages on NOTICE.txt file 
Related PR: https://github.com/mattermost/delivery-platform/pull/121 
https://mattermost.atlassian.net/browse/CLD-6877

feat: Introduce new notice file generator integration

---

e2e-tests/tests/integration/playbooks/playbooks/overview_spec.js
e2e-tests/tests/integration/playbooks/runs/rdp_general_spec.js
webapp/src/components/backstage/main_body.tsx
webapp/src/components/backstage/playbook_editor/playbook_editor.tsx

Only accept valid MM ids in URLs
https://mattermost.atlassian.net/browse/MM-58843

[MM-58843] Only accept valid MM ids in URLs

---

e2e-tests/tests/integration/playbooks/channels/general_actions_spec.js
server/api/signal.go
server/plugin.go

Cherry Pick of MM-58432 - #1911

Cherry Pick of MM-58432 - #1911

---

e2e-tests/tests/integration/playbooks/api/graphql_errors_spec.js
server/api/graphql.go
server/api_graphql_runs_test.go

Cherry pick of MM-58791 - #1927

Cherry pick of MM-58791 - #1927

---

e2e-tests/tests/integration/playbooks/playbooks/overview_spec.js
e2e-tests/tests/integration/playbooks/runs/rdp_general_spec.js
webapp/src/components/backstage/main_body.tsx
webapp/src/components/backstage/playbook_editor/playbook_editor.tsx

Cherry pick of MM-58843 - #1920

Cherry pick of MM-58843 - #1920

---

webapp/src/components/actions_modal.tsx
webapp/src/components/backstage/playbook_edit/metrics/metrics.tsx
webapp/src/components/backstage/public_private_selector.tsx
webapp/src/components/backstage/search_input.tsx
webapp/src/components/backstage/styles.tsx
webapp/src/components/markdown_textbox.tsx
webapp/src/components/modals/run_playbook_modal.tsx
webapp/src/components/rhs/rhs_run_details_tour_dialog.tsx
webapp/src/components/widgets/confirmation_modal_light.tsx
webapp/src/components/widgets/generic_modal.tsx

Fixes an issue with the preview text overlapping dropdown items in the create playbook modal. Also fixes issues with playbooks modals spacing/layout.
Fixes: https://github.com/mattermost/mattermost/issues/27536
Fixes: https://github.com/mattermost/mattermost/issues/26269
Jira: https://mattermost.atlassian.net/browse/MM-58173
Jira: https://mattermost.atlassian.net/browse/MM-56861
| Before | After |
|---|---|
| <img width="683" alt="image" src="https://github.com/user-attachments/assets/23372bb1-ccd3-41ff-a8d8-fa21e40c18d4"> | <img width="625" alt="image" src="https://github.com/user-attachments/assets/37b859d8-e689-4d33-9d41-5d4244ba7d41"> |
| <img width="678" alt="image" src="https://github.com/user-attachments/assets/00c4d6be-f9b2-45fd-94f4-52ec0b269de2"> | <img width="673" alt="image" …

MM-58173 fix overlapping UI and modals

---

webapp/src/components/rhs/rhs_run_list.tsx

Fixes https://github.com/mattermost/mattermost/issues/28365
Jira https://mattermost.atlassian.net/browse/MM-54343
##Screenshots
Before:- 
After:- 
~- [ ] Telemetry updated~
~- [ ] Gated by experimental feature flag~
~- [ ] Unit tests updated~

RHS header styling fixed

---

webapp/src/components/backstage/status_badge.tsx

Fixes a minor theme issue which caused the status badge label to be unreadable in the Quartz theme.
<table>
<tr><td>Before</td><td>After</td></tr>
<tr><td><img width="390" alt="image" src="https://github.com/user-attachments/assets/ff52f82f-040d-441d-8594-ae58aa6d5a38"></td><td><img width="397" alt="image" src="https://github.com/user-attachments/assets/1a3f08b8-733c-4841-b16e-72d733e303af"></td></tr>
<tr><td><img width="418" alt="image" src="https://github.com/user-attachments/assets/c02c246a-dcd5-4653-8ed1-fbd302a74a53"></td><td><img width="418" alt="image" src="https://github.com/user-attachments/assets/2132aa5c-7ad1-4191-a516-de86de844ddf"></td></tr>
</table>
Jira: https://mattermost.atlassian.net/browse/MM-61479
- Please test in all themes (Denim, Sapphire, Quartz, Indigo, Onyx)
- …

fixed theme color for status badge

---

webapp/src/components/backstage/rhs/rhs.tsx

Fixes: https://mattermost.atlassian.net/browse/MM-61478

MM-61478: fix alignment for backstage RHS

---

server/api/playbook_runs.go
server/api/signal.go
server/api_runs_test.go

Fixes the keywords posts. 
https://mattermost.atlassian.net/browse/MM-61242

Fixing keywords post

---

.github/actions/e2e-test/action.yaml
.github/workflows/ci.yaml

- Fixed failed tests
https://mattermost.atlassian.net/browse/MM-64741

MM-64741 E2E/Test: Fix failed tests

---

webapp/package-lock.json
webapp/package.json
webapp/webpack.config.js

Remove `styled-components` from webpack externals and provide `process` to fix problem with multiple instances of same version of styled-components.
(Styles working)
https://mattermost.atlassian.net/browse/MM-63782

MM-63782: Use own styled-components

---

webapp/package-lock.json
webapp/package.json
webapp/webpack.config.js

Cherry-pick #2043; Own styled-components for Playbooks v1
https://mattermost.atlassian.net/browse/MM-63730
https://mattermost.atlassian.net/browse/MM-63782

Own styled-components for Playbooks v1

---

.github/workflows/ci.yaml
webapp/src/components/backstage/playbook_runs/playbook_run/rhs_timeline.tsx

Upload artifacts to S3

---

e2e-tests/tests/integration/playbooks/playbooks/status_update_spec.js

It might or might not fix the issue, I managed to have a few commits working in a row 😅 Worst come to worst, nothing changed, the test code is not less valid.
MM-65776

[MM-65776] Try to mitigate flaky test 

---

server/api/api.yaml

Add yaml docs for the rest API
no ticket, this is on top of #2065
also a second commit to reflect some changes I had some hard time finding: https://github.com/mattermost/mattermost-plugin-playbooks/pull/2089#discussion_r2406891078

Add missing conditional docs to REST api
